### ISSUE TITLE
NativeScript support 

### ISSUE THREAD

**Issue by calbear47** [apollographql/apollo-angular#102]
I am about to start a new project with ng2. I plan on re-using a lot of my services/core logic from my ng2 app in a NativeScript app. Will angular2-apollo play nicely with NativeScript?

**Comment by Urigo** [comment]
@calbear47 there shouldn't be any reason I it would not work, but I haven't tried it yet.
Would love to see an example app from you, and help you out making sure it works nicely

**Comment by iguissouma** [comment]
@calbear47 @Urigo 
I did some experiment with angular-cli, apollo, native-script(used nativescript-ng2-magic).
I had some issues:
1) redux/lib/index.js line 38 process variable is not defined, so I deleted this condition process.env.NODE_ENV !== 'production' && 
2) app then started but got error on simulator
![image](https://cloud.githubusercontent.com/assets/9085108/18797430/368e763c-81ce-11e6-94a3-54d5010591d8.png)

3) I didn't get the mobile and web working with the same template/css paths on app.component.ts:
for the web I use relative paths
```
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css']

})
```
to get the app running on ios simulator I have to use 

```
@Component({
  selector: 'app-root',
  templateUrl: './app/app.component.html',
  styleUrls: ['./app/app.component.css']

})
```
   

The repository is here if any want to investigate:
[native-angular-apollo](https://github.com/iguissouma/native-angular-apollo)

@Urigo 
With NativeScript we can utilize every JavaScript library that does not depend on browser-specific APIs such as the DOM.

I used this module to integrate web and mobile:
[nativescript-ng2-magic](https://github.com/NathanWalker/nativescript-ng2-magic)

**Comment by calbear47** [comment]
@Urigo Thanks, I'll keep you posted. It's still a couple months out. 

@iguissouma Thanks for the info. However, you'll be writing different views/styles for your NativeScript app then the ones you used for your web app...so the components and dependencies could be totally different. I was planning on just re-using services, and maybe some core components...Thoughts?

**Comment by iguissouma** [comment]
@calbear47 yes you'll be writing different views *.tns.html for native script and *.html for web ans use some component, that's the idea about  nativescript-ng2-magic. for dependencies it's separate the web and mobile has his own package.json.

You can take alook also to this advanced angular see to see how to share code between the different apllication web/mobile/desktop [angular2-seed-advanced](https://github.com/NathanWalker/angular2-seed-advanced)

The idea is not to duplicate your services for web and mobile, so if you have to fix something, you fixed on one place.

I'm just doing some tests not planing to do something for real.
@Urigo can share more thoughts about sharing code between web mobile, and what's the best strategy.

**Comment by iguissouma** [comment]
Resolved the error 2 ang got a new error:
 
```
CONSOLE ERROR file:///app/tns_modules/trace/trace.js:160:30: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
CONSOLE ERROR file:///app/tns_modules/trace/trace.js:160:30: ns-renderer: null is not an object (evaluating 'this.client.watchQuery')
        
        watchQuery@file:///app/tns_modules/angular2-apollo/build/src/Angular2Apollo.js:30:104
        ngOnInit@file:///app/app/app.component.js:23:31
        detectChangesInternal
        detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9566:39
        detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9671:52
        detectChanges@file:///app/tns_modules/@angular/core/bundles/core.umd.js:7668:37
        forEach@[native code]
        tick@file:///app/tns_modules/@angular/core/bundles/core.umd.js:7089:49
        _loadComponent@file:///app/tns_modules/@angular/core/bundles/core.umd.js:7067:22
        bootstrap@file:///app/tns_modules/@angular/core/bundles/core.umd.js:7058:32
        forEach@[native code]
        _moduleDoBootstrap@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6960:53
        file:///app/tns_modules/@angular/core/bundles/core.umd.js:6928:49
        invoke@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:190:33
        onInvoke@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6242:47
        invoke@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:189:42
        run@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:83:49
        file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:60
        invokeTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:42
        onInvokeTask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6233:51
        invokeTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:54
        runTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:123:57
        drainMicroTaskQueue@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:355:42
        promiseReactionJob@[native code]
        UIApplicationMain@[native code]
        start@file:///app/tns_modules/application/application.js:234:26
        bootstrapModule@file:///app/tns_modules/nativescript-angular/platform.js:97:26
        anonymous@file:///app/main.js:34:57
        evaluate@[native code]
        moduleEvaluation@[native code]
        [native code]
        promiseReactionJob@[native code]
8:28:33 AM - Compilation complete. Watching for file changes.

```

**Comment by iguissouma** [comment]
- Inject Angular2Apollo service

For some reason Injecting Angular2Apollo does not work properly on nativescript like below and leads to null object:

```
 // Inject Angular2Apollo service
  constructor(apollo: Angular2Apollo) {
    console.log('constructor try to initialise apollo');
    this.apollo = apollo;
  }
```
the code below does not work too

```
 // Inject Angular2Apollo service
  constructor(private apollo: Angular2Apollo) {
    console.log('constructor try to initialise apollo');
  }
```

So, I init it manually like below to get it working:

```
  constructor() {
    this.apollo = new Angular2Apollo(client);
  }
```

- can't find the variable `process` 
 
NativeScript can't find the variable `process` on the redux lib `nativescript/node_modules/redux/lib/combineReducers.js`

So I defined a process variable as a workaround like below on combineReducers.js
```
'use strict';
var process= process ||  {}
process.env = process.env || {}
```

-  Allowing iOS to use clear http protocol

I added this line to info.plist on the nativescript project
```
<key>NSAppTransportSecurity</key>
  <dict>
  	<key>NSAllowsArbitraryLoads</key>
  	<true/>
  </dict>
```

- finally the app is working

After allowing iOS to use clear http protocol, the app is woking, I can get a list of users from the apollo-server like the hello-world sample on angular2-apollo repo.

![image](https://cloud.githubusercontent.com/assets/9085108/18809168/b9c72858-8275-11e6-9c2a-e01c6033c951.png)

**Comment by kamilkisiela** [comment]
@iguissouma Have you used `ApolloModule.withClient(client)` inside your main module that is bootstraped?

**Comment by iguissouma** [comment]
Yeah I resolved that error, 
You're right `ApolloModule.withClient(client)` was missing.

I got Apollo working on NativeScript with some tweaks.

**Comment by kamilkisiela** [comment]
Could you describe those tweaks? It would help us a lot :+1:

**Comment by iguissouma** [comment]
I already described problems/solution, I will do more tests and keep you updated.
Thanks for the great work.

**Comment by Urigo** [comment]
@iguissouma would be great to have blog post/tutorial from you about how to create a sample project

**Comment by Urigo** [comment]
@iguissouma nice post, can you shoot me an email, I want to help you improve it a bit if you like

**Comment by mcorcuera** [comment]
To fix the issue related with `process variable is not defined` without modifying the redux code, you can also add this in your entry file, before any import:

```javascript
global.process = {
    env: {}
};
```

**Comment by iguissouma** [comment]
@mcorcuera You are right, "process" doesn't exist as part of NativeScript.
You can pollyfill it by adding to your our main.ts `global.process =  {env: {}};`
and that will make process and its env work globally in the app as a empty variable.

I mentioned that on this [blog post](https://medium.com/@iguissouma/using-graphql-inside-an-angular-native-nativescript-app-using-apollo-756a344cd486), the blog need to be updated to latest apollo client.

**Comment by dudanogueira** [comment]
Hi! I am trying to use apollo with nativescript, but can't even start... I am new to nativescript AND relatively new to angular AND definitely to apollo/graphql, so pardon my ignorance here ;)

I noticed that, after installing the apollo libs:
`npm install apollo-client apollo-angular graphql-tag --save`

I can't run tns run android anymore. If I remove, everything is back to "normal".

This is the error I get:

```
tns run android
Executing before-prepare hook from /home/dudanogueira/dev/unimed/MyProject/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /home/dudanogueira/dev/unimed/MyProject/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.1.6
node_modules/@types/async/index.d.ts(93,27): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(96,32): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(101,32): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(104,37): error TS2304: Cannot find name 'IterableIterator'.
node_modules/@types/async/index.d.ts(109,29): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(112,34): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(117,29): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(120,34): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(128,32): error TS2304: Cannot find name 'IterableIterator'.
node_modules/@types/async/index.d.ts(133,29): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(136,34): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(141,32): error TS2304: Cannot find name 'IterableIterator'.
node_modules/@types/async/index.d.ts(142,27): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(145,32): error TS2304: Cannot find name 'IterableIterator'.
node_modules/@types/async/index.d.ts(150,28): error TS2304: Cannot find name 'IterableIterator'.
node_modules/@types/async/index.d.ts(153,33): error TS2304: Cannot find name 'IterableIterator'.

node_modules/@types/async/index.d.ts(159,32): error TS2304: Cannot find name 'IterableIterator'.
node_modules/@types/isomorphic-fetch/index.d.ts(10,11): error TS2300: Duplicate identifier 'Headers'.

node_modules/@types/isomorphic-fetch/index.d.ts(19,13): error TS2300: Duplicate identifier 'Headers'.
node_modules/@types/isomorphic-fetch/index.d.ts(33,14): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.
node_modules/@types/isomorphic-fetch/index.d.ts(42,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'string[] | Headers | { [index: string]: string; }', but here has type 'any'.

node_modules/@types/isomorphic-fetch/index.d.ts(43,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'body' must be of type 'BodyInit', but here has type 'any'.
node_modules/@types/isomorphic-fetch/index.d.ts(46,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'mode' must be of type 'RequestMode', but here has type 'string'.
node_modules/@types/isomorphic-fetch/index.d.ts(47,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'credentials' must be of type 'RequestCredentials', but here has type 'string'.

node_modules/@types/isomorphic-fetch/index.d.ts(48,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'cache' must be of type 'RequestCache', but here has type 'string'.

node_modules/@types/isomorphic-fetch/index.d.ts(55,11): error TS2300: Duplicate identifier 'Request'.
node_modules/@types/isomorphic-fetch/index.d.ts(72,13): error TS2300: Duplicate identifier 'Request'.
node_modules/@types/isomorphic-fetch/index.d.ts(83,5): error TS2687: All declarations of 'status' must have identical modifiers.

node_modules/@types/isomorphic-fetch/index.d.ts(84,5): error TS2687: All declarations of 'statusText' must have identical modifiers.
node_modules/@types/isomorphic-fetch/index.d.ts(85,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'HeaderInit', but here has type 'any'.

node_modules/@types/isomorphic-fetch/index.d.ts(85,5): error TS2687: All declarations of 'headers' must have identical modifiers.
node_modules/@types/isomorphic-fetch/index.d.ts(88,11): error TS2300: Duplicate identifier 'Response'.
node_modules/@types/isomorphic-fetch/index.d.ts(99,13): error TS2300: Duplicate identifier 'Response'.

node_modules/tns-core-modules/declarations.d.ts(3,15): error TS2300: Duplicate identifier 'Request'.

node_modules/tns-core-modules/declarations.d.ts(36,15): error TS2300: Duplicate identifier 'Headers'.
node_modules/tns-core-modules/declarations.d.ts(46,5): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(56,15): error TS2300: Duplicate identifier 'Response'.

node_modules/tns-core-modules/declarations.d.ts(72,5): error TS2687: All declarations of 'status' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(73,5): error TS2687: All declarations of 'statusText' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(74,5): error TS2687: All declarations of 'headers' must have identical modifiers.

TypeScript compiler failed with exit code 1
```

**Comment by iguissouma** [comment]
@dudanogueira Make sure your tsconfig.json is configured with the folowing options“noEmitHelpers”: false, and “noEmitOnError”: false

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": false,
        "noEmitOnError": false
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": false,
        "noEmitOnError": false
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}
```

**Comment by dudanogueira** [comment]
@iguissouma , yes! that did the trick.

also, is good to state that global.process = {env: {}}; must come on the top of the main.ts and main.aot.ts 

I lost some time on this one.

Now I am enjoying the Apollo lib. Just lost some time figuring out the whole fetch policy. Let's see how it gets :)

**Comment by kamilkisiela** [comment]
Welcome Apollo Angular 1.0! [Integrating with NativeScript](https://www.apollographql.com/docs/angular/features/nativescript.html)

**Comment by yassern** [comment]
Hello,
Seems that it doesn't work with graphql subscriptions and websockets.
At installing the package `apollo-link-ws` it requires the peer dependencie `subscriptions-transport-ws` and when i tried to npm install that  I'm was getting the `error TS2688: Cannot find type definition file for 'node'.`.
More details also on https://github.com/NativeScript/nativescript-angular/issues/1285.

**Comment by kamilkisiela** [comment]
I think it would be nice to create an Apollo Link that takes advantage of a WebSocket implementation of NativeScript for Angular (something like @angular/common/http but for WS).
