### ISSUE TITLE
Angular-Material pagination does not leverage cache to paginate quickly

### ISSUE THREAD

**Issue by bsbechtel** [apollographql/apollo-angular#1031]
**Intended outcome:**

The Apollo cache stores paginated data so cycling back through data is instant and we don't have to wait on data to load from the server. The issue is specifically noticeable when using Angular-Material's MatPaginator, but I suspect any paginating framework would experience the same issue.

**Actual outcome:**

Each time a PageEvent is fired (moving forward or backward), query is sent to the server and the user must wait several seconds for the next bunch of data to load. Concatenating fetchMoreResults with the previous results does not work with Angular-Material. The table and pagination framework expects data to be delivered for the specific page requested (e.g., page 0, 10 results per page)

**How to reproduce the issue:**

https://stackblitz.com/edit/simple-apollo-angular-example-vn8jhu

**Versions**

    "@angular/animations": "7.0.0",
    "@angular/cdk": "^7.0.1",
    "@angular/common": "7.0.0",
    "@angular/compiler": "7.0.0",
    "@angular/core": "7.0.0",
    "@angular/forms": "7.0.0",
    "@angular/http": "7.0.0",
    "@angular/material": "^7.0.1",
    "@angular/platform-browser": "7.0.0",
    "@angular/platform-browser-dynamic": "7.0.0",
    "@angular/pwa": "^0.11.4",
    "@angular/router": "7.0.0",
    "@angular/service-worker": "^7.1.4",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "apollo-angular": "^1.5.0",
    "apollo-angular-link-http-batch": "^1.4.0",
    "apollo-cache-inmemory": "^1.3.12",
    "apollo-cache-persist": "^0.1.1",
    "apollo-client": "^2.4.0",
    "apollo-link": "^1.2.0",
    "apollo-link-context": "^1.0.12",
    "apollo-link-retry": "^2.2.8",
    "graphql": "^0.13.2",
    "graphql-tag": "^2.10.0",

**Comment by bsbechtel** [comment]
I updated the reproduction example so it's working properly now

**Comment by kamilkisiela** [comment]
You don't always have to use built-in and recommended solution of pagination. Easiest solution of your problem would be to use RxJS's `switchMap` or similar operator + a stream that passes `limit` and `offset`, or `page` and whatever.

Conceptual model:
1. `variables$` -> Stream of variables (`{ limit: number, offset: number }`).
2. Use `mergeMap` on `variables$`
3. Take variables to create another stream which is your actual query.
4. Then whenever you change variables, it fetches new data.

**Comment by bsbechtel** [comment]
@MaximS your example is what I was looking to implement. Thank you :-) I do feel like it should be a little more intuitive how pagination works with the cache, as the example in the docs is really operating under the assumption that you are wanting to fetchMore for an infinite list, not a paginated table. I will close for now, though it would still be nice to see improvements here.
