### ISSUE TITLE
How do I use afterLink + service in new configuration?

### ISSUE THREAD

**Issue by alexander-tarasenko** [apollographql/apollo-angular#1062]
Need help or want to talk all things Apollo Angular? Issues here are reserved for bugs and feature requests, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-angular` tag): https://stackoverflow.com/questions/tagged/apollo-angular
Ok, so I have the setup when everything is done in separate apollo module.
Note that it is done in a function, not in constructor of the class. It means I can't inject service anywhere. But I need to inject my auth service. Any suggestions?
Here it is
```
export function createApollo(httpLink: HttpLink) {
  const http = httpLink.create({ uri });
  const tokenMiddleware = new ApolloLink((operation, forward) => {
 ...
  });

  const errorHandler = onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors)
      graphQLErrors.map(({ message, locations, path }) => {
        console.log(message);
        // console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`)
      });
    if (networkError) {
      const errorStatus = networkError['error'].errors[0].status;
      if(errorStatus === 401) {
        // How do I use service here...?
      }
    }
  });

  return {
    link: from([tokenMiddleware, errorHandler, http]),
    cache: new InMemoryCache(),
  };
}
```

**Comment by kamilkisiela** [comment]
The answer is, use Angular's Dependency Injection. You can pretty much use DI anywhere you want. Here's an example of how it might work:

https://stackblitz.com/edit/apollo-angular-links-as-tokens?file=app%2Fapollo%2Ferror-link.ts

**Comment by elincognito** [comment]
Using Angular's Dependency Injection how can i avoid circular dependencies in my case AuthService uses Apollo and my graphql.module.ts i need to access my AuthService to access a jwt token

```export function createApollo(httpLink: HttpLink, authService: AuthService) {

    const http = httpLink.create({uri});

    const middleware = setContext(() => ({
        headers: new HttpHeaders().set('Authorization', authService.getToken() || '')
    }));

    return {
        link: middleware.concat(http),
        cache: new InMemoryCache()
    };
}

@NgModule({
    exports: [ApolloModule, HttpLinkModule],
    providers: [
        AuthService,
        {
            provide: APOLLO_OPTIONS,
            useFactory: createApollo,
            deps: [HttpLink, AuthService],
        },
    ],
})
export class GraphQLModule {
}```

gives me a circular dep injection issue

**Comment by marcoacevey** [comment]
> Using Angular's Dependency Injection how can i avoid circular dependencies in my case AuthService uses Apollo and my graphql.module.ts i need to access my AuthService to access a jwt token
> 
> ```
> 
> export function createApollo(httpLink: HttpLink, authService: AuthService) {
> 
>     const http = httpLink.create({uri});
> 
>     const middleware = setContext(() => ({
>         headers: new HttpHeaders().set('Authorization', authService.getToken() || '')
>     }));
> 
>     return {
>         link: middleware.concat(http),
>         cache: new InMemoryCache()
>     };
> }
> 
> @NgModule({
>     exports: [ApolloModule, HttpLinkModule],
>     providers: [
>         AuthService,
>         {
>             provide: APOLLO_OPTIONS,
>             useFactory: createApollo,
>             deps: [HttpLink, AuthService],
>         },
>     ],
> })
> export class GraphQLModule {
> }
> ```
> 
> gives me a circular dep injection issue

same problem here :(
Using Injector.get not worcking.
