### ISSUE TITLE
Query variables parameter is badly serialized when using GET method in production

### ISSUE THREAD

**Issue by mrfoster** [apollographql/apollo-angular#1096]
**Intended outcome:**

I would like to use a GET method to allow query caching using ```httpLink.create({uri, method: 'GET'})```

**Actual outcome:**

This works correctly for development with ```ng serve``` but when built for production or using ```ng serve --prod``` the variables query parameter is serialized as ```[object Object]``` instead of ```{"currency":"USD"}```

I can see there is a test assertion but I'm not too sure how it can be executed with production optimizations: https://github.com/apollographql/apollo-angular/blob/d185116b2d2306a40b12db747a058621211e2e92/packages/apollo-angular-link-http/tests/HttpLink.spec.ts#L205

**How to reproduce the issue:**

Example: https://github.com/mrfoster/ng-apollo-link-bug-1

Steps to recreate:
- ```ng new apollo-angular-test```
- ```ng add apollo-angular```
- Change the line in ```graphql.module.ts``` from ``` httpLink.create({uri})``` to ```httpLink.create({uri, method: 'GET'})```
- Create a query that accepts variables
```
query Rates($currency: String!) {
  rates(currency: $currency) {
    currency
    rate
  }
}
```
- Start using ```ng serve --prod```

**Comment by Stradivario** [comment]
Following logic i am here at http-common module: https://github.com/apollographql/apollo-angular/blob/master/packages/apollo-angular-link-http-common/src/utils.ts

I see that we have restriction for GET  requests https://github.com/apollographql/apollo-angular/blob/master/packages/apollo-angular-link-http-common/src/utils.ts#L11

So my logic here is that maybe GET request are using different fetcher
i think the variables should be prepared here before creating body object: https://github.com/apollographql/apollo-angular/blob/d185116b2d2306a40b12db747a058621211e2e92/packages/apollo-angular-link-http/src/HttpLink.ts#L28 

Anyway the hard fix is to Stringify req.body.variables before the request here:
https://github.com/apollographql/apollo-angular/blob/d185116b2d2306a40b12db747a058621211e2e92/packages/apollo-angular-link-http/src/HttpLink.ts#L51

And we pray :D 

hahaha 

I will look for this bug :)

**Comment by mrfoster** [comment]
@Stradivario - thanks for looking into this! I think I can see the problem now. 

The code below is deciding whether to stringify the parameters based on variable name.  However the variable names will be mangled as part of the production minification and will no longer match.

https://github.com/apollographql/apollo-angular/blob/b9ee478b56aa7448617c9aa4d47efac4ab43dca6/packages/apollo-angular-link-http-common/src/utils.ts#L12-L13

**Comment by kamilkisiela** [comment]
Could you prepare a PR?

**Comment by mrfoster** [comment]
@kamilkisiela It was nothing to do with name mangling. The optimisations seemed to simply remove these lines:
https://github.com/apollographql/apollo-angular/blob/b9ee478b56aa7448617c9aa4d47efac4ab43dca6/packages/apollo-angular-link-http-common/src/utils.ts#L34-L38

**Comment by KillerCodeMonkey** [comment]
having the same issue, but we simply use `apollo-link-http`

**Comment by mrfoster** [comment]
@KillerCodeMonkey That's good to know, I hadn't realised it can be swapped out.  I don't expect it would work with angular universal though.

**Comment by KillerCodeMonkey** [comment]
@mrfoster maybe something like cross-fetch works with ssr. so a node fetch is used on serverside and browser fetch on clientside

**Comment by intellix** [comment]
For those who can't wait:

https://github.com/ds300/patch-package
**patches/apollo-angular-link-http-common+1.5.0.patch**
```
diff --git a/node_modules/apollo-angular-link-http-common/fesm5/ng.apolloLink.httpCommon.js b/node_modules/apollo-angular-link-http-common/fesm5/ng.apolloLink.httpCommon.js
index 823a940..b9f4ddc 100644
--- a/node_modules/apollo-angular-link-http-common/fesm5/ng.apolloLink.httpCommon.js
+++ b/node_modules/apollo-angular-link-http-common/fesm5/ng.apolloLink.httpCommon.js
@@ -46,16 +46,13 @@ function (req, httpClient) {
             };
         }
         else {
-            Object.keys(req.body).forEach((/**
-             * @param {?} param
-             * @return {?}
-             */
-            function (param) {
-                if (shouldStringify(param.toLowerCase())) {
-                    ((/** @type {?} */ (req.body)))[param] = JSON.stringify(((/** @type {?} */ (req.body)))[param]);
-                }
-            }));
-            bodyOrParams = { params: req.body };
+          const params = Object.keys(req.body).reduce((obj, param) => {
+            const value = req.body[param];
+            obj[param] = shouldStringify(param) ? JSON.stringify(value) : value;
+            return obj;
+          }, {});
+
+          bodyOrParams = { params: params };
         }
     }
     // create a request
```

**Comment by kamilkisiela** [comment]
Please bump `apollo-angular-link-http-common` to `1.5.1`, it contains a fix
