### ISSUE TITLE
Invalid global scope naming for UMD build

### ISSUE THREAD

**Issue by jsBrian** [apollographql/apollo-angular#1111]
**Intended and actual outcome:**
When I removed the apollo-angular libraries from my angular project bundles and add them as externals instead; I noticed an issue.
```
$ head node_modules/apollo-angular-link-http/bundles/ng.apolloLink.http.umd.js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/common/http'), require('apollo-link'), require('graphql/language/printer'), require('apollo-angular-link-http-common'), require('@angular/core')) :
    typeof define === 'function' && define.amd ? define('apollo-angular-link-http', ['exports', '@angular/common/http', 'apollo-link', 'graphql/language/printer', 'apollo-angular-link-http-common', '@angular/core'], factory) :
    (factory((global['ng.apolloLink.http'] = {}),global.ng.common.http,global.apolloLink.core,global.printer,global.ng.apolloLink.httpCommon,global.ng.core));
```
At the beginning of the last line you can see an assignment `global['ng.apolloLink.http'] = {}`. This should have been `global.ng = global.ng || {}, global.ng.apolloLink = global.ng.apolloLink || {}, global.ng.apolloLink.http = {}` instead.
`global['ng.apolloLink.http']` is not the same as `global.ng.apolloLink.http`.

At the end of the last line you can even see that one of the imports is `global.ng.apolloLink.httpCommon`. When I checked that umd bundle it also assigned it's exports to `global['ng.apolloLink.httpCommon']`

**How to reproduce the issue:**
You can simply install the latest version of the packages and check the umd bundles.

**Versions**
I'm currently getting it on the latest version. I noticed a switch from rollup to ng-packagr, so that might be related (although ng-packagr uses rollup itself).
Currently, I've only checked 3 libraries `apollo-angular`, `apollo-angular-link-http-common` and `apollo-angular-link-http`. Which all faced the same issue.

**Comment by kamilkisiela** [comment]
I think we can change it all to be `pascalCased`, could you open a PR?

**Comment by kamilkisiela** [comment]
#1305 should fix it

**Comment by kamilkisiela** [comment]
[v1.7.0](https://github.com/apollographql/apollo-angular/releases/tag/v1.7.0)
