### ISSUE TITLE
Deprecated docs for local state management

### ISSUE THREAD

**Issue by ceelian** [apollographql/apollo-angular#1119]
**Intended outcome:**
Docs should be applicable for the recent version-

**Actual outcome:**
Docs refer to and explain usage of deprecated apollo-link-state

**How to reproduce the issue:**
See https://www.apollographql.com/docs/angular/basics/local-state.html

**Versions**
Docs are deprecated on the website on March 4th 2019

**Comment by raydirty** [comment]
I created MR #1140 to update the documentation. If you think I missed something, feedback is welcome.

**Comment by raydirty** [comment]
@ceelian my pull request was accepted so I think you can close this issue.
