### ISSUE TITLE
Include API in the documentation

### ISSUE THREAD

**Issue by EricKit** [apollographql/apollo-angular#1129]
Apollo Angular documentation does not have the API references that React does. For example, the options that are passed to a Client. The Apollo Client API documentation is found here: https://www.apollographql.com/docs/react/api/apollo-client.html#apollo-client which is not intuitive. I'm going to a react help section to get the generic Apollo Client API options.

It would be nice to have a set of API options in the Angular section or provide a link to the Apollo Client options in the link above. That will save users starting in Angular time.

Edit: Also, thanks for the awesome project and work!

**Comment by kamilkisiela** [comment]
@EricKit could you create a Pull Request with that?

**Comment by EricKit** [comment]
Will do in a week or so.
