### ISSUE TITLE
Mode 'no-cors' not working?

### ISSUE THREAD

**Issue by EDario333** [apollographql/apollo-angular#1135]
**Intended outcome:**
Get the response from the server (using Django 2.1.7+graphene 2.1.13+graphene-django 2.2.0)

**Actual outcome:**
<code>Error: "Network error: JSON.parse: unexpected end of data at line 1 column1 of the JSON data"</code>.

As you can see in [error1.jpg](https://github.com/EDario333/test1/blob/master/errors/error1.jpg).

I've already tried with mode <code>"no-cors"</code> for the <code>fetchOptions</code> params for the <code>HttpLink</code> class from <code>apollo-link-http</code> (passing headers, with <code>credentials</code>, and more scenarios; [error3.jpg](https://github.com/EDario333/test1/blob/master/errors/error3.jpg) & [error4.jpg](https://github.com/EDario333/test1/blob/master/errors/error4.jpg) are a couple more of tries). Also I tried with an object of type <code>HttpLink</code> <code>from apollo-angular-link-http</code> ant its method <code>create(...)</code>. See [<code>GraphQLModule</code>](https://github.com/EDario333/test1/blob/master/client/myapp/src/app/graphql.module.ts) on file [graphql.module.ts](https://github.com/EDario333/test1/blob/master/client/myapp/src/app/graphql.module.ts) under the [app src directory](https://github.com/EDario333/test1/tree/master/client/myapp/src/app).

I don't think that could be an "issue" on my server side because on it everything's  fine (http://localhost:8000/graphql runs well, and the query/queries, too).

**How to reproduce the issue:**
In [https://github.com/EDario333/test1](https://github.com/EDario333/test1) you will find the full project, and also some bat scripts (I'm working on Win 7, 32 bits). If you do not want to clone the repo, then download the [scripts directory's content](https://github.com/EDario333/test1/tree/master/scripts) and **run**: <code>create-project.bat</code> and later <code>run-project.bat</code>

**Versions**
For the server side I have:

Django 2.1.7
graphene 2.1.13
graphene-django 2.2.0
graphql-core 2.1
graphql-relay 0.4.5
graphql-server-core 1.1.1
grapqh-ws 0.3.0
promise 2.2.1

On the client side I have (among others):

Angular core 7.2.0
Angular platform-browser 7.2.0
apollo-angular 1.5.0
apollo-angular-link-http 1.3.1
apollo-cache-inmemory 1.3.2
apollo-client 2.4.0
apollo-link 1.2.0
apollo-link-http 1.5.14
graphql 0.13.2
graphql-tag 2.10.0
rxjs 6.3.3
zone.js 0.8.26
typescript 3.2.2

**Comment by kamilkisiela** [comment]
I don't think it's something related to the client but if it is and you use `apollo-link-http` then it's the `window.fetch` API so again, nothing related to `apollo-angular` itself. I'm 90% sure it's something either with your server configuration (http://localhost:8000 works because it has the same origin) or a wrong configuration of http link.

Remember that `apollo-angular-link-http` [has different options](https://github.com/apollographql/apollo-angular/tree/master/packages/apollo-angular-link-http#options) that `apollo-link-http` and it's based on Angular's `HttpClient`.

Could you create a small reproduction so I could help you?

**Comment by EDario333** [comment]
Hi @kamilkisiela,

I got the repo on [https://github.com/EDario333/test1](https://github.com/EDario333/test1)

There are also some bat scripts (I'm working on Win 7, 32 bits). If you do not want to clone the repo, then download the [scripts directory's](https://github.com/EDario333/test1/tree/master/scripts) content and run: `create-project.bat` and later `run-project.bat`

The full source code for the [`GraphQLModule`](https://github.com/EDario333/test1/blob/master/client/myapp/src/app/graphql.module.ts) is:

```
import {NgModule} from '@angular/core';
import {ApolloModule, APOLLO_OPTIONS} from 'apollo-angular';
import {HttpLinkModule, HttpLink} from 'apollo-angular-link-http';
import {InMemoryCache} from 'apollo-cache-inmemory';

import { HttpLink as myHttpLink } from 'apollo-link-http';

const uri = 'http://localhost:8000/graphql/'; // <-- add the URL of the GraphQL server here
/*
export function createApollo(httpLink: HttpLink) {
  return {
    link: httpLink.create({uri}),
    cache: new InMemoryCache(),
  };
}
*/

const LINK:myHttpLink = new myHttpLink({
  uri: 'http://localhost:8000/graphql',
  // Additional fetch options like `credentials` or `headers`
  //credentials: 'include',
  headers: {
    "Access-Control-Allow-Origin": "http://localhost:4200",
    "Access-Control-Allow-Methods": "GET",
    'Access-Control-Allow-Headers': 'application/json'
    //"Access-Control-Allow-Credentials" : true
    //"X-CSRFToken": Cookies.get('csrftoken')
  },
  /*fetchOptions: {
    mode: "no-cors",
  },*/
  useGETForQueries: true
});

export function createApollo(httpLink: myHttpLink) {
  return {
    link: LINK,
    cache: new InMemoryCache(),
  };
}

@NgModule({
  exports: [ApolloModule, HttpLinkModule],
  providers: [
    {
      provide: APOLLO_OPTIONS,
      useFactory: createApollo,
      deps: [HttpLink],
      //deps: [myHttpLink],
    },
  ],
})

export class GraphQLModule {}
```

**Comment by OverDriveGain** [comment]
I know it's late. fetchOptions is a child of object createApollo

**Comment by EDario333** [comment]
> I know it's late. fetchOptions is a child of object createApollo

Finally I solved it...

On the client side:

```
import {NgModule} from '@angular/core';
import {ApolloModule, APOLLO_OPTIONS} from 'apollo-angular';
import {HttpLinkModule, HttpLink} from 'apollo-angular-link-http';
import {InMemoryCache} from 'apollo-cache-inmemory';

const uri = 'http://dummy-host:port/graphql'; // <-- add the URL of the GraphQL server here

export function createApollo(httpLink: HttpLink) {
  return {
    link: httpLink.create({
      uri: uri, method: "GET"
    }),
    cache: new InMemoryCache(),
  };
}

@NgModule({
  exports: [ApolloModule, HttpLinkModule],
  providers: [
    {
      provide: APOLLO_OPTIONS,
      useFactory: createApollo,
      deps: [HttpLink],
    },
  ],
})
export class GraphQLModule {}
```
Until here is like many people say... The 'secret' is on the server side:

1. We need `corsheaders`
2. Add `corsheaders` to `INSTALLED_APPS` in `settings.py`. I did it just before `graphene_django` and after than `django.contrib.staticfiles`: 
```
INSTALLED_APPS=[
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',

	'corsheaders',
        'graphene_django',
       # More over here...
]
```

3. Configure `corsheaders` (in my case, for development purposes):
`CORS_ORIGIN_ALLOW_ALL=True`

More details about this: https://github.com/graphql-python/graphene-django/issues/168
