### ISSUE TITLE
Identical Operands

### ISSUE THREAD

**Issue by dargmuesli** [apollographql/apollo-angular#1179]
Is this intended and if yes, why?

https://github.com/apollographql/apollo-angular/blob/7219ceab60086587d12414a3a4034713ceba8ad4/packages/apollo-angular-cache-ngrx/src/normalized-cache.ts#L63

**Comment by kamilkisiela** [comment]
No, it's should be `selected = result[dataId];`

**Comment by dargmuesli** [comment]
Was this fixed or do you need a PR?
