### ISSUE TITLE
Do I need to unsubscribe?

### ISSUE THREAD

**Issue by octogod** [apollographql/apollo-angular#1191]
```
    this.query = this.apollo.watchQuery({query: query})

    this.query.valueChanges.subscribe(res => {
      this.lesson = res.data && res.data.lesson
    })
```

Nooby here. Do I need to unsubscribe from this observable, or is this something that is done automatically?

Every apollo-angular tutorial I see contains code similar to the above code. I'm guessing I don't need to unsubscribe but I just want to make sure.

Thank you.

**Comment by intellix** [comment]
This isn't done automatically. I'd recommend this as it makes it easier/more convenient to unsub: https://github.com/NetanelBasal/ngx-take-until-destroy

Typically I like to let the view handle the subscription:

```ts
lesson$ = this.apollo.watchQuery({query: query}).pipe(
  map(({ data }) => data.lesson),
);
```

```html
*ngIf="(lesson$ | async) as lesson"
```

Also, you shouldn't use the repository issue system for questions :) the above is probably answered a million times on stackoverflow

**Comment by octogod** [comment]
Awesome, thank you!

Keep up the great work guys. I'll ask questions on stackoverflow from now on, haha.

**Comment by vladimirdrayling** [comment]
Hi @intellix! And what about mutations? What is the best approach to unsub. Is there like ngrx/effects lib?

**Comment by intellix** [comment]
I believe mutations finish after a single emit so you'll be fine
