### ISSUE TITLE
ng add apollo-angular introduces a bug

### ISSUE THREAD

**Issue by rolfed** [apollographql/apollo-angular#1200]
**Intended outcome:**

For ng add apollo-angular to not introduce bug

**Actual outcome:**

ng add apollo-angular introduces a breaking bug. 
```bash
ERROR in node_modules/@wry/context/lib/context.d.ts(6,84): error TS2694: Namespace 'NodeJS' has no exported member 'Timeout'.
```
<img width="1440" alt="Screen Shot 2019-05-22 at 9 50 01 PM" src="https://user-images.githubusercontent.com/16821986/58226574-1ba5a280-7cdc-11e9-8382-31ac914eee0b.png">

**How to reproduce the issue:**

ng new app-test && ng add apollo-angular && ng s
**Versions**

<img width="1440" alt="Screen Shot 2019-05-22 at 9 51 25 PM" src="https://user-images.githubusercontent.com/16821986/58226588-2d874580-7cdc-11e9-853d-9e8d0b01870b.png">

**Comment by kamilkisiela** [comment]
It's not really `apollo-angular` but as far as I see, `@wry/context` requires `@types/node` BUT it doesn't really use it except in tests. I will try to create a Pull Request for that.

**Comment by kamilkisiela** [comment]
Continuing at https://github.com/benjamn/wryware/issues/4 and https://github.com/benjamn/wryware/pull/5
