### ISSUE TITLE
'NodeJS' has no exported member 'Timeout'.

### ISSUE THREAD

**Issue by RmilaWeb** [apollographql/apollo-angular#1202]
Hello, When i added Apollo to my project this error was showed.

 

> ERROR in node_modules/@wry/context/lib/context.d.ts(6,84): error TS2694: Namespace 'NodeJS' has no exported member 'Timeout'.
> 
> i ｢wdm｣: Failed to compile.
> 

 
**Versions**
2.6

**Comment by RmilaWeb** [comment]
![image](https://user-images.githubusercontent.com/12487298/58251868-13de1080-7d65-11e9-9206-1fd7bd696ee1.png)
![image](https://user-images.githubusercontent.com/12487298/58251883-20626900-7d65-11e9-9f09-9bf845b28622.png)

**Comment by judithprays** [comment]
same issue here - it is with angular + apollo.

**Comment by RmilaWeb** [comment]
> same issue here - it is with angular + apollo.

Angular 7 ?

**Comment by judithprays** [comment]
Yes

**Comment by bjuffe** [comment]
Also experiencing the same issue. Fresh angular project and `ng add apollo-angular`.

(A work around for now is just removing `node_modules/@wry/context/lib/context.d.ts`)

**Comment by heuperman** [comment]
There's an open pull request on @wry here for those wanting to be notified when this is resolved:
https://github.com/benjamn/wryware/pull/5

**Comment by Andre153** [comment]
upgrading @types/node to the latest version did the trick

**Comment by kamilkisiela** [comment]
That's related to `apollo-cache-inmemory` and not `apollo-angular` itself. I fixed it, but it's not merged and released yet, here's the ongoing pull request https://github.com/benjamn/wryware/pull/5 and the related issue https://github.com/benjamn/wryware/issues/4. 

I'm going to close it so please follow https://github.com/benjamn/wryware/issues/4. I will notify all you guys once it's released :))

**Comment by sreenivasarajiv** [comment]
> upgrading @types/node to the latest version did the trick

Working fine 👍

**Comment by xuxusheng** [comment]
> upgrading @types/node to the latest version did the trick

Working fine

**Comment by kamilkisiela** [comment]
Yeah but it's just a workaround, not a fix.

**Comment by RatanKumar678** [comment]
Same here. It happened to be an issue with the version of the "@types/node"-dependency that was defined in my devDependencies. Upgrading it to the latest version (12.0.2) fixed it for me.

**Comment by Amit562877** [comment]
> upgrading @types/node to the latest version did the trick

Work for me too thanks dude
