### ISSUE TITLE
Update Apollo to work with Angular 8

### ISSUE THREAD

**Issue by Dunos** [apollographql/apollo-angular#1208]
**Intended outcome:**
With the current version of Apollo Angular we cannot upgrade to Angular v8 because of the dependencies:

Package "apollo-angular" has an incompatible peer dependency to "zone.js" (requires "~0.8.20", would install "0.9.1").

**How to reproduce the issue:**
Run "ng update @angular/cli @angular/core" to see the error

**Versions**
Apollo Angular 1.5.0

**Comment by stunti** [comment]
Seems to be a work in progress
https://github.com/apollographql/apollo-angular/pull/1206

**Comment by kamilkisiela** [comment]
@stunti @Dunos @CDDelta @mpbalmeida @rburgt @Dunos @rmyz @loremaps @alexsanqp 

Update to `v1.6.0` 🚀

**Comment by artem-galas** [comment]
Just checked, and seems you are not update `@angular/http` into [apollo-angular-link-http](https://github.com/apollographql/apollo-angular/blob/master/packages/apollo-angular-link-http/package.json#L42)

That's why I got an error

```
npm WARN apollo-angular-link-http@1.6.0 requires a peer of @angular/core@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-angular-link-http@1.6.0 requires a peer of @angular/common@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-angular-link-http-common@1.6.0 requires a peer of @angular/core@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-angular-link-http-common@1.6.0 requires a peer of @angular/common@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by kamilkisiela** [comment]
@artem-galas oopsie, I forgot to publish other packages :)

https://github.com/apollographql/apollo-angular/pull/1214
