### ISSUE TITLE
Please verify and consider a major version change for the angular 8 updates and schematics

### ISSUE THREAD

**Issue by KillerCodeMonkey** [apollographql/apollo-angular#1222]
1.6.0 breaks angular 7.x. cli production builds.

I get, when trying to start my angular 7 app with angular-apollo 1.6.0

```
angular production build must call super constructor before using |this| in anonymous class constructor
```

works with angular-apollo 1.5.0

Maybe you can check that. If this is a valid issue then the schematics and angular upgrade has breaking changes and it should be a major version change.

**Comment by cedvdb** [comment]
also `Package "apollo-angular" has an incompatible peer dependency to "zone.js" (requires "~0.8.20", would install "0.9.1").
Incompatible peer dependencies found. See above`

**Comment by maxim1006** [comment]
Temporary solution for this might be set

"buildOptimizer": false

for now, but still waiting for fix

**Comment by KillerCodeMonkey** [comment]
yeah but this is not really a workaround, because you are losing the build optimization, without that it is not really a "production" build. Especially for bigger apps the result is not suitable ;)

**Comment by maxim1006** [comment]
yeah, or use 1.5.0 as you mentioned before.

**Comment by kamilkisiela** [comment]
Closing in favor of #1226
