### ISSUE TITLE
ERROR in ENOENT: no such file or directory, lstat '/node_modules/graphql/index'

### ISSUE THREAD

**Issue by richardsengers** [apollographql/apollo-angular#1273]
**Intended outcome:**
Serve angular app with Ivy enabled

**Actual outcome:**
When ivy enabled with the latest .next version of Angular, an error is thrown
```
ERROR in ENOENT: no such file or directory, lstat '/node_modules/graphql/index'

```
**How to reproduce the issue:**
I'm not quite sure if this is related to apollo, but I've tracked the issue and it only occurse when I import something from Apollo.
for example 

```
import { Apollo } from 'apollo-angular';
```

or 
```
import { QueryRef } from 'apollo-angular';
```

**Versions**
From my package.json

```
     "apollo-angular": "^1.6.0",
    "apollo-angular-link-http": "^1.8.0",
    "apollo-cache-inmemory": "^1.6.2",
    "apollo-client": "^2.6.3",
    "apollo-link": "^1.2.12",
    "apollo-link-context": "^1.0.18",
    "graphql": "^14.4.2",
    "graphql-tag": "^2.10.1",
```

To get the latest versions from Angular

```
ng update @angular/cli @angular/core --next
```

To get Iy enabled add this to your tsconfig.sjon

```
"angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableIvy": true
  }
```

**Comment by chakrachi** [comment]
in the mean time, I managed to bypass this error by deleting the .js extension of the graphql npm module

**Comment by kamilkisiela** [comment]
I tried with `9.0.0-next.7` and `1.7.0` of apollo-angular + latest `graphql` and it seems to work fine. Could you guys create a reproduction?
