### ISSUE TITLE
VariableTypeMismatch Error

### ISSUE THREAD

**Issue by samermerhi** [apollographql/apollo-angular#1274]
Hello, 

We are trying to execute a simple apollo query: 
```ts
 this.apollo
    .watchQuery({ 
      query: gql`
        query getQuery($path: String) {
          guillotine {
           getChildren(key: $path) {
               _id
           }
          }
        }
      `,
      variables: {
  		path: "/phtest/flag/ANG"
	  },
    })
    .valueChanges
    .subscribe(result => {
      this.guillotine = result.data && result.data['guillotine'];
      this.loading = result.loading;
      this.error = result.errors;
    });
```

every thing works fine when we remove the $path variable. 
we appreciate your help!

**Comment by kamilkisiela** [comment]
I bet you define `$path` as `String` but it might be something different than what `key` in `getChildren` accepts. It's not related to Apollo Angular or even Apollo itself, it's GraphQL.

Could you show the schema?

**Comment by kamilkisiela** [comment]
Closing because it seems not related to Apollo
