### ISSUE TITLE
All links to other doc pages are broken in docs

### ISSUE THREAD

**Issue by gloomylumi** [apollographql/apollo-angular#1331]
**Intended outcome:**
Clicking references to other doc pages within documentation successfully navigates to the doc page.
**Actual outcome:**
URL path includes extra '/docs/angular' which results in displaying a blank page. 404 page is only displayed after refreshing page. Hitting back button to return to previous doc page continues to show 404 page until you hit refresh again.
**How to reproduce the issue:**
For example, clicking the 'mutations' link in the first sentence on https://www.apollographql.com/docs/angular/features/optimistic-ui/ will attempt to navigate to https://www.apollographql.com/docs/angular/docs/angular/basics/mutations/#optimistic-ui when the correct url is https://www.apollographql.com/docs/angular/basics/mutations/#optimistic-ui

**Versions**
n/a

**Comment by kamilkisiela** [comment]
Thanks, I fixed it
