### ISSUE TITLE
Inject object instance for each return type.

### ISSUE THREAD

**Issue by clintsinger** [apollographql/apollo-angular#1411]
I have a query that returns a union.   In my case I have two classes, Organization and User, which extend Account.    When I do a query I have to return the base class in my mutation and query objects when I would prefer to have returned the Organization and User objects directly.  This would then allow me to be able to use the `instanceof` operator.

Is it possible to inject what object instance I would like to use for each of the returned values? 

If not, it would be great if there was some kind of factory function that let you return whatever object instance you want based on the incoming data.   For example, I could read the `__typename` and then return the corresponding instance.

Alternatively, is there another preferred way of handling this?

**Comment by kamilkisiela** [comment]
Could you give an example in code because I'm not sure how Apollo itself should do something about it. I don't understand how `instanceof` has something to do with GraphQL.
