### ISSUE TITLE
Recommended way to trigger query refetch after some non-mutation operation?

### ISSUE THREAD

**Issue by andy23512** [apollographql/apollo-angular#1463]
I need to fetch new set of data after some non-mutation actions (such as after uploading some files). But it seems the `refetchQuery` must be triggered by a mutation.
I've thought of some ways to work around:

1. ignite a dummy mutation (which does nothing) to trigger the refetch
2. recreate a new `watchQuery` stream
(Maybe use subscription api is the best way, but it's difficult for me to handle it for now.)

Any better ways or advice?

**Comment by kamilkisiela** [comment]
Subscription is more for events-like things so I say you use Queries. If you want to watch the store / cache then use `watchQuery`, if you want to fetch data once and it won't be mutated, then doing `query` is also fine. 

About refetching. If you decide to use `query` then putting a Subject next to Query Observable as a trigger will do the thing perfectly.
If you want to watch the store and use `watchQuery`, check the `refetch` method of `QueryRef`. The `QueryRef` it's an object returned by `watchQuery`, next to `valueChanges`.

Here's an example of `QueryRef.refetch`: https://stackblitz.com/edit/simple-apollo-angular-example-qstaky

Let me know if you need any help :)

**Comment by andy23512** [comment]
It looks like `QueryRef.refetch` is what I need. Thanks for the response!
