### ISSUE TITLE
Angular v9.0 Support

### ISSUE THREAD

**Issue by dabears318** [apollographql/apollo-angular#1464]
Angular 9 was released earlier this week, with the much anticipated Ivy compiler and many other improvements.

When will apollo-angular support 9.0+?  Will this coincide with a full 3.0 release of client?

Thanks.

**Comment by qirex** [comment]
I updated a project that is using apollo to Angular 9 today.
Did not notice any issues other than npm warning about peer dependency versions.

**Comment by dabears318** [comment]
thanks qirex - I did notice there wasn't any apparent issues but this is causing production builds to not pass tests due to (apparent) peer dependency issues, so we are waiting.  since there aren't seemingly any apparent issues then hopefully it will be a quick update to package.json

**Comment by maktarsis** [comment]
@qirex 

My project is running on Angular 9 with Ivy renderer.
Yarn warns me about these incorrect peerDependencies
https://prnt.sc/r5wvdq

**Comment by jkossis** [comment]
Any movement on this?

**Comment by damingerdai** [comment]
Please officially support angular9 as soon as possible

**Comment by flobacher** [comment]
there is a [pr](https://github.com/apollographql/apollo-angular/pull/1460) to upgrade to 9.1 from the renovate bot that is failing because typescript is too old
there is a [pr](https://github.com/apollographql/apollo-angular/pull/1073) to update typescript to 3.8 but this is not supported in the old angular 8
if the changes of both those prs combined, at least the build would go through I guess.
@kamilkisiela should I prepare this in a new pr, or are there other reasons as well, for not progressing on this issue? thank you!

**Comment by kamilkisiela** [comment]
@flobacher @damingerdai @jkossis @maktarsis @dabears318 @qirex @psoares-resilient @A1leen @philippschladitz @MicMicMon @RikdeVos @niklissad @fetis @ivib @ximiltech @ivibe @rob3c @Pokerkoffer @wSedlacek @slavicronenko @cgatian @HirokiMinagawa

Could you try out `next` version and give me the feedback? https://github.com/apollographql/apollo-angular/pull/1484#issue-394657421

I have no time to test it myself so let's ship it together :)

**Comment by kamilkisiela** [comment]
Please give your feedback on the pull request

**Comment by maktarsis** [comment]
@kamilkisiela warnings have gone on **1.8.0-alpha.0**

**Comment by flobacher** [comment]
@kamilkisiela PR looks good, had no issues building and running an angular 9 app with this version in production mode!

**Comment by kamilkisiela** [comment]
@flobacher @damingerdai @jkossis @maktarsis @dabears318 @qirex @psoares-resilient @A1leen @philippschladitz @MicMicMon @RikdeVos @niklissad @fetis @ivib @ximiltech @ivibe @rob3c @Pokerkoffer @wSedlacek @slavicronenko @cgatian @HirokiMinagawa

Done, use `latest`
