### ISSUE TITLE
Does not build with Angular 8 and Ivy

### ISSUE THREAD

**Issue by JonathanWylie** [apollographql/apollo-angular#1466]
**Intended outcome:**
ivy-ngcc not to fail compiling

**Actual outcome:**
Compiling apollo-angular : fesm2015 as esm2015
Compiling apollo-angular : fesm5 as esm5
Compiling apollo-angular : esm2015 as esm2015
Compiling apollo-angular : esm5 as esm5
Compiling apollo-angular : main as umd
Compiling apollo-angular/testing : fesm2015 as esm2015
No suitable injection token for parameter 'apollo' of class 'ApolloTestingModuleCore'.
no type or decorator

**How to reproduce the issue:**
Try compiling with ivy

**Versions**
"@angular/cdk": "~8.2.3",
"@angular/common": "^8.2.14",
"@angular/compiler": "^8.2.14",
"@angular/core": "^8.2.14",
"@angular/router": "^8.2.14",
"typescript": "3.5.3",
"apollo-angular": "^1.8.0",
"apollo-angular-link-http": "~1.9.0",
"apollo-cache-inmemory": "~1.6.5",
"apollo-client": "~2.6.8",
"apollo-link": "~1.2.13",
"graphql": "^14.0.2"

Possibly related to this other issue?
https://github.com/apollographql/apollo-angular/issues/1376

I tried with version 2.0.0 and got a similar error:

"apollo-angular": "2.0.0-beta.2",

Compiling apollo-angular : fesm2015 as esm2015
No suitable injection token for parameter 'alreadyThere' of class 'ApolloModule'.
no type or decorator

**Comment by Yohandah** [comment]
Everything is working fine for me with Angular 9, can you consider updating your project to Angular 9 and test or not ?

**Comment by JonathanWylie** [comment]
Yes, we have tried upgrading to angular 9 and it is OK, so it must only be a problem when using angular 8 and ivy.
