### ISSUE TITLE
Tests examples

### ISSUE THREAD

**Issue by sebastiannm** [apollographql/apollo-angular#183]
Hi,

I couldn't find any examples of how to do the unit testing with angular2-apollo. I always ended up going to the server, or getting errors like "this.apollo.watchQuery is not a function".

Some examples would be nice, at least to use mock data.

**Comment by kamilkisiela** [comment]
I'll try to work on something soon

**Comment by intellix** [comment]
I've just been playing with this. You can mock the ApolloClient to return a response that you like:

```ts
// Copy a GQL response (that includes __typename etc)
const gqlResponse = '...';

function provideClient() {
  return new ApolloClient({
    networkInterface: {
      query: function() {
        return new Promise(resolve => resolve(gqlResponse));
      }
    }
  });
}

TestBed.configureTestingModule({
  declarations: [ MyComponent ],
  imports: [
    ApolloModule.withClient(provideClient),
  ]
})
.compileComponents();
```

Maybe it's worth importing an entire mocked Network Interface that includes data for your whole application so you're not repeating yourself over and over. If you can re-use your schema and use graphql-tools, then even better

**Comment by kamilkisiela** [comment]
There is some work going on about test utils (apollostack/apollo-test-utils#1)
