### ISSUE TITLE
@types/graphql are 0.8.x and graphql is 0.9.x

### ISSUE THREAD

**Issue by intellix** [apollographql/apollo-angular#270]
Just leaving a note/call-to-arms that the types are out of date now and will need updating at DefinitelyTyped by somebody :)

Should be much easier to update this time around because there isn't a monolith type file anymore. I'm not sure how large the changes are though.

Changes: https://github.com/graphql/graphql-js/compare/v0.8.2...v0.9.1
Types: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/graphql

**Comment by eitanfr** [comment]
was updated to 0.9
