### ISSUE TITLE
Make returned data extensible

### ISSUE THREAD

**Issue by pixelsailor** [apollographql/apollo-angular#272]
I'm running into a situation where I need another plugin (ngx-datatable) to be able to modify the data being returned from the server. Right now it's unable to do so because the data is not extensible.

```javascript
ngOnInit(): void {
    this._apollo.watchQuery({
        query: getAllTheThings
    }).subscribe(({data, loading}) => {
        console.log(Object.isExtensible(data['theThings')); // false
    });
}
````
It would be super helpful if this was mutable out of the box. Failing that, does anyone have a suggestion as to how to maintain the observable state of the data but allow the other plugin to modify it?

**Comment by manuelfink** [comment]
Why don't you use lodash cloneDeep for this? Not sure if this is the expected way to go though?

**Comment by manuelfink** [comment]
```
Import * as _ from 'lodash';
...
Let copyOfData = _.cloneDeep(data);
```

**Comment by stubailo** [comment]
Yeah it can't be mutable because then we have to clone every time we return data which quickly becomes inefficient. If you want it to be mutable cloning it yourself is the right way to do it.

**Comment by pixelsailor** [comment]
Thanks for the info. I had considered using lodash previously but was concerned about the performance overhead and whether it would maintain its observable state. Appears to be working though. 👍

**Comment by stubailo** [comment]
Yep we wouldn't want to build that performance overhead into the core itself.

**Comment by kamilkisiela** [comment]
Closing this. If you think this still need to be opened, @mention me :)
