### ISSUE TITLE
Basic query issue 'data'

### ISSUE THREAD

**Issue by nilpaco** [apollographql/apollo-angular#287]
I'm really new to Apollo and GraphQL in general. Right now I'm trying to follow the example in the Apollo documentation for the integration with Angular.

The problem comes when I get the data retrieved by the server, then I try to get the object called 'allPets', like this:
```
this.apollo.watchQuery({
    query: Query
}).subscribe(({data}) => {
    this.pets = data.allPets;
});
```

But I get this error message:
`Property 'allPets' does not exist on type '{}'.`

FYI: I solved the issue with this workaround:
`this.pets = data['allPets'];`

and this one:
```
this.pets = data;
*ngFor="let pet of pets | select: 'allPets'"
```

**Comment by xmurcia** [comment]
Hey nilpaco!

I was dealing with a similar issue and I found in Apollo's docs the answer to our problem, check out the link below!

http://dev.apollodata.com/angular2/typescript.html

**Comment by nilpaco** [comment]
It worked!

Thanks!

**Comment by bboynton97** [comment]
Thank you for the solution! It's really weird to me that even now, two years later, their documentation has code that doesn't work
