### ISSUE TITLE
Update / set dynamic uri

### ISSUE THREAD

**Issue by lukemadera** [apollographql/apollo-angular#296]
I've got things working with a hardcoded url endpoint, but I can't figure out how to set the uri after bootstrapping. I tried 

```
const networkInterface = createNetworkInterface({
        // TODO - add method to set url / setup network interface (or just take url paramter in this function)
        uri: '{unknown at this point}',
    });
networkInterface.use([{
        applyMiddleware(req: any, next: any) {
            req.uri = '{myUrlHere}';
            next();
        }
    }]);
```

but that does not seem to work.

How do I set / change the uri?

My use case:
I have a helper repository that wraps apollo for graphql, and the main repo has the url. The main repo sets the urls, and at that point, I need to set the graphql url (I don't know it ahead of time, as it is set by a function call with which url to use).

**Comment by lukemadera** [comment]
@kamilkisiela How would I set the uri dynamically?

**Comment by kamilkisiela** [comment]
@lukemadera You can create your own `networkInterface`. The `createNetworkInterface` function is just to provide the default network interface class (`HTTPFetchNetworkInterface`) in a short, simply way. You don't have to stick with it.

Take a look at [this code](https://github.com/apollographql/apollo-client/blob/master/src/transport/networkInterface.ts).

```ts
class MyCustomNetworkInterface implements HTTPNetworkInterface {
  // ...
}

**Comment by lukemadera** [comment]
Thanks for the reply @kamilkisiela Things seem quite nested and complicated to get it working as I'd want - even if I did re-write a new network interface, the module instantiation looks like:
```
export function provideClients() {
    return {
        default: apolloClient,
        // extra: extraClient,
    };
}

@NgModule({
    imports: [CommonModule, ApolloModule.forRoot(provideClients), PLHttpModule],
```

It seems to need to be set ahead of time. While the
```networkInterface.use([{
        applyMiddleware(req, next) {
```
can be a good way to set a header to be sent on ALL requests, there's not an easy way to customize PER request. And that's what we need. Just like a standard http request - you pass in the url and the options. The way apollo graphql seems set up, it's for one (or a few, with the multiple clients option) urls.

What would be ideal is at this level, when the query is made, to be able to set the url:
```
const gqlQuery = gql`${query}`;
        return this.apollo.watchQuery({
            query: gqlQuery,
        });
```
In addition to the query, we need to be able to set the url. A per request / per query set of url, options, etc.
Is that something that could be added as a future feature?

**Comment by Dunos** [comment]
Any update on this issue? I am interested in that kind of functionality too.

**Comment by viktorvillalobos** [comment]
Me too, i need to change the uri dynamically.

**Comment by Dunos** [comment]
For what I've tested with a custom service extending from Apollo/ApolloBase, if they remove the private property for the "client" variable, this could be achived (not saying is the best solution, but it works at least). I tried it editing myself the Apollo.d.ts file and got it working...

**Comment by Dunos** [comment]
@kamilkisiela do you think they will allow a petition to change the Apollo.d.ts definition?

Currently is like this:

```
export declare class ApolloBase {
    private client;
```

But if they change it to this, we could access the client and change the uri...
```
export declare class ApolloBase {
    public client;
```

**Comment by carlospalacin** [comment]
Hi! I leave my solution, I have created apollo-client-amanger.ts:
```
import { ClientMap } from 'apollo-angular/build/src/types';
import { ApolloClient, createNetworkInterface } from 'apollo-client';
import { Apollo } from 'apollo-angular';

export class ApolloClientManager {
    private client: ApolloClient;

    static getClient(uri: string = undefined): ApolloClient {
        const cm = new ApolloClientManager(uri);
        return cm.client;
    }

    static getClientMap(uri: string = undefined): ClientMap {
        return { 'default' : ApolloClientManager.getClient(uri) };
    }

    static apollo(uri: string = undefined): Apollo {
        return new Apollo(ApolloClientManager.getClientMap(uri));
    }

    constructor(
        uri: string = undefined
    ) {
        const networkInterface = createNetworkInterface({
            uri: uri ? uri : '/graphql'
        });

// middleware form JWT
        networkInterface.use([{
            applyMiddleware(req, next) {
                if (!req.options.headers) {
                    req.options.headers = {};  // Create the header object if needed.
                }
                // get the authentication token from local storage if it exists
                req.options.headers.authorization = localStorage.getItem('token') || null;
                next();
            }
        }]);

        this.client = new ApolloClient({
            networkInterface
        });
    }
}
```
and apollo-service.ts:
```
import { Injectable } from '@angular/core';
import { Apollo } from 'apollo-angular';
import { ApolloClientManager } from './apollo-client-manager';

@Injectable()
export class ApolloService {

    _apollo: Apollo;

    constructor() { }

    apollo(uri) {
        if (uri) {
            this._apollo = ApolloClientManager.apollo(uri);
        } else if (! this._apollo) {
            this._apollo = ApolloClientManager.apollo();
        }
        return this._apollo;
    }
}
```
and graphql.module.ts:

```
import { NgModule, Inject } from '@angular/core';
import { ApolloClient, createNetworkInterface } from 'apollo-client';
import { ApolloModule } from 'apollo-angular';
import { ApolloClientManager } from './apollo-client-manager';

@NgModule({
    imports: [
        ApolloModule.forRoot(ApolloClientManager.getClient)
    ],
    exports: [ApolloModule],
    providers: [
        ApolloService
    ]
})
export class GraphQLModule { }
```
you can create your apollo instance with service:
```
@Component({
    selector: 'ps-selector-list',
    templateUrl: './selector-list.component.html'
})
export class SelectorListComponent {

    constructor(
        private apolloService: ApolloService
    ) { }

    ngOnInit() {
        // this with custom uri
        this.apolloService
            .apollo('http://my-uri.com/graphql').watchQuery({
                query: gql`
                 {
                    actions {
                      id
                      name
                    }
                    packages {
                      id
                      name
                      root
                      sort
                    }
                 }
                `
            }).subscribe(({data}) => {
                console.log(data);
            });

        // and this with default uri
        this.apolloService
            .apollo().watchQuery({
                query: gql`
                 {
                    actions {
                      id
                      name
                    }
                    packages {
                      id
                      name
                      root
                      sort
                    }
                 }
                `
            }).subscribe(({data}) => {
                console.log(data);
            });
    }
}
```

don't forget import graphql.module.ts in your module
This works fine for me

**Comment by tariknz** [comment]
@carlospalacin this looks like it creates a new instance of the client on every request.

I think I found a more efficient way of doing this when I was looking at this ticket: https://github.com/apollographql/apollo-client/issues/1267

NetworkInterface is referenced so you can just extend it and update it in your application.

Basically you create a new class that extends HTTPFetchNetworkInterface:
```
import { HTTPFetchNetworkInterface } from 'apollo-client';

export class GraphQLNetworkInterface extends HTTPFetchNetworkInterface {
    public setUri(uri: string) {
        this._uri = uri;
    }
}
```

Then create your client as instructed, but using the new network interface. Make sure you export the networkInterface when creating it:
```
import { ApolloClient } from 'apollo-client';
import { GraphQLNetworkInterface } from './graphql-network-interface';

export const networkInterface = new GraphQLNetworkInterface('[DEFAULT URL]');

const client = new ApolloClient({ networkInterface });

export function provideClient(): ApolloClient {
  return client;
}
```

Lastly, provide the networkInterface instance you created above in your module
```
{ provide: GraphQLNetworkInterface, useValue: networkInterface },
```

Then basically you can inject GraphQLNetworkInterface anywhere in your application and call the setUri  to update the URI. It will be the same instance of the network interface you used to instantiate the client.

**Comment by carlospalacin** [comment]
Hi @tariknz your solution looks great!
my code don't instance apollo client each request, in apollo-service.ts check if is instance the client, and by to be a service singletone, if is created, return always the same instance, but your code looks better that mine

**Comment by monkeychops** [comment]
@tariknz this is exactly what I needed. Nice one!

**Comment by somecallmemike** [comment]
I am trying to utilize @tariknz method, however I keep getting the error:

`
ERROR in Error encountered resolving symbol values statically. Calling function 'GraphQLNetworkInterface', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol networkInterface in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts
`

Code looks like this:
```
export const networkInterface = new GraphQLNetworkInterface('http://127.0.0.1:3000/graphql');

networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {}
    }
    let token = localStorage.getItem('authtoken')
    // console.log("I am graphql authorization middleware", token, typeof token)
    req.options.headers.authorization = token
    next()
  }
}])

const client = new ApolloClient({
  networkInterface
})

export function provideClient(): ApolloClient {
  return client
}
```

The module is providing it as such:
```
@NgModule({
....
  providers: [
    { provide: GraphQLNetworkInterface, useValue: networkInterface },
  ],
....
})
```
What am I doing wrong here?

**Comment by kamilkisiela** [comment]
It will be possible with Angular's `HttpInterceptors` and new apollo-angular #377 (thanks to links - especially `apollo-angular-http-link`)

**Comment by kamilkisiela** [comment]
with `apollo-angular@1.0.0` and `apollo-angular-link-http` you can specify `uri` in the context (as [here](https://github.com/apollographql/apollo-angular/tree/master/packages/apollo-angular-link-http#context)). It's not documented yet but will be soon.

**Comment by kolypto** [comment]
I was able to re-create my Apollo client like this:

```javascript
    this.apollo.removeClient();
    this.apollo.create({
      cache: new InMemoryCache(),
      link: this.httpLink.create({
        uri: this.backendUrl,
      })
    });
```
