### ISSUE TITLE
ApolloQueryObservable compatibility with Rx.Observable

### ISSUE THREAD

**Issue by sarora2073** [apollographql/apollo-angular#301]
Hi,

I'm using the latest version 0.13.0, and am seeing issues when using the .map operator on an  ApolloQueryObservable, as doing so appears to return an Rx.Observable instead (which I guess is to be expected, however...), the extension methods of  ApolloQueryObservable (such as refetch) no longer *appear* to be available according to typescript. Even though the extension methods actually appear to work, this is a nuisance since I get flooded with compilation errors since I use ApolloQueryObservable extension operations like refetch frequently to update data after performing mutations. 

Here's some sample code to illustrate:

import { Apollo,ApolloQueryObservable  } from 'apollo-angular';
...
items: any;
**itemsObs: Observable\<any\>;**
// note: i've tried using the type ApolloQueryObservable<{}> here, but the compiler complains unless I use a regular Observable type when rxjs's  .map operator is appended as shown below

  getItems() {
    **this.itemsObs** = this.apollo.watchQuery({ 
      query: _items })
     **.map**(({data}:any) => data.items); // within returned data object, get the array of items     

    this.itemsObs.subscribe(
        (res) => {
          this.items = res;
      }, error => this.handleError(error));
  }

and after running a mutation, i run this:

this.itemsObs.refetch() // <-- this is the line that what works fine if itemsObs is an ApolloQueryObservable, but gives typescript warnings if itemsObs is an Observable

The specific compilation warnings are like this:
    TS2339: Property 'refetch' does not exist on type 'Observable<any>'.

I've tried re-writing the above code a few different ways, but the constraints I keep bumping into are:

1.  .map operator is useful to me in various scenarios, but that is what causes the associated side effects casting from ApolloQueryObservable to Rx.Observable. I'd prefer the solution to NOT be "don't use .map" since it has general utility.
2. I need to be able to use the refetch extension method on ApolloQueryObservable (i.e. need a lightweight way of forcing a data refresh after mutations). 

Any alternative options (e.g. can i cast the Observable back to ApolloQueryObservable to do extension operations? am unable to determine how) and/or long-term fix ideas appreciated.

Thank you,

S. Arora

**Comment by kylecordes** [comment]
I'm not convinced the extra methods on ApolloQueryObservable are a good idea at all. I suspect things would be much better overall if:

* We got back just a plain old Observable.
* Some other means was provided to perform Apollo specific feature.

**Comment by sarora2073** [comment]
Thanks. Is there a way to do a refetch on a plain Observable? I went down that path for a bit but didn't see find a similar method.

**Comment by kylecordes** [comment]
@sarora2073 No, there is not - and there should be. Observable is a very generic interface. Things like requerying are implemented idiomatically with various Observable operators. (Relevant here - .retry, .switchMap, some others). I don't have an example handy, unfortunately.

**Comment by sarora2073** [comment]
I'll look into those. Thanks again!

**Comment by sarora2073** [comment]
update: was able to get past the conundrum. i was unnecessarily relying on the refetch operation to refresh my UI after each mutation. Now after each mutation I simply re-run the getItems() method in the subscribe operation, which in turn fetches the latest data. Since I bind the observable (called itemsObs) directly to my template and pipe to 'async', the UI updates immediately after each mutation, and shows the latest list of items. I'm also relying on fetchPolicy set to 'network-only to bypass graphql caching. 

Here's what the getItems method looks like now. Note, i'm no longer subscribing in this method..the async pipe in the template handles that it seems.

  getItems() {
    this.itemsObs = this.apollo.watchQuery({ 
      query: _items,
      **fetchPolicy: 'network-only'** 
    })
     .map(({data}:any) => data.items); // within data object, get the array       
  }

**Comment by kylecordes** [comment]
@sarora2073 It seems to me that, if `watchQuery` does it job correctly, you would not need to re-run `getItems()`, rather you would receive the data automatically.

**Comment by sarora2073** [comment]
Are you saying it should push data from the server-side? If so, that would make me think watchQuery is perhaps not working right, or else perhaps I just need to know more about what links mutations and  associated server push events i.e. is the disconnect explainable somehow?

Please note: Til now I was thinking of all this mainly from a client-side...and how to get angular to know that there's been a change to previously subscribed data after a mutation event within the same component.

**Comment by kylecordes** [comment]
As I understand the rough idea is:

* In theory the data could be all observable, end to end (server/client/etc). With the watchQuery API. But:
* So far, the docs/code at least discuss the notion of watchQuery picking up changes in the client-side cache.
* I don't see any docs/etc which indicate end-to-end observability is up and running yet; the docs about subscriptions are about an old-fashioned explicit subscription/pub/sub API:

http://dev.apollodata.com/tools/graphql-subscriptions/index.html

Maybe someone from the Apollo project will see this and comment with official information about the status and plans around this.
