### ISSUE TITLE
Errors while handing promises

### ISSUE THREAD

**Issue by Purus** [apollographql/apollo-angular#302]
I have the below function is a service provider. I want to keep the back-end and UI part separate and so I use providers to fetch all data.

    getUserById(id: number) {

    return new Promise((resolve, reject) => {
      this.apollo.query({
        query: UserByIdQueryText,
        variables: {
          id: id
        }
      }).subscribe((res: any) => {

        let ans = res.data.user;
        if (ans) {
          console.log(ans);
          resolve(ans);
        } else {
          reject('could not get user');
        }
      }, (err) => {
        console.error(err);
      });
    });
  }

In the actual page, I have the below code to fetch the data.

    export class UserProfilePage {
      public user: User;
      public id: number;
    
      constructor(private userService: UserService, private navController: NavController, private params: NavParams) {
        this.user = null;
        this.id = params.get("id");
        
        this.userService.getUserById(this.id)
          .then((user: User) => {
            this.user = user;
            console.log(user);
          });
      }
    
    }

The problem is that the remote call completes late but the view tries to show the data. I get the below error. I can see the console log after the error is thrown.

    Error: Uncaught (in promise): TypeError: Cannot read property 'title' of null
    TypeError: Cannot read property 'title' of null
        at Object.eval [as updateRenderer] (ng:///AppModule/UserProfilePage.ngfactory.js:273:28)
        at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:8100/build/main.js:12978:21)
        at checkAndUpdateView (http://localhost:8100/build/main.js:12357:14)
        at callViewAction (http://localhost:8100/build/main.js:12667:17)
        at execComponentViewsAction (http://localhost:8100/build/main.js:12613:13)

**Comment by eitanfr** [comment]
hi,
1. keep the UI and the business logic is great, but you dont need to wrap apollo query with a promise, apollo.query() returns a rx observer that resolves when that data arrives like a promise.
2. not sure what is your problem , it seems that you trying to access to a value that hasnt yet resolved. you need to access the data only when it is exist, there is a few things you can do , like` `async` pipe or `?.` null safe operator syntax and so on...

**Comment by eitanfr** [comment]
If you have any more problems or questions feel free to reopen the issue

**Comment by lyxhaven** [comment]
Hi,

I have run into the similar behavior.

It's not seeing the "data" object under Resolve as a Promise, but rather simply a returned value. As a result to this, the controller and template will be initiated without knowing what "data" is and throw the same error as above.
