### ISSUE TITLE
Observables not workng for nested variable object

### ISSUE THREAD

**Issue by Anthonyzou** [apollographql/apollo-angular#303]
Hi there. I was trying to follow the apollo-angular docs for [observable variables](http://dev.apollodata.com/angular2/queries.html#observable-variables)

I have come up with some code like this.

```typescript
export class UsersComponent implements OnInit {
  // Observable with GraphQL result
  public users: ApolloQueryObservable<any>;
  public searchControl = new FormControl();
  public nameFilter: Subject<string> = new Subject<string>();

  constructor(
    private fb: FormBuilder,
    private apollo: Apollo,
    ) { }

  ngOnInit() {
    // Get all available users
    this.observeUsersSearch();
    this.nameFilter.next('')
    this.searchControl.valueChanges.debounceTime(FetchInterval).subscribe(text => {
      this.nameFilter.next(`%${text}%`);
    });
  }

  public observeUsersSearch() {
    this.users = this.apollo.watchQuery<any>({
      query: SearchUsersQuery,
      variables: {
        userWhereArgs: {
          AND: [
            {
              clientId: {
                eq: ClientId
              }
            },
            {
              OR: [
                {
                  username: {
                    like: this.nameFilter
                  }
                },
                {
                  firstName: {
                    like: this.nameFilter
                  }
                },
                {
                  lastName: {
                    like: this.nameFilter
                  }
                }
              ]
            }
          ]
        }
      }

    }).map(({data}) => data.viewer.allUsers.edges) as any;
  }

}
```
In the networks tab I am expecting the like attribute to be a string like so:

![screenshot from 2017-04-09 18-35-52](https://cloud.githubusercontent.com/assets/1567160/24842344/990881ba-1d53-11e7-958d-8921784a0f54.png)

However once I use observable variables the output is this:

![screenshot from 2017-04-09 18-34-50](https://cloud.githubusercontent.com/assets/1567160/24842350/ab5b232c-1d53-11e7-92f2-423c4cfc30c2.png)

I'm thinking there isn't handling of obvservable variables for nested attributes.

**Comment by kamilkisiela** [comment]
It's true, they don't but you can change it if you want :)

I could help you!

**Comment by kamilkisiela** [comment]
That feature, is a part of `apollo-client-rxjs`.

https://github.com/kamilkisiela/apollo-client-rxjs/blob/master/src/utils/variables.ts

**Comment by Anthonyzou** [comment]
Oh I see. Yeah I will look into that library and see if I can provide a fix.
