### ISSUE TITLE
Incompatible Types Error

### ISSUE THREAD

**Issue by tkhemani** [apollographql/apollo-angular#305]
ERROR in app.component.ts (37,53): Argument of type '{ query: DocumentNode; va
riables: { name: Subject<string>; }; }' is not assignable to parameter of type 'WatchQueryOptions'.
[1]   Types of property 'query' are incompatible.
[1]     Type 'DocumentNode' is not assignable to type 'DocumentNode'. Two different types with this name exist, but they are unrelated

**Comment by kamilkisiela** [comment]
Maybe there's a version mismatch and you have two declarations of types?

**Comment by tkhemani** [comment]
I get this error on running "npm run client" for the example app in this repo. I've changed the local ref of "apollo-angular" to this in package.json: "apollo-angular": "^0.13.0",
Also tried updating graphQL: "graphql": "~0.9.2"
No Luck.

**Comment by tkhemani** [comment]
Changed: `import { DocumentNode } from 'graphql';`
To: `import { DocumentNode } from 'apollo-client/node_modules/@types/graphql';`

Works now!
