### ISSUE TITLE
Question about two way binding and gql-response being read donly

### ISSUE THREAD

**Issue by Ramzeus** [apollographql/apollo-angular#306]
I have just started using Angular(2) and GraphQL with Apollo.
One of the first thing I had problems with was that suddenly two way binding stopped working.
When I received GraphQL data in my component and tried to change it with a form nothing happened. When I tried to change the data "manually" by setting it with a script I got an exception telling me that I was trying to modify a read only property (Cannot assign to read only property 'name' of object '#<Object>').

This all makes some sense I guess. It is probably good that the data is not mutable. However, when making a form to change the data it makes everything quite complicated. I need to either copy all the data to a new object or I need to add extra code to extract the data from the form instead. This, however, breaks third party addons like a datetimepicker I am using, that relies on the two way binding to work.

How do people usually solve this issue? Am I maybe missing something? I have not been able to find any examples on how to edit data and mutate it with a form...

**Comment by EXPEylazzari** [comment]
I have the exact same problem using Vue's [Apollo integration](https://github.com/Akryum/vue-apollo). Only simple examples are provided and they don't deal with two-way binding. I'm curious about best practices around this.

**Comment by tomermoshe** [comment]
If you need to keep a single reference to your binded data you can do something like this: 
```
apollo.watchQuery<any>({
   query: ...,
    variables: {...},
}).subscribe((result) => Object.assign(this.bindedData.field, result.data.......));
```

**Comment by tomermoshe** [comment]
If you have any more question, feel free to open a new issue.

**Comment by arshbhatti8** [comment]
@fetis  You can do a deep copy with something like `JSON.parse(JSON.stringify())` or `Lodash's deep copy`. But then you obviate the subscribe function (if you actually do subscribe to the observable it returns).
