### ISSUE TITLE
Using watchQuery with rxjs : watchQuery(...).map is not a function

### ISSUE THREAD

**Issue by nlko** [apollographql/apollo-angular#308]
Hello, 

I'm using 
```
    "apollo-angular": "0.13.0",
    "apollo-client": "1.0.3",    
    "graphql": "0.9.3",
```

I tried to follow what says the book for rxjs : http://dev.apollodata.com/angular2/queries.html#rxjs

```
 this.data = this.apollo.watchQuery({ query: FeedQuery })
      .map(({data}) => data.feed);
```

Unfortunately, when I'm doing something similar I end up with the following error : 
`EXCEPTION: this.apollo.watchQuery(...).map is not a function`

I think I manage to make it work by creating an observable from the watchQuery result. 
If it was in the documentation, it would be something using `Rx.Observable.from()`. Like this:
```
 this.data = Rx.Observable.from(this.apollo.watchQuery({ query: FeedQuery }))
      .map(({data}) => data.feed);
```

Am I wrong here or is there a mistake in the documentation ?

Thank you for helping me understand.

**Comment by eitanfr** [comment]
try adding import `rxjs/add/operator/map;`

**Comment by nlko** [comment]
Thanks!
