### ISSUE TITLE
The mutationResult parameter from updateQueries should be type ANY

### ISSUE THREAD

**Issue by Dunos** [apollographql/apollo-angular#313]
If you try to use the code provided in the documentation ([updateQueries](http://dev.apollodata.com/angular2/cache-updates.html#updateQueries)), the compiler gives you errors because **mutationResult** has defined a type Object so you can't do something like `mutationResult.data.submitComment` (data is not defined in type Object).

Example of the code that fails:

```
updateQueries: {
    Comment: (prev, { mutationResult }) => {
      const newComment = mutationResult.data.submitComment;
      const prevComments = prev.entry.comments;

      return {
        entry: Object.assign(prev.entry, {
          comments: [newComment, ...prevComments]
        })
      };
    },
  },
```

This only happens when using updateQueries in the apollo.mutate function, when you use it inside fetchMore is works fine (there is defined as any as it should be).

**Comment by eitanfr** [comment]
hi,
seems as Apollo client issue (MutationOptions type defined in apollo-client), can you please reopen the issue there. should change to `any` or may be add generics .  @stubailo 
meanwhile, you can to something like:
```
Comment: (prev, { mutationResult }: any) => {...}
```
