### ISSUE TITLE
refetchQueries ignores queries not currently active

### ISSUE THREAD

**Issue by altschuler** [apollographql/apollo-angular#317]
I have a list page of Foos. In there I have a watched query `FooList`. Now I go to the detail page of a Foo. I no longer have a `FooList` watched (it's not the in dev tools). I then delete the Foo from the detail page and redirect back to the list page. I am using `refetchQueries` to refetch the list of Foos in the list page, but it's using a cached version with the just deleted Foo still there.

I suppose the issue is that the query is not active when I do the mutation, but how can I ensure that the query is then refetched when it becomes active?

I have worked around this by refetching the query on every init of the component, in a timeout because it otherwise throws an error. Like this:

```
this.foos = this.apollo.watchQuery(...);
setTimeout(() => this.foos.refetch({}), 0);
```

Thank you very much, and thanks for a great library :)

**Comment by stubailo** [comment]
Instead of refetching on component mount you can simply pass the "forceFetch" option to watchQuery!

Anyway, this is currently the intended behavior since we don't want to keep track of every query ever done. But you can also pass the query and variables into refetchQueries to refetch stuff that isn't currently active.

**Comment by altschuler** [comment]
@stubailo Oh, great! I'm guessing `fetchPolicy: 'network-only'` is the new `forceFetch`? It makes sense that the behavior I'm seeing is the default, it's just really confusing to have a lot of different queries running and some of them "randomly" showing outdated data.

**Comment by joannabochynska** [comment]
It seems that I have the same problem when it comes to deleting items and than coming back to list view, the deleted item is still displayed. I tried to use `fetchPolicy: 'network-only` but it doesn't seem to be working. Can it be used with watchQuery, not only with query?

**Comment by altschuler** [comment]
@joannabochynska I'm using it with `watchQuery`. Are you sure you're actually invoking the query again? Closing the issue since it's "solved".
