### ISSUE TITLE
Standard For Multiple Mutations

### ISSUE THREAD

**Issue by bclynch** [apollographql/apollo-angular#318]
I was hoping someone could explain the standard way to execute multiple mutations with apollo in a single http call on the front end.

My use case is I am inserting multiple (n) product rows into a join table for an order at a time. Within the Graphiql playground I am aware of using aliases to use multiple of the same mutation as shown below, but I was wondering how to use have a dynamic amount with apollo + gql since it is normally pretty static?

I could theoretically loop through and make a single mutation for each, but I was hoping there might be something better.

```typescript
mutation {
  a: createOrderProduct(input:{
    orderProduct: {
      orderId: 14,
      productId: 3,
      productQuantity: 1
    }
  }) {
    clientMutationId
  }
  b: createOrderProduct(input:{
    orderProduct: {
      orderId: 14,
      productId: 2,
      productQuantity: 3
    }
  }) {
    clientMutationId
  }
}
```

Thanks

**Comment by tomermoshe** [comment]
You can use batching in order to execute multiple mutation and query in a single request.
All you need you need to do is:
 ```
ApolloClient({
 //other options...,
 shouldBatch: true,
 batchInterval: 10, //not required- default is 10(ms)
});
```
This will batch your queries and mutations together. You will also get a single response that will be automatically unpack by the network interface.

For more reading: http://dev.apollodata.com/core/network.html#query-batching

**Comment by tomermoshe** [comment]
If you have any more questions, feel free to open a new issue.

**Comment by bclynch** [comment]
Hey thanks for the response @tomermoshe . Finally got around to trying to implement and it looks like query batching is not supported by the server I'm using (Postgraphql). Appreciate the input though!
