### ISSUE TITLE
Subscriptions are not executed in NgZone

### ISSUE THREAD

**Issue by ribizli** [apollographql/apollo-angular#320]
If a subscription event comes, the store is updated, the observable emits, but no change detection is running in angular. (I need to interact with a component to get the view being updated)

```typescript
// service
const gameChanges = gql`
  subscription GameChanges {
    gameChanged {
      ...GameFragment
    }
  }
  ${UserFragment}
  ${GameFragment}
`;

this.gameChanges$ = apollo.subscribe({
      query: gameChanges
    }).map((r: { gameChanged: Game }) => r.gameChanged)

// component
this._gameService.gameChanges$.subscribe(g => console.log(`game changed: ${g.id}`));
```

**Comment by ribizli** [comment]
My current workaround for this is to delay the emission into the next event loop (???): 
```typescript
this._gameService.gameChanges$.delay(0).subscribe(g => console.log(`game changed: ${g.id}`));
```

**Comment by eitanfr** [comment]
`apollo.subsribe` is wraped with zone current zone , so change detection should be invoked. 
can you show the components code? do you use ON_PUSH?

**Comment by ribizli** [comment]
No ON_PUSH at all. My other comp uses watchQuery with async. I expect it's view to get updated automatically but it won't.
More code sample I can provide later on...

**Comment by alansmithribae** [comment]
I am also seeing this issue on our project. Delay didn't work for me, instead Apollo subscription results seem to have to be wrapped in a zone.run(() => { ... }) to get Angular templates to update.

We are using stock change detection (i.e NO ON_PUSH)
Could this also be related to [#295](https://github.com/apollographql/apollo-angular/issues/295)?

**Comment by ribizli** [comment]
I can again confirm, that this **bug is still valid**.

I've tested it with `NgZone.isInAngularZone()` in the `next()` handler, and any emission caused by an Apollo Client cache update is outside of `NgZone`.

Again a short description:
I use `watchQuery` to query an object. The first result is emitted in `NgZone`. Later a GraphQL Subscription sends an update of this object. The emission from the subscription's `Observable` is also correctly in `NgZone`. But the caused cache update in the client's cache triggers an emission of the `watchQuery` which is not in `NgZone` anymore.

**Comment by ribizli** [comment]
Workaround No.2 - wrapping the watchQuery observable into `NgZone`:
```typescript
function observeOnZone<T>(this: Observable<T>, zone: NgZone): Observable<T> {
    return Observable.create(observer => {
        var onNext = (value) => zone.run(() => observer.next(value));
        var onError = (e) => zone.run(() => observer.error(e));
        var onComplete = () => zone.run(() => observer.complete());
        return this.subscribe(onNext, onError, onComplete);
    });
};

Observable.prototype.observeOnZone = observeOnZone;

declare module 'rxjs/Observable' {
  interface Observable<T> {
    observeOnZone: typeof observeOnZone;
  }
}

// in service

this._apollo.watchQuery<CurrentPlaylistQueryResult>({
  query: currentPlaylistQuery
}).map(r => r.data.currentPlaylist)
  .observeOnZone(this._ngZone);
```

**Comment by kamilkisiela** [comment]
works in `apollo-angular@1.0.0`
