### ISSUE TITLE
require(...*.graphql) doesn't work in angular cli generated project

### ISSUE THREAD

**Issue by davideberlein** [apollographql/apollo-angular#321]
Hey, 

I am trying to apply your tutproial with a project that I created using the angular cli.
Most of it is fine but I have 2 problems.
Here is nr. 1 I will add nr. 2 in a second issue.

``` typescript
const UsersQueryNode: DocumentNode = require('graphql-tag/loader!../graphql/Users.graphql');
```
does not work for me, the TS compiler says: 

> Cannot find name 'require'.

 Not sure what the problem here is, I added the `@types/node` to the tsconfig.

**Comment by eitanfr** [comment]
hi, 
seems you don't have require typings. try installing `@types/node`. 
anyway, I am working with angular CLI project and I haven't encountered any problem.

**Comment by davideberlein** [comment]
@eitanfr I had already added `@types/node` to the package.json. Do I need to import the "require" somewhere else?

**Comment by eitanfr** [comment]
Maybe you have a wrong tsconfig settings , 
Try adding `"types": ["node"]` to the `compilerOptions` in the tsconfig.app.json

**Comment by davideberlein** [comment]
@eitanfr thanks, that solved the issue.

**Comment by loxy** [comment]
This works fine, but the webpack (Angular CLI) still logs the error on console. Any suggestions to fix that?
