### ISSUE TITLE
Cache updates

### ISSUE THREAD

**Issue by Draccoz** [apollographql/apollo-angular#326]
Is there any way to update a cache reliably? I know there is the `update` method, but so far in the tutorials and examples I've seen only updating whole "global" lists (like list of ALL ToDos etc.). What about the case, where I have a `Client` type and each client has its very own `ToDo`s (relational data from MySQL)? How to update `ToDo`s of specific `Client` once it's added? This is pretty trivial task, but so far I found it impossible to achieve without resetting the store each update.

**Comment by kamilkisiela** [comment]
Depends on your structure but since Apollo has it all stored flat and normalized. You can decide how an id of a record is being generated and update fragment or a whole query via Cache.

https://www.apollographql.com/docs/angular/basics/caching.html

**Comment by Draccoz** [comment]
I think I wasn't clear enough.
The scenario is that:
1. We have a list of **Users**
2. **Each** user has a list of **Tasks**
3. A **task** is added for a **single user**
4. How to update list of **tasks** for a **specific** user that the change concerns?

I know I can write a bunch of code taken from the backend, that would decide which task belongs to whom, but isn't there a faster way to say "only update one list of tasks, for the user that got the new task"?
