### ISSUE TITLE
error on angular 4.2.5

### ISSUE THREAD

**Issue by razzaghi** [apollographql/apollo-angular#327]
apollo-angular/node_modules/apollo-client-rxjs/build/src/RxObservableQuery.d.ts (7,22): Class 'RxObservableQuery<T>' incorrectly extends base class 'Observable<ApolloQueryResult<T>>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<ApolloQueryResult<T>, ApolloQueryResult<R>>) => Observable<ApolloQueryResu...' is not assignable to type '<R>(operator: Operator<ApolloQueryResult<T>, R>) => Observable<R>'.
      Types of parameters 'operator' and 'operator' are incompatible.
        Type 'Operator<ApolloQueryResult<T>, R>' is not assignable to type 'Operator<ApolloQueryResult<T>, ApolloQueryResult<{}>>'.
          Type 'R' is not assignable to type 'ApolloQueryResult<{}>'.

**Comment by beagleknight** [comment]
I managed to fix some of this errors like this:

Instead of this:

```typescript
this.apollo.watchQuery({
  ...  
}).combineLatest(other$, ...)
```

I used: 

```typescript
Observable.combineLatest(
  this.apollo.watchQuery({
    ...  
  }),
  other$,
  ...
)
```

**Comment by beagleknight** [comment]
@razzaghi My CI build the project successfully so I suspected it was related to the dependencies cache. I performed a cleanup of my node_modules (`rm -rf node_modules && yarn cache clean && yarn`) and it works as expected.

**Comment by beagleknight** [comment]
I still have the same problem :(. I updated yarn and I start getting the same error again:

```
ERROR in /Users/beagleknight/projects/codegram/empresaula/teacher-panel/node_modules/apollo-client-rxjs/build/src/RxObservableQuery.d.ts (7,22): Class 'RxObservableQuery<T>' incorrectly extends base class 'Observable<ApolloQueryResult<T>>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<ApolloQueryResult<T>, ApolloQueryResult<R>>) => Observable<ApolloQueryResu...' is not assignable to type '<R>(operator: Operator<ApolloQueryResult<T>, R>) => Observable<R>'.
      Types of parameters 'operator' and 'operator' are incompatible.
        Type 'Operator<ApolloQueryResult<T>, R>' is not assignable to type 'Operator<ApolloQueryResult<T>, ApolloQueryResult<{}>>'.
          Type 'R' is not assignable to type 'ApolloQueryResult<{}>'.
```

**Comment by beagleknight** [comment]
@razzagui The problem is being adressed here https://github.com/kamilkisiela/apollo-client-rxjs/pull/44

**Comment by kamilkisiela** [comment]
Hi all!

Try to add `apollo-client-rxjs@0.6.0-rc.1` as a dependency in your project and tell me how it works for you ;)

**Comment by abdulhaq-e** [comment]
It didn't solve the problem, PR #45 did though, I tested it.
