### ISSUE TITLE
error cannot resolve AppModule (first time)

### ISSUE THREAD

**Issue by lagmanzaza** [apollographql/apollo-angular#328]
![888](https://user-images.githubusercontent.com/5283709/28159065-edcd6f44-67e5-11e7-8322-5432d78092a2.PNG)

**Comment by mitul69** [comment]
I have same issue can you please help me.

**Comment by lagmanzaza** [comment]
I'm not sure how to fix it but I  rewrite my project use it's work

**Comment by mitul69** [comment]
Ohh so you have installed all again?

**Comment by lagmanzaza** [comment]
yes sir

**Comment by lagmanzaza** [comment]
I'm so sorry that I cannot show my code because they uses in my company

**Comment by mitul69** [comment]
It's ok not an issue i am switching some where else.

**Comment by lagmanzaza** [comment]
I think it's a bug in this example when I create a new project then use angular-apollo by the guide in dev.apollo its work  
You should follow the guide first.
I am willing to teach you.
you can ask me by Facebook  FB/lagman2600th directly
thank you very much.

I'm bad in English

**Comment by kamilkisiela** [comment]
It won't be a problem anymore. Please try to use v1.0
