### ISSUE TITLE
Cannot edit response object - Object frozen

### ISSUE THREAD

**Issue by kadosh1000** [apollographql/apollo-angular#329]
Hi, I have the following code:
      const GetChatsQuery = gql `
        query($withBlocked: Boolean) { 
            userChats(withBlocked: $withBlocked) { 
                ${ GetChatGraphQL(10) }
            } 
        }`;

        ` return this.apollo.query({
            query: GetChatsQuery,
            variables: {
                withBlocked: withBlocked
            }
        }).map(res => {
            let response = <GetChatsResponse>res.data;
            // I get here the error
            response.userChats[0].messages.push(null);
            return response.userChats;
        })`

The thing is that I'm getting an error on the push method:

> Cannot add property 2, object is not extensible

As I understood from the internet it means that the object is frozen (`Object.freeze`).
Have anyone had that problem before? how can I solve it?

**Comment by niceilm** [comment]
In my case to use copy object
```
 return this.apollo.query({
        query: GetChatsQuery,
        variables: {
            withBlocked: withBlocked
        }
    }).map(res => {
        let response = <GetChatsResponse>res.data;
        // I get here the error
        response.userChats[0].messages.push(null);
        return {... response.userChats};
    })
```

**Comment by intellix** [comment]
Aye, you can use object destructuring, but be aware that its only a shallow copy and other objects will maintain the same frozen reference since Apollo deeply freezes objects. Similar q: https://github.com/apollographql/apollo-client/issues/1909

**Comment by benthepoet** [comment]
We definitely need some sort of option to disable the freezing. Took me a while to figure that the frozen response was preventing `ngModel` from working on my forms.

**Comment by Kliton** [comment]
News?

**Comment by ryansolid** [comment]
Yeah I came across this using nested proxies for fine grained change notification. Even if I have no intention of changing the original and seek to do referential equality the invariant for frozen object prevents the getter property returning a proxy. Resorting to JSON stringify or cloning removes any referential checking ability. 

In general frozen objects while useful for enforcing immutability, get in the way of performance optimizations that can be used in libraries that work off mutable state even if the consumer has no intention of ever mutating that specific data.

**Comment by plck** [comment]
I've been trying to solve this for weeks now. I'm using this utility function for now to clone my response: https://gist.github.com/plck/ff0e95060f41ccf3eeaf95d6fc34e92e
but this is a workaround, not a solution.

**Comment by 4F2E4A2E** [comment]
@kadosh1000 did you find any solution by now?

**Comment by senthilsivanath** [comment]
Facing same issue, took some time to find the root, getting an option in clientOptions to unfreeze and unseal would help.

**Comment by 4F2E4A2E** [comment]
Are you using dynamic forms?

**Comment by kamilkisiela** [comment]
It's by design. You don't want to touch store directly so Apollo Client freezes the result. It's the same behaviour as in Redux, Ngrx and so on. They don't freeze the results but they say to not mutate it. This won't change anytime soon.

**Comment by ranbuch** [comment]
@kamilkisiela I have no idea how am I supposed to let the user edit fields with freeze objects.
```javascript
Object.freeze = () => {};
// or:
// eval("Object.freeze = () => {}"); 
// on typescript
```
works for me.

**Comment by kamilkisiela** [comment]
@ranbuch By "edit fields" you probably mean Form and Inputs that user can modify. If so, then use [Reactive Forms](https://angular.io/guide/reactive-forms). You don't need to touch an object directly.

**Comment by ranbuch** [comment]
Thank you @kamilkisiela but I'm using Angular 6.

Any way it's working for me there with `FormGroup` and `ngModel` but sometimes you need to edit things programmatically, not by UI bindings.

For example, the user insert a string and I need to add this string as part on an Object with other parameters form multiple services and then push it to some array in the `freeze` Object.

**Comment by ranbuch** [comment]
```javascript
Object.freeze = () => {}
``` 
Messes things up, I'll just deep-copy the response like this:
```javascript
let unFreeze = JSON.parse(JSON.stringify(response));
```
