### ISSUE TITLE
Using a different store(angular-redux) does not work correctly

### ISSUE THREAD

**Issue by gotenxds** [apollographql/apollo-angular#330]
Hi, I'm following the guide [here](http://dev.apollodata.com/angular2/redux.html) and the repo [here](https://github.com/alexthewilde/angular-redux-apollo-example)

This does not seem to work anymore in the newest version of apollo angular and angular-redux for 2 reasons:

1. (Looks like a angular-redux error)
The `reduxRootSelector` of apollo need to be set to this `state => state.computedStates[0].store.apollo`.
The `getState` method of angular-redux now returns this weird non state object. ^^

2.(Looks like an angular-apollo error)
After successfully running angular-apollo with angular-redux querys no longer seem to work.
calling `watchQuery` does indeed fetch the data, you can see the request being sent and the data returns in the network tab of the dev tools, but the observable is never notified, after debugging unfemilier ugly compiled js code for about 1 and half hours I think the section of the querymanager that checks if the new state and the old state are different does not compare the new state but instead compares the old and the old state with each other instead.

I've also opned an [issue](https://github.com/angular-redux/store/issues/445) with angular-redux as this seems to be an issue(s) on both parties.

**Comment by kamilkisiela** [comment]
Thanks to ApolloClient 2.0 it will be possible to use it with any cache mechanism you want to. 2.0 and new version of apollo-angular is coming soon. Check this #377
