### ISSUE TITLE
difficult to use RxJs operators like .map against watchQuery data; data not a stream

### ISSUE THREAD

**Issue by sarora2073** [apollographql/apollo-angular#331]
Hi,

This report is related to #48 ("Can't call rxjs observable operators on object returned by watchQuery") which has been addressed in some manner in the past. I believe there may be a common scenario which is unnecessarily difficult to handle. 

Detailed explanation with example:

When doing a normal watchQuery the shape of the result contains an array of objects (rows in a table or documents in a given collection), and it is **this array e.g. in bold below** that we typically need to perform RxJs operations against e.g. to make transformations using .map against each object.

{
  "data": {
    "getContacts": **[
      {
        "_id": "58dbcc0e0b33b63808f687d8",
        "name": "test1",
        "created": "2017-03-29T15:00:30.278Z",
        "modified": "2017-07-15T00:17:26.524Z"
      },
      {
        "_id": "59695a62c2500f2c088e2782",
        "name": "test2",
        "created": "2017-07-14T23:57:22.003Z",
        "modified": "2017-07-15T00:17:01.156Z"
      },
    ]**
  }
}

Unless i'm missing something, it appears very cumbersome to use RxJs against the object array, because afaik, the object array itself is not a stream. For example, I was trying to get some data and format it to fill a dropdown select list i.e. transform the raw data into an **object like the one in the 2nd map statement below** that has the value and the display version of the same value. To created the desired data structure I can't simply do something like this (with 2 .maps, let alone one):

```
    this.dataService.getContacts()
      .map( ({data}) => data.getContacts)
      .map((data) => { return { value: data._id, viewValue: data.name }; }) // <-- this second .map returns undefined values, unless I do something like data[0]._id which defeats the purpose..i need to work with a stream
      .subscribe(data => {
        console.log(data);
      });

(note: for reference here's the underlying method..)
    getContacts(): ApolloQueryObservable<any> {
        return this.apollo.watchQuery({
            query: queries.getContactLists,
            fetchPolicy: 'network-only'
        });

```
Any time i try to get at the object array it treats the entire array as one collection, not something I can transform object by object. For this reason, i find it necessary to convert it to an Observable, and only then can i run additional RxJs transformations like .map to created the desired object, as follows:

```
// THIS "WORKS" 
    this.dataService.getContacts()
      .map(({ data }) => data.getContacts)
      .subscribe((res) => {
        this.contacts = res;
        let contactsDropDownList = Observable.from(this.contacts);
        contactsDropDownList.map((data: any) => { return { value: data._id, viewValue: data.name }; } )
          .subscribe(data => {
            console.log(data); 
          });
      });
```

I'm really hoping there a simpler way (or in future there will be an easier way) to run RxJs operations against the "actual data" I need to work with (by which i mean the object array, not it's container / graphql metadata etc.) without having to do all the above. My concerns with having to do the above approach include:
- too verbose / too many steps for a common scenario; the approach that fails above with 2 .map should work imho.
- "callback hell" issues since the second .map call has to be done in the .subscribe method of the first operation

Any thought / advice greatly appreciated.

Thank you, 

- S. Arora

**Comment by agborkowski** [comment]
.map(({ data }) => data.getContacts)
->>.take(1)<-- ??
      .subscribe((res) => {

**Comment by sarora2073** [comment]
Hi,

Thanks for responding, but not sure if you understood fully...I want avoid concerns of handling arrays / index-based operators etc. and consume the entire data set (not a subset) *as a stream* instead of single object array collection, and transform it object-by-object using rxjs / functional reactive approach, without having to create a new Observable or for example having to use another toolkit like lodash. 

I would have thought graphql would provide the "actual" desired data set as a stream but was surprised to find it did not work this way. The watchQuery result appears to be a stream at first blush..you can use rxjs operators at the 'data' field level, but in real-life scenarios we usually need to run operations one-level down e.g. data.getContacts gets the collection of contacts from the db in my example. 

Incidentally, according to an (outdated?) example from http://dev.apollodata.com/angular2/queries.html copied below the object array is right under the data field level:

{
  "data": {
    "currentUser": { ... },
    "feed": [ ... ]
  }
}

The latter result shape seems better suited for the task at hand..wondering if there was a breaking change at one point when they nested the data one-level down that resulted in the difficulties i'm encountering...just a thought.

**Comment by j3ddesign** [comment]
Hi, one way my team has gotten around this for now is similar to the following (forgive rough code, typing from memory)

```
 this.dataService.getContacts()
   .switchMap(({data}) => Observable.fromArray(data.contacts))
   .map((data) => { return { value: data._id, viewValue: data.name }; }) // <-- this second .map returns undefined values, unless I do something like data[0]._id which defeats the purpose..i need to work with a stream
   .subscribe(data => {
     console.log(data);
   });
```

This seems to do the job for now, though it would be nice to have a cleaner way of handling data returns, I agree

**Comment by sarora2073** [comment]
@j3ddesign  - THANK YOU! 

using switchMap solved the problem and allowed me to get back to functional reactive code semantics. :-)
