### ISSUE TITLE
watchQuery fails to run when variables parameter is an empty object

### ISSUE THREAD

**Issue by sarora2073** [apollographql/apollo-angular#333]
Hi,

I tried profiling network requests in chrome to debug this issue where a watchQuery wasn't even executing as expected, and what it appeared to boil down to was that the query wouldn't execute if the variables parameter was an empty object i.e. {}. I would expect it to at least execute.

Below is a copy of the code. I tried the line that starts with "let obj =" 3 ways to confirm what's going on.

```
    getCompaniesCount(searchTerm?): any {
        // let obj = _.assign({}, searchTerm ? { 'searchTerm': searchTerm } : null); // test #1: null object as variable => result: query below fails to execute
		// let obj = {}; // test#2: with empty object the query below also fails to execute
        let obj = { 'searchTerm': searchTerm }; // test#3: query executes
        return this.apollo.watchQuery({
            query: queries.getCompaniesCount,
            fetchPolicy: 'network-only',
            variables: obj
        }).map((res: any) => res.data.getCompaniesCount);
    }
```

This issue is somewhat easy to work around in simple cases once you know what to watch for, but nevertheless I deem it a bug and resolution would aid more robust code, and avoid having to write too much defensive code.

Regards,

-S. Arora

**Comment by kamilkisiela** [comment]
It's not an issue anymore. If you disagree just @mention me here so I can reopen it.
