### ISSUE TITLE
how to setup subscription to angular 4?

### ISSUE THREAD

**Issue by lagmanzaza** [apollographql/apollo-angular#336]

**Comment by kamilkisiela** [comment]
Could you explain?

**Comment by lagmanzaza** [comment]
can you example app for me

**Comment by lagmanzaza** [comment]
I don't know  how to setup subscription and use with watchQuery()  

thank you very much

**Comment by kamilkisiela** [comment]
It's all here 
https://www.apollographql.com/docs/angular/features/subscriptions.html
