### ISSUE TITLE
no exported member 'ApolloExecutionResult'

### ISSUE THREAD

**Issue by PtrWlp** [apollographql/apollo-angular#351]
apollo-client-rxjs@0.5.2, apollo-client 1.0.0 and appollo-angular@0.13.1 gives me 
`Error at /Users/(me...)/node_modules/apollo-angular/build/src/Apollo.d.ts:2:100: Module '"/Users/(me...)/node_modules/apollo-client/index"' has no exported member 'ApolloExecutionResult'. `
Also in combination with apollo-client-rxjs@0.6.0-rc.1.

**Comment by PtrWlp** [comment]
Also in combination with apollo-client-rxjs@0.6.0-rc.1 i fear...

**Comment by Chabane** [comment]
Same issue

**Comment by mwld** [comment]
I think there are issues with apollo-angular-rxjs. See theses posts/issues for more detail:
- https://github.com/apollographql/apollo-angular/issues/346#issuecomment-323321202
- https://github.com/kamilkisiela/apollo-client-rxjs/issues/42

Downgrading apollo-angular to 0.13.0 should make it work for you in the meantime.

**Comment by PtrWlp** [comment]
Yes, so we noticed. Good luck with the next version! Thanks.
