### ISSUE TITLE
Issue after upgrading to 0.13.1 from 0.13.0

### ISSUE THREAD

**Issue by crumhorn** [apollographql/apollo-angular#353]
I just upgraded my versions to the latest as of this writing;
- apollo-angular@0.13.1
- apollo-client@1.9.2
- apollo-client-rxjs@0.6.0-rc.1

And am getting the following error when I try to load up my Angular 2 application:

`Error: Unable to dynamically transpile ES module
   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
  Instantiating http://localhost:3000/node_modules/apollo-client-rxjs/index.js
  Loading http://localhost:3000/node_modules/apollo-angular/build/bundles/apollo.umd.js
  Loading app/main
    at transpile (system.src.js:3694)
    at system.src.js:3476
    at ZoneDelegate.invoke (zone.js:392)
    at Zone.run (zone.js:142)
    at zone.js:844
    at ZoneDelegate.invokeTask (zone.js:425)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at <anonymous>`

I'm not sure how it's loading up the RXJS but there seems to be some difference between previous versions of above packages and the latest version that I can't seem to figure out what it is. Has anyone else run into this and solved it? Usually that error means it didn't manage to load something either because it didn't find a necessary file, or there's some issue with ES versions. 

I'm not sure if it's an issue that the apollo.umd.js is looking for apollo-client.rxjs/index.js rather than the apollo-rxjs.umd.js file?

Any ideas would be appreciated :+1:

**Comment by crumhorn** [comment]
Just want to add, with all other versions staying on the latest, but changing apollo-angular back to 0.13.0 it works again, so the change must be between 0.13.0 and 0.13.1.

**Comment by kamilkisiela** [comment]
No more `apollo-client-rxjs`. 
#377
