### ISSUE TITLE
http request called more than once when biding to view with `async` Pipe

### ISSUE THREAD

**Issue by dotansimha** [apollographql/apollo-angular#354]
Running `watchQuery` with a query, and use the observable returned from the request this way, inside a component:
```ts
const obs = this.apollo.watchQuery(...);
this.c$ = obs.map(data => data.a.b.c);
this.d$ = obs.map(data => data.a.b.d);
```

Then, in the template, I am using:
```ts
<div>
C Value: {{ $c | async }}
D Values: {{ $d | async }}
</div>
```

And it causing the apollo-client to execute the http request of the query twice. 

I found a temporary workaround:
```ts
const obs = this.apollo.watchQuery(...).publishCount(1).refCount();
```

@Urigo @eitanfr @tomermoshe @kamilkisiela

**Comment by DxCx** [comment]
calling twice is the expected behavior as it is created as cold observable.
your workaround is the correct solution which is to make it hot observable.
im not sure if we want the observables to be hot out of the box.

**Comment by dotansimha** [comment]
@DxCx why not? how does that effect the behavior of the observable in our case?

**Comment by abdulhaq-e** [comment]
Just to make a note here, this behaviour is described in the docs. I was about to use the `async` pipe (cleaner code) when I read it.

> Note: Using async pipe more than once in your template will trigger the query for each pipe. To avoid the situation subscribe to the data in the component, and display the data from the component’s property.
http://dev.apollodata.com/angular2/queries.html

**Comment by DxCx** [comment]
@dotansimha an observable can be warmed by multicasting it, but once multicast it cannot be unmulticasted.
by default, most of the observables you will get are cold ones..
so you can "warm" it yourself but i don't see a reason to force it

**Comment by eitanfr** [comment]
@dotansimha I also think that the best thing is to call `publish()` or `share()` yourself, this way you give the user the freedom to what ever he wants with his RxObserver

**Comment by raysuelzer** [comment]
I am running into a similar issue after upgrading from beta to 1.0.0 where my async pipes have stopped working. Any async pipes now just cause the application to hang, probably due to apollo-link-dedup.  Has anyone else experienced this?

**Comment by Sevensnake** [comment]
I am also. same problem angular 6.2

**Comment by kamilkisiela** [comment]
Okay, I discussed the issue with @darkbasic and it seems like it has been fixed since then.

Reproduction:
- apollo-angular https://stackblitz.com/edit/apollo-angular-deduplication
- apollo-client https://stackblitz.com/edit/apollo-deduplication

If some of you can create a test or even a simple reproduction please @mention me here so I reopen.
