### ISSUE TITLE
watchQuery events

### ISSUE THREAD

**Issue by cime** [apollographql/apollo-angular#355]
Is it possible to know when will the query be executed when you use watchQuery? I would like to set a isBusy property to true before the query is executed and to false on response/error.
I have an angular component for data table that takes query and variables as input. Those variables are merged with component's internal variables (for paging etc).

Something like:

    this.apollo.watchQuery({
        query: ...,
        variables: ...,
        beforeEachRequest: () => {
             this.isBusy = true;
        }
    });

**Comment by kamilkisiela** [comment]
Observable that comes from `watchQuery` works like any other Observable. 
You can create a wrapper function that runs query so you know when `isBusy` should be `true` and then you can use RxJS `do` operator to catch the response and set it to `false`.
