### ISSUE TITLE
Support for Angular v5

### ISSUE THREAD

**Issue by CaerusKaru** [apollographql/apollo-angular#357]
Angular will be entering RC for v5.0.0 in [roughly a week](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md), so this issue is open to track compatibility issues with the latest version.

One breaking change already shown is the deprecation of OpaqueToken, which is fixed with #316 (potentially).

**Comment by kamilkisiela** [comment]
First step to support v5 #358

**Comment by intellix** [comment]
Installing Angular 5 in my project and am blocked by this not being released. 
Would be cool if @next was published after every commit so we can live on the edge :)

```
$ npm dist-tag ls apollo-angular
latest: 4.1.4
```

**Comment by CaerusKaru** [comment]
Compiling errors with AOT, documented here #363
