### ISSUE TITLE
apollo angular watchQuery with pollInterval not working

### ISSUE THREAD

**Issue by davidctaylor** [apollographql/apollo-angular#370]
Hi,
I'm having an issue using pollInterval with watchQuery, this initial query is returned but subsequent requests are not made.

Relevant pieces from package.json
        "apollo-angular": "0.13.1",
        "apollo-client": "^1.9.1",
        "apollo-client-rxjs": "^0.6.0-rc.1",
        "graphql": "^0.11.2",
        "graphql-tag": "^2.4.2",

This is my code;         
this.apollo.watchQuery<any>({
                query: queryName,
                pollInterval: 1000,
                variables: {
                    name: 'testing',
                },
            }).subscribe((res: ApolloQueryResult<any>) => {
                console.log('Got Data', res);
            }, (err: any) => {
                console.log('Error loading data');
            });

Thanks,
David

**Comment by KillerCodeMonkey** [comment]
it is working i think, but you have to keep in mind, that you callback is only executed if there are any changes in the cache/response object.

I had the same misleading idea how this works.

1. if you want to make a request everytime, you need to change the fetchPolicy from `cache-first` (if the value is in cache --> no requests are made)
2. even if you set fetchPolicy to `network-only` --> requests are made in the specified polling interval, but your callback is only executed if the response value changes. ;)

**Comment by yashwp** [comment]
@KillerCodeMonkey 
I've implemented it in the same way as you have mentioned here... Here is my code below, which is throwing an error and also my WebStorm is showing error **Expected 2-3 arguments and got 1**

**Console Error** - 
```
 Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql
````

**Code**- 
```
      this.apollo.watchQuery({
            query: NotificationsQuery,
            pollInterval: 1000,
            variables: {
              ei_id: this.currentUser.managed_institution.id,
              first: 10,
            },
            fetchPolicy: 'network-only'
          })
            .pipe(takeWhile(() => this.isAlive))
            .subscribe((notifs: any) => {
              if (notifs) {
                const nEdges = notifs.educationalInstitutionGet.notifications.edges;
                this.notifications = nEdges.map((i: NotificationTypeEdge) => i.node);
                this.isLoading = false;
              }
            }, (err: any) => {
              this.isLoading = false;
              this.errorService.showErrorModal(err.networkError);
        });
```

**GQL query**
```
export const NotificationsQuery = gql`
  query NotificationsQuery($ei_id: Int!, $first: Int) {
    educationalInstitutionGet(id: $ei_id) {
      id
      notifications(first: $first) {
        edges {
          node {
            body
            read_at
          }
        }
      }
    }
  }
`;
```

**Comment by kamilkisiela** [comment]
Please create a reproduction on stackblitz.io or similar.

Here's a template: https://stackblitz.com/edit/simple-apollo-angular-example
