### ISSUE TITLE
Warning: Can't resolve all parameters for Apollo (AOT, @angular/cli)

### ISSUE THREAD

**Issue by ribizli** [apollographql/apollo-angular#372]
Warning: Can't resolve all parameters for Apollo in C:/work/DAS/workspace/das-gui/node_modules/apollo-angular/build/src/Apollo.d.ts: (?). This will become an error in Angular v5.x

**Comment by kamilkisiela** [comment]
This issue will be fixed with the [upcoming release](https://github.com/apollographql/apollo-angular/blob/master/CHANGELOG.md#vnext)
