### ISSUE TITLE
How to use forRoot when ApolloClient depends upon angular service

### ISSUE THREAD

**Issue by raysuelzer** [apollographql/apollo-angular#375]
How would you configure the ApolloModule to accept an Apollo client that depends upon an Angular provider.  For example, I use Angular2Token, I need to have my AppoloClient use Angular2Token as a middleware, but I cannot pass anything except a parameterless function into forRoot method.

**Comment by kamilkisiela** [comment]
It will be possible in the next release of angular-apollo. Stay tuned

**Comment by kamilkisiela** [comment]
@raysuelzer It's out! Check v1.0
