### ISSUE TITLE
New subscription for each call to fetchMore

### ISSUE THREAD

**Issue by miquelferrerllompart** [apollographql/apollo-angular#376]
Hello,

I have a problem with `fetchMore` function of `watchQuery`.
I have implemented a infinite scroll for my app, when i call to `fechMore` function of my `watchQuery` is created a new Subscription, i can see on "Apollo Dev Tools".
The problem is i can't unsubscribe of this new subscriptions because i don't have any reference about them.

This is the watchQuery function:
```
this.query = this.apollo.watchQuery<{ Customers: Array<Customer> }> ({
      query: gql`
        query Customers ($orderBy: String, $first: Int, $skip: Int) {
          Customers: allCustomers(
            orderBy: $orderBy
            first: $first
            skip: $skip
          ) {
            ...customerListFragment
          }
        }
        ${ customerListFragment }
      `,
      variables: { orderBy: "firstName_ASC", first: 20, skip: 0 },
    });
```

and with the reference of this i call to fetchMore:
```
this.query.fetchMore({
      variables: { skip: 20 },
      updateQuery: (prev, { fetchMoreResult }) => {
          if (!fetchMoreResult) return prev;
          return Object.assign({}, prev, {
            Customers: [...prev.Customers, ...fetchMoreResult.Customers],
          });
        },
    });
```
Each time when i call this function for feachMore results is created a new subscription.
Is the expected behavior? How i can unsubscribe for this new subscriptions?

Thank you!

**Comment by kamilkisiela** [comment]
I think it's on the `apollo-client` side but give me some time to check it.

**Comment by chris08002** [comment]
@kamilkisiela Did you have a chance to look at this one?

**Comment by miquelferrerllompart** [comment]
Hi @kamilkisiela Did you have some update?

**Comment by raysuelzer** [comment]
I can confirm this leak happens. Is there a fix for this?

**Comment by Vendium** [comment]
Any new about this issue?

**Comment by kamilkisiela** [comment]
Does anyone want to take a look at this? I could help and answer all questions about Apollo if needed.

**Comment by kamilkisiela** [comment]
I'm closing in favor of this one apollographql/apollo-client#2286
