### ISSUE TITLE
Angular HowToGraphQL sample for apollo-angular 1.0

### ISSUE THREAD

**Issue by b-barry** [apollographql/apollo-angular#379]
Hello @kamilkisiela,

First of all, I would like to thank you for the work done for the 1.0. 
I was working on "how to graphql" version angular, and I had some bugs regarding the subscription with the old version.
Now, with the 1.0, all examples are working. You can find the [code](https://github.com/howtographql/angular-apollo) 

If you need help for the documentation or creating recipes,  I will be glad to give a hand :)

**Comment by kamilkisiela** [comment]
@b-barry That's super awesome! I will definitely need some help on documenting new things, will message you :)

**Comment by Dutchboy** [comment]
@b-barry @kamilkisiela  I want to join in!.... I know it's been 9 days... A bit late, another lunatic ISIS attack later, but I think I can be of value..... 

@b-barry .... you're of immensely great value, but even though you got it working, and in the short time gave it a chance I didn't, I do think there should be a much nicer (SOC) separation of concerns here... and get ngrx into it too.... ngrx is angular, let's face it.... I'm European (still) so, for me it's night and I'll get to it tomorrow...... Will get back to you.... both.... and then, @kamilkisiela you will have to open a new repo to get it going - I'm not into it, you are
