### ISSUE TITLE
"Initialization" section in documentation installs incorrect apollo-client version

### ISSUE THREAD

**Issue by nlko** [apollographql/apollo-angular#385]
To my understanding apollo-angular doesn't support yet apollo-client 2.x. While apollo-angular 1.x for (for apollo-client 2.x) is still in beta version, I think it is better to force a stable apollo-client ^1.x version to avoid troubles to newcomers.

The current documentation could be updated to 

```
npm install apollo-client@^1.x apollo-angular graphql-tag --save
```

**Comment by kamilkisiela** [comment]
Thanks! Docs has been updated
