### ISSUE TITLE
updateQueries no longer working in beta 1.0.0? 

### ISSUE THREAD

**Issue by raysuelzer** [apollographql/apollo-angular#389]
It appears that updateQueries no longer workins in the 1.0.0 beta branch.  

Any code in `updateQueries` is no longer run:

```    this.apollo.mutate<Mutation>({
      mutation: createInviteMutation,
      variables: {
        input: {
          email: this.createInvitiationFormModel.email,          
        } 
      },      
      updateQueries: {
        GetUsers:  (prev, { mutationResult: { data } }) => {...}
     }

```

**Comment by headonkeyboard** [comment]
You need to subscribe to your mutation call (like you would do on queries). Subscription will fire the mutation :).

**Comment by kamilkisiela** [comment]
@raysuelzer Could you create a reproduction?

For example, using this https://stackblitz.com/edit/simple-apollo-angular-example or by creating a unit test.
