### ISSUE TITLE
How to set Apollo client within testing module - 1.0.0-beta.0

### ISSUE THREAD

**Issue by dustin-cooler** [apollographql/apollo-angular#394]
Given something like the following:

```
beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [
        ApolloModule
      ],
      providers: [
        ServiceThatUsesApollo
      ],
      declarations: [
        MyComponent
      ]
    });
  }));
```
how do I set the client on the injected Apollo instance so that it's available to providers?

I tried writing a custom module that imports ApolloModule and then sets the client as described in the Initialization section of the [migration doc](https://github.com/apollographql/apollo-angular/blob/1.0.0-beta.0/Migration.md), and then importing the custom module instead of importing ApolloModule directly, but with either approach, when I run the tests I get 'Error: Client has not been defined yet' coming from Apollo when called from within the provider 'ServiceThatUsesApollo'.

**Comment by patricknazar** [comment]
I was just running into this. I've given mocking the Apollo injectable a try. Seems like a good idea, seeing as I'm testing a component's behavior against different expected values to be returned by apollo queries. For example, if a login component successfully displayed an error message when the server failed to respond, or if it gave the success message upon success. Depends on what you are testing.

**Comment by dustin-cooler** [comment]
@patricknazar That's what I ended up doing as well, but it used to be possible to mock the network interface so that unit tests could use Apollo directly but get mock results

**Comment by kamilkisiela** [comment]
@dustin-cooler To use `Apollo` service you need to create a client, just like in the docs, that chapter [_"Setup and options: Creating a client"_](https://www.apollographql.com/docs/angular/basics/setup.html#creating-client)
