### ISSUE TITLE
Cannot set property 'networkStatus' of undefined Error occurs when fetchMore gets invoked

### ISSUE THREAD

**Issue by pycraft114** [apollographql/apollo-angular#397]
**Intended outcome:**

I'm trying to use fetchMore function that is described at your documentation. link : https://www.apollographql.com/docs/angular/recipes/pagination.html#fetch-more

below is the actual code : 
```
this.fetchQuery = this.apollo.watchQuery<any>({
      query: gql`
          query FetchTrainingData ($projectId: String!, $label: String, $page: Int, $size:Int, $order: OrderType){
              trainingData(projectId: $projectId, label: $label, page: $page, size:$size, order: $order) {
                  sentence
                  labels
                  id
                  updateCount
              }
          }
      `,
      variables: {
        projectId: "",
        page: null,
        label: null,
        order: null,
        size: null
      }
    });

this.fetchQuery.fetchMore({
      variables: {
        projectId: this.projectId,
        label: null,
        page: page,
        size: size,
        order: null
      },
      updateQuery: (prev, { fetchMoreResult }) => {
        if (!fetchMoreResult) { return prev; }
        return Object.assign({}, prev, {
          feed: [...prev.feed, ...fetchMoreResult.feed],
        });
      },
    }).then(res => {
      console.log(res);
    })
```
but when fetchMore gets invoked, "Cannot set property 'networkStatus' of undefined" error occurs.

ps. After the 2.0.0 releases your documentations are very unstable .Inside the example code about usage of fetchMore(above link) there is no such "this.feedObs" property. Maybe you guys meant "this.feedQuery". And also the "forceFetch" property inside watchquery options does not exist in type WatchQueryOptions & TypedVariables<V>.

**Actual outcome:**

<img width="1440" alt="2017-11-10 11 31 03" src="https://user-images.githubusercontent.com/24728657/32640195-c64dc4e0-c60a-11e7-9805-a2af652ced41.png">
<img width="1440" alt="2017-11-10 11 31 27" src="https://user-images.githubusercontent.com/24728657/32640229-f1462e62-c60a-11e7-8bf9-61339332562b.png">

**How to reproduce the issue:**

**Version**
```
"apollo-angular": "1.0.0-beta.2",
    "apollo-angular-link-http": "1.0.0-beta.5",
    "apollo-cache-inmemory": "1.1.0",
    "apollo-client": "^2.0.2",
    "apollo-link-context": "1.0.0"
```

**Comment by kamilkisiela** [comment]
@pycraft114 

In `apollo-angular@1.0` we introduced a different way of watching queries. Let me show you, step by step how it works.

To watch query we stll use `watchQuery()` which `QueryRef` (this is new)

```ts
const ref = this.apollo.watchQuery(...) // QueryRef
```

`QueryRef` has methods like `refetch()`, `fetchMore()` and others.

```ts
ref.refetch({variables: foo: 'new'});
```

So where is an `Observable` that we could subscribe to?

```ts
ref.valueChanges.subscribe(...)
```

It's a pure RxJS Observable, previously it was a custom Observable that contained Apollo specific methods, for example `refetch()`. 

Thanks to that change it's way less buggy and it fully works with RxJS and also in TypeScript without any Type Errors.

**Comment by kamilkisiela** [comment]
You can read more about the migration process in the documentation.
