### ISSUE TITLE
pollInterval keeps NgZone occupied and hangs e2e tests

### ISSUE THREAD

**Issue by gviligvili** [apollographql/apollo-angular#406]
I use protractor to test my project.
If setTimeout / setInterval is used the ngZone is occupied, and the app won't stablize therefore the protractor will throw Timeout Error accours :
Timed out waiting for asynchronous Angular tasks to finish after 11 seconds.

When I use pollInterval option, protractor keep throwing this error.
when I remove pollInterval, e2e tests runs perfectly fine.

Intended outcome:
pollInterval should not occupie ngzone and e2e tests should run.

Actual outcome:
pollInterval holds ngZone and protractor fails to start.
(I don't want to use the "don't wait for angular" flag).

How to reproduce the issue:
Use watchQuery with pollInterval option and try to run protractor.

Version

apollo-client@1.9.1
apollo-angular@0.13.0
angular 4.

**Comment by kamilkisiela** [comment]
@gviligvili You could create an ApolloLink that catches operations that contains `pollInterval` option and just execute them once or something.
