### ISSUE TITLE
Use a decorator to set metadata and a service to manipulate them inside a component

### ISSUE THREAD

**Issue by kamilkisiela** [apollographql/apollo-angular#41]
An issue to keep track of `decorator  + service` thing in one place.

Related to #22 #26 and #37 

---
- [x] use service to manipulate queries and mutations
- [x] set metadata with queries and mutations
- [x] use defaultClient

---

I'm going to put here my thoughts and plans for the future API change.

**Comment by Urigo** [comment]
Also waiting for [this](https://github.com/angular/angular-cli/issues/2799) issue of Angular

**Comment by matthewerwin** [comment]
@kamilkisiela what's the status on this one? Looks like an issue was resolved on Angular-cli referenced by @Urigo and all other roadblocks out of the way -- saw that #165 review was never merged.
