### ISSUE TITLE
Why doesn't .query() return a Promise?

### ISSUE THREAD

**Issue by kroeder** [apollographql/apollo-angular#412]
I've asked this here https://github.com/apollographql/apollo-client/issues/2561#event-1343477916 and I was told that apollo-client itself returns a promise on `.query()` - why doesn't apollo-angular do the same as apollo-client?

Here's the question I asked in the apollo-client repo:

Just wanted to ask for the reasen why .query() does not return a Promise

I always end up calling .toPromise() because I don't want to unsubscribe something that is executed once anyway.

And if there's a good reason for it, does this mean, calling toPromise() is bad practice?

**Comment by kamilkisiela** [comment]
You don't have to unsubscribe, it completes immediately after it receives the result.

We tried to make the experience the same as with any Angular service so everything is an Observable , just like in Angular's `HttpClient`.

**Comment by kroeder** [comment]
Good to know - thanks. Not really sure when to unsubscribe an observable and when I don't have to, though. :/ It feels like there isn't any way except guessing or having a documentation that tells me how to handle the observable? Anyway, not something that need's to be discussed here.

**Comment by kroeder** [comment]
PS: This prevents the use of `async / await` If I am correct. Only allowed in Promises ... Really feels odd to me

**Comment by kamilkisiela** [comment]
It's angular integration, it means there are Observable that can be chained. The whole ecosystem is built on Observables instead of Promises.

**Comment by justinmchase** [comment]
Instead of calling `.subscribe()` you can just call `.toPromise()` and then it works as expected.
