### ISSUE TITLE
Parameter of the `from` function should be an array

### ISSUE THREAD

**Issue by nlko** [apollographql/apollo-angular#414]
Hi, the [middleware documentation](https://www.apollographql.com/docs/angular/basics/network-layer.html#linkMiddleware) says :
```
    apollo.create({
      link: from(authMiddleware, otherMiddleware, http),
    });
```
I think it should rather be `from([authMiddleware, otherMiddleware, http]),` since the `from` signature is `export const from = (links: ApolloLink[]): ApolloLink => {…};`

Correct ?

**Comment by b-barry** [comment]
PR #433 fix it
