### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by nlko** [apollographql/apollo-angular#415]
Hello, 

Here are some broken links I found in the documentation.

In [why](https://www.apollographql.com/docs/angular/index.html#) :
- `all the popular frontend frameworks` 
- `Other JavaScript + native platforms`: all the javascript section is broken

The migration guide link in the menu doesn't work.

In [setup](https://www.apollographql.com/docs/angular/basics/setup.html)
- `For more infomation read the cache docs`
- `This argument allows the Apollo Client Devtools`

In [mutations](https://www.apollographql.com/docs/angular/basics/mutations.html): most of the links are broken

In [graphql over ws](https://www.apollographql.com/docs/angular/basics/network-layer.html#websocket): the in depth link is broken

The link in the menu to the `Apollo cache` page doesn't work.

**Comment by mafalarz** [comment]
In Angular:
Migration guide
Webpack
Webpack fragments
...etc

**Comment by kamilkisiela** [comment]
Could you guys help with that or at least some of them?

**Comment by nlko** [comment]
I'm sorry @kamilkisiela I would have already done a pull request if I hadn't to sign the Meteor Contributor Agreement for that.

**Comment by b-barry** [comment]
I went through all the docs and fixed all broken links.
If you find new one, just ping me
