### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by mafalarz** [apollographql/apollo-angular#417]
In the docs there are errors:
https://www.apollographql.com/docs/angular/basics/queries.html :
![image](https://user-images.githubusercontent.com/30442378/32894884-30f12dc8-caac-11e7-89df-330e009a9864.png)
Missing something in import { Apollo } from ' -angular';

**Comment by jlovison** [comment]
Another area for documentation errors: [Apollo Link > Afterware](https://www.apollographql.com/docs/angular/basics/network-layer.html#linkAfterware)

    const logoutLink = onError(({ networkError }) => {
          if (networkError.statusCode === 401) auth.logout();
        });
    
        apollo.creat({
          link: logoutLink.concat(httpLink),
        });

So a number of things wrong here:

* `onError` passes a type of `Error` which does not have a `statusCode` attribute
* `apollo.creat` is obviously a typo
* `httpLink` is the name of the injected service, not the name of the variable containing the new `httpLink.create` instance (which is `http`)

`apollo-link` has much clearer afterware documentation for this example:

    const httpLink = createHttpLink({ uri: '/graphql' });
    const errorLink = onError(({ networkError }) => {
      if (networkError.status === 401) {
        logout();
      }
    })
    
    // use with apollo-client
    const link = errorLink.concat(httpLink);

**Comment by b-barry** [comment]
@mafalarz PR #431 fix the issue
@jlovison Apollo link doc was updated, they don't use anymore `status` but `statusCode` see [ResponseError interface](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L10). However, I saw an open issue regarding [HttpLink error object](apollographql/apollo-link#218). PR #432
