### ISSUE TITLE
Not compatible with strict null checks

### ISSUE THREAD

**Issue by sandangel** [apollographql/apollo-angular#418]
Basic setup can not be complete when strictNullCheck is turn on.

Argument of type '{ link: HttpLinkHandler; cache: InMemoryCache; }' is not assignable to parameter of type 'ApolloClientOptions<NormalizedCacheObject>'.
  Types of property 'cache' are incompatible.
    Type 'InMemoryCache' is not assignable to type 'ApolloCache<NormalizedCacheObject>'.
      Types of property 'read' are incompatible.
        Type '<T>(query: ReadOptions) => T | null' is not assignable to type '<T>(query: ReadOptions) => T'.
          Type 'T | null' is not assignable to type 'T'.
            Type 'null' is not assignable to type 'T'.

apollo-angular v1.0.0 angular 5.0.2

**Comment by kamilkisiela** [comment]
It's not related to `apollo-angular` but to `apollo-cache-inmemory`. Known issue, there will be soon a fix for that apollographql/apollo-client#2592.
