### ISSUE TITLE
Network Error: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by abubakkarbutt** [apollographql/apollo-angular#448]
## Package Versions
-  @angular : 5.1.0,
-  "apollo-angular": "^1.0.0",
-  "apollo-angular-link-http": "^1.0.1",
-   "apollo-cache-inmemory": "^1.1.3",
-   "apollo-client": "^2.1.0",
-   "apollo-link": "^1.0.5",
-   "apollo-link-context": "^1.0.2",
-   "apollo-link-error": "^1.0.2",
-   "apollo-link-ws": "^1.0.2",
-   "apollo-utilities": "^1.0.3",
### TypeError: Cannot read property 'length' of null
-    at HttpHeaders.applyUpdate (http.js:322)
-    at eval (http.js:269)
-    at Array.forEach (<anonymous>)
-    at HttpHeaders.init (http.js:269)
-    at HttpHeaders.forEach (http.js:368)
-    at Observable.eval [as _subscribe] (http.js:2172)
-    at Observable._trySubscribe (Observable.js:172)
-    at Observable.subscribe (Observable.js:160)
-    at subscribeToResult (subscribeToResult.js:23)
-    at MergeMapSubscriber._innerSub (mergeMap.js:138)
## Apollo Setup
```javascript
  // http and ws endpoints configuration
  const HTTP_GQL_ENDPOINT = '/xyz';
  let WS_GQL_ENDPOINT = 'ws://localhost:8088/subscriptions';
  // Http configurations
  const http = http_link.create({uri: HTTP_GQL_ENDPOINT});
  // Websocket configuration
  const ws = new WebSocketLink({
    uri: WS_GQL_ENDPOINT,
    options: {
      reconnect: true,
      connectionParams: {
        authToken: localStorage.getItem('vital_token') || null
      }
    }
  });

  // Add authentication middleware to add jwt token to http header
  const auth_middleware = new ApolloLink((operation, forward) => {
    // add the authorization to the headers
    operation.setContext({
      headers: new HttpHeaders().set('Authorization', localStorage.getItem('vital_token') || null)
    });
    console.log(operation.operationName);
    return forward(operation);
  });

  const http_with_middleware = concat(auth_middleware, http);

  // Handle network and graphql errors
  const error = onError(({ networkError, graphQLErrors }) => {
    if (graphQLErrors) {
      graphQLErrors.map(({ message, locations, path }) => {
        logger(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`)
      });
    }
    if (networkError) { logger(`[Network error]: ${networkError}`) }
  });

  // create hybrid link of http client and websocket
  const link = ApolloLink.split(
    // split based on operation type
    ({ query }) => {
      const { kind, operation } = getMainDefinition(query);
      return kind === 'OperationDefinition' && operation === 'subscription';
    },
    ws,
    error.concat(http_with_middleware),
  );

  // create apollo client
  apollo.create({
    link: link,
    cache: new InMemoryCache({
      dataIdFromObject: (obj: any) => obj._id
    })
  });
```

**Comment by picosam** [comment]
Did you try to change `authToken: localStorage.getItem('vital_token') || null` to `authToken: localStorage.getItem('vital_token') || ''`?

**Comment by abubakkarbutt** [comment]
No, why would it be the cause of error?

**Comment by picosam** [comment]
(Sorry, I updated my comment after referring to the correct line.)
To answer your question, I think here's is the culprit: https://github.com/angular/angular/blob/master/packages/common/http/src/headers.ts#L176

**Comment by abubakkarbutt** [comment]
Yes it did fixed the error. Thank you so much for your help.
