### ISSUE TITLE
Observable/Promised based subscribeToMore for reacting to updates

### ISSUE THREAD

**Issue by intellix** [apollographql/apollo-angular#450]
I'm taking an initial result set from a query and subscribing to more. When new data comes in, I need to first push it through some animation before adding it to a list of results for the user to see.

Results: [0, 1, 2]
New Result: 3...... animate for a couple of seconds
Results: [0, 1, 2, 3]

Having subscribeToMore return a Promise or be an Observable chain would make this really easy cause I think it would be as easy as `delay(1000)` or `setTimeout(() => resolve(mergedData), 1000)`

Right now to delay new results it looks something like:

```ts
queryRef: QueryRef<Things> = this.apollo.watchQuery<Things>({ query });

thing$ = new Subject<Thing>();

things$: Observable<any> = mergeStatic(
  this.thing$.pipe(delay(1000)),
  this.queryRef.valueChanges.pipe(
    map(({ data }) => data.things.edges.map(edge => edge.node)),
    mergeAll(),
  ),
).pipe(
  scan((acc, node) => [...acc, node], []),
);

this.queryRef.subscribeToMore({
  document,
  updateQuery: (prev: any, { subscriptionData }) => {
    if (!subscriptionData.data) {
      return prev;
    }

    this.animate = true;
    this.thing$.next(subscriptionData.data.createThing);

    return prev;
  },
});
```

**Comment by kamilkisiela** [comment]
@intellix maybe `Apollo.subscribe(...)` + QueryRef.updateQuery(...)` are what you need?

**Comment by intellix** [comment]
Ahah, I didn't know about the subscribe method :) Documentation only referenced subscribeToMore so missed that one: https://github.com/apollographql/apollo-client/issues/2719#issuecomment-351504883

**Comment by kamilkisiela** [comment]
Pretty much every time I mention `.subscribe()` people are surprised. I'll cover that in angular docs soon.
