### ISSUE TITLE
Mutation call api twice

### ISSUE THREAD

**Issue by Vi-dot** [apollographql/apollo-angular#451]
Hello,

Since I updated my application dependencies to last version : 
```
@angular/... : ^5.0.0
apollo-angular: 1.0.0
apollo-client: 2.0.4
apollo-cache-inmemory: 1.1.4
apollo-angular-link-http: 1.0.1
```

I have a bug with `mutate()` function. One function execution make two calls to api. I saw api calls in network debuger. Then I'm sure about number of function execution with simple console prints (once a time).

```typescript
    console.log('mutate...') // printed only once

    let observable : Observable<FetchResult> = this.apollo.mutate({
      mutation: this.updateReq,
      variables: {
        id: id
        key: key,
        value: value
      }
    });

    observable.subscribe(({data}) => {
      console.log('Mutation results', data); // printed only once
    },(error) => {
    });
```

I tried with Firefox 5.7 and Chromium 63, and get the bug any way.

It's a big problem, because in my server side, when mutation is called, some inserts are performed. Then in database everything is doubled.

**Comment by kamilkisiela** [comment]
@Vi-dot Are you sure there are two exact same requests? One is probably `OPTIONS` (method) and second is `POST` and that's how it should be.

**Comment by Vi-dot** [comment]
@kamilkisiela Yes, it's exactly the same requests, with the same http header, query and variables as below : 
```json
{
	"operationName":"_",
	"variables":
	{
		"ids": ["3452"],
		"key": "object.validated",
		"value": false
	},
	"query": "mutation _($ids: [String]!, $key: String!, $value: String!) {\n  updateMentions(ids: $ids, key: $key, value: $value) {\n    id\n    doi\n    raw\n    validation\n    source\n    position_tag\n    bounding_boxes {\n      id\n      p\n      x\n      y\n      w\n      h\n      __typename\n    }\n    object_link {\n      id\n      object {\n        id\n        identifier\n        main_identifier\n        exists\n        commands {\n          id\n          command\n          __typename\n        }\n        attributes\n        __typename\n      }\n      validated\n      __typename\n    }\n    __typename\n  }\n}\n"
}
```

I wonder if it's because the graphql lib of server I'm using is a bit old. I'm using graphql-java 2.4, and now graphql-java is in version 6.0. But it shouldn't be because the calls come from client part.

**Comment by Vi-dot** [comment]
I fixed it, it's because I subscribe twice to the observer returned by `mutate()` function.
Strange, because before it was allowed.
The function mutate should make a recall, not a subscription to its observer.

**Comment by kamilkisiela** [comment]
@Vi-dot I don't agree. Where you're using `HttpClient`, it will do an action after you subscribe to it. Since it's a standard Observable, you can share it the same way as you normally do in Angular.
