### ISSUE TITLE
Why have you removed ApolloModule.forRoot()?

### ISSUE THREAD

**Issue by blissi** [apollographql/apollo-angular#454]
This makes problems with instantiation order:
I've got a service that makes a query in the constructor. The ApolloClient hasn't been created at this time, though.

**Comment by blissi** [comment]
Next problem:
I tried to use the select-pipe in a feature module. It says "The pipe 'select' could not be found..." Therefore I tried to add "ApolloModule" to the imports-section. Then I get the error "Error: Client has not been defined yet" when accessing the page on the feature module.

**Comment by kroeder** [comment]
If you need apollo before everything else you can do this by using the angular APP_INITIALIZER token
```typescript
@NgModule({
    imports: [
        ApolloModule,
        // [...]
    ],
    declarations: [
        // [...]
    ],
    providers: [
        // Taken from here https://gist.github.com/fernandohu/122e88c3bcd210bbe41c608c36306db9
        {
            provide: APP_INITIALIZER, useFactory: onStartup, deps: [
                Apollo,
                AnyService
            ], multi: true
        }
    ],
    bootstrap: [AppComponent]
})
export class AppModule {
}

export function onStartup(apollo: Apollo, anyService: AnyService) {
    return () => {
        // do something here
    };
}
```
See this https://gist.github.com/fernandohu/122e88c3bcd210bbe41c608c36306db9

Hope this helps!

**Comment by blissi** [comment]
Thanks, I'll give it a try!

**Comment by kamilkisiela** [comment]
#460 will fix it.

@blissi 

> Error: Client has not been defined yet

It says there is no ApolloClient created. It's done with `Apollo.create({ options })`. You can check out the Setup chapter in docs.

There are two cases when it might happen:
- `Apollo.create()` hasn't been used at all
- On of `Apollo` service's methods has been used before `Apollo.create()` happend

**Comment by jdeanwaite** [comment]
@blissi Did you resolve the issue with importing `ApolloModule` in your feature module in order to access the `SelectPipe`? We are doing a similar thing, trying to import the `ApolloModule` into a feature module that is lazy loaded, but getting the error you saw.

**Comment by blissi** [comment]
@jdeanwaite  I set up an APP_INITIALIZER as @kroeder  suggested.
