### ISSUE TITLE
Is there way to get response headers?

### ISSUE THREAD

**Issue by agborkowski** [apollographql/apollo-angular#459]
im using code similar like 

https://github.com/benawad/slack-clone-client/blob/31_fix_auto_refresh_of_jwt_tokens/src/apollo.js#L18

but with apollo-angular-link-http afterWare 

```js
const { response: { headers } } = operation.getContext();
```
inside map and operation.getContext(); there is only object with requested `headers` `cache` and body content,  how to get response headers ?

## R&D update

i didn't find solution to access to response headers in `apollo-angular-link-http`. I solved problem by replace to native `apollo-link-http` link, after that operation.getContext() started expose response headers

be ensure to add headers `Access-Control-Expose-Headers` on servers side when u use express server.

**Comment by kamilkisiela** [comment]
#476 should fix it.

It behaves exactly like in `apollo-link-http`. How you like it?
