### ISSUE TITLE
watchQuery variables member as a Rxjs Subject not working

### ISSUE THREAD

**Issue by ThinkontrolSY** [apollographql/apollo-angular#464]
This problem occurred after upgraded to apollo-angular 1.0.1

when I use watchQuery, the type of variables' member is a Subject\<any\>, and I just next a new value to this variable member to update data.

```typescript
filter: Subject<any> = new Subject();
GQL = gql`
query something(
  $filter: Filter,
) {
  Something(filter: $filter) {
    totalCount
  }
}
`
apolloClient.watchQuery({
      query: GQL,
      variables: {
        filter: this.filter
      }
    }).subscribe(val => {
      console.log(val)
    });
```

But I found this feature is no longer work in apollo-angular 1.0.1

Is the feature disabled or the usages changed ?

Thanks

**Comment by picosam** [comment]
Is this related to #425?

**Comment by ThinkontrolSY** [comment]
Yes, Thanks to @picosam

**Comment by kamilkisiela** [comment]
Closing in favor of #425
