### ISSUE TITLE
support graphql@0.12?

### ISSUE THREAD

**Issue by amitport** [apollographql/apollo-angular#467]
when installing graphql@0.12.3 I am getting a warning: 
`npm WARN apollo-angular-link-http@1.0.1 requires a peer of graphql@^0.11.2 but none was installed.`

I am not seeing any actual regression though. Does this lib support `graphql@0.12`? If so, can the peer dependency be updated?

Thank you

**Comment by kamilkisiela** [comment]
#472 should close it. You can use `apollo-angular-link-http@1.0.2-beta.0`.
