### ISSUE TITLE
WatchQuery dispose leaking

### ISSUE THREAD

**Issue by stephenlautier** [apollographql/apollo-angular#469]
When using the `.watchQuery`, is there a way to dispose it?
Not sure if its a bug or I'm misusing it, but it seems to be leaking without somehow disposing it.

I followed the [documentation](https://www.apollographql.com/docs/angular/basics/queries.html) but all the usages doesnt have any dispose, I also unsubscribe from the `.valueChanges.subscribe` but it's still alive.

This is what I'm doing:
- Register WatchQuery
  - On page init
  - Invoke watchQuery
  - Add log
  - subscribe to `.valueChanges`
- Change page
  - On page destroy
  - Unsubscribe to `valueChanges` subscription
- Revisit page with watchQuery
- Reset Store (via `getClient().resetStore()`)
- Log gets called x2 instead (increasing for every page switch)

![image](https://user-images.githubusercontent.com/3908723/35343979-3f8f1c1c-012c-11e8-817b-7a2a63cb6a99.png)

If you would like to see how I'm using it exactly you can do so on https://github.com/sketch7/angular-skeleton-app/blob/feature/odin-gql/src/app/areas/heroes/heroes.component.ts#L30
Unfortunately on that branch, with the API you cannot just run it.
_p.s. I also tried to put everything in the UI for the sake of it, but same issue_

**Comment by kamilkisiela** [comment]
I failed to reproduce by simply using `Apollo` service inside a component.

https://stackblitz.com/edit/apollo-angular-469

Apollo Dev Tools shows one watched query and I get only one log.

**Comment by stephenlautier** [comment]
@kamilkisiela in that it seems its works fine, I will try to use that API in my repo and see if it works properly or not.

**Comment by kamilkisiela** [comment]
@stephenlautier How it works? Maybe you could prepare a small reproduction of it?

**Comment by stephenlautier** [comment]
yes i will try replicate what you had in mine, and ill update you

**Comment by stephenlautier** [comment]
Just an update, so far I've changed my implementation to simply use the gql api you used, and did some changes to comment out some private lib we have... and its working fine now.

I can give last shot again at work exactly how it was, and maybe reinstall node modules and see if it happens agian.. but i had tested this several times and it was reproducible 100% - if i didnt had the screenshot I would think I was hallucinating =(

**Comment by intellix** [comment]
think I'm seeing something similar locally to be honest. Not sure if it's related entirely but I have the following:

```ts
private gamesQueryRef = this.apollo.watchQuery({ query, variables });

games$: Observable<any> = this.gamesQueryRef.valueChanges.pipe(
  map(({ data }) => data.games.edges.map(edge => edge.node)),
  shareReplay(1),
);

countdown$ = this.games$.pipe(
  map(games => new Date(games[0].scheduledAt)),
  share(),
);

ngOnInit() {
  this.subscriptions.add(this.games$.pipe(take(1)).subscribe(console.log));
  this.subscribeToMore();
}

ngOnDestroy() {
  this.subscriptions.unsubscribe();
}

subscribeToMore() {
  this.gamesQueryRef.subscribeToMore({ document, updateQuery: (prev: any, { subscriptionData }) => { ... });
}
```

With the `shareReplay(1)` and `subscribeToMore`, leaving the page doesn't stop the subscription. With `share()` it does but then coming back with instant cache causes `countdown$` to miss the emit. There's no view and the `ngOnDestroy` is definitely run so I'd say that apollo-angular or apollo-client isn't able to clean up the subscribeToMore for some reason.

It's getting late but I'll try to create a reproduction over the weekend outside of my codebase

**Comment by intellix** [comment]
Actually, found something else that is weird:

```ts
export class GameComponent {
  private gamesQueryRef = this.apollo.watchQuery({ query });

  constructor(private apollo: Apollo) {
    this.subscribeToMore();
  }

  subscribeToMore() {
    this.gamesQueryRef.subscribeToMore({ document, updateQuery: prev => prev });
  }
}
```

If you never subscribe to the valueChanges and run a subscribeToMore and switch pages, it'll throw an Error in console that a particular ObservableQuery id doesn't exist:

![screenshot 2018-03-03 11 26 54](https://user-images.githubusercontent.com/1162531/36933268-509f43ca-1ed6-11e8-87dc-5af8b5864414.png)

**Comment by ntziolis** [comment]
Seeing the same behaviour still, anybody figured out a way to stop the leaking?

**Comment by intellix** [comment]
My issue in particular was probably shareReplay not unsubscribing: https://github.com/ReactiveX/rxjs/issues/3336

**Comment by kamilkisiela** [comment]
Is this still an issue?

**Comment by stephenlautier** [comment]
@kamilkisiela doest seems like it, I will close it, if anyone has the same issue will reopen if needed

**Comment by gituser3000** [comment]
2.6.0 shareReplay(1) causes leaking

**Comment by gituser3000** [comment]
shareReplay(1) causes leaks, but as far as i understand it should not (using destroy subjects\ async pipe) .
shareReplay({refCount: true) fixes this, but this solution may not be always acceptable
