### ISSUE TITLE
this.apollo.subscribe works (even for inserts), but .query and .watchQuery don't work so well

### ISSUE THREAD

**Issue by tjme** [apollographql/apollo-angular#474]
I have a [repo](https://github.com/tjme/angular-io-example-graphql/) with a working re-implementation of the Angular Tour of Heroes tutorial, but using Apollo-Angular to link via GraphQL (and [PostGraphile)](https://github.com/postgraphql/postgraphql/) to a PostgreSQL database. It now seems to work well, but I expected to use apollo.query or apollo.watchQuery (with .valueChanges) to fetch all the Heroes as an Observable (at [src/app/hero.service.ts line 40](https://github.com/tjme/angular-io-example-graphql/blob/master/src/app/hero.service.ts#L40)), and although either mostly work, they don't update when new Heroes are inserted, unless a Hero is first deleted!

Strangely (from my understanding of the documentation), using apollo.subscribe seems to be working fine, but I don't think it's as intended!

Is this a bug, or am I misunderstanding?

**Comment by kamilkisiela** [comment]
Could you create a small isolated reproduction? Here it works: [simple-apollo-angular-example.stackblitz.io](simple-apollo-angular-example.stackblitz.io).
