### ISSUE TITLE
QueryOptions is not availabe in Apollo Link

### ISSUE THREAD

**Issue by gviligvili** [apollographql/apollo-angular#475]
I have multiple polling requests. and a bit of regular queries.

I try to add to each polling request an header :  "isPolling: true"
But I can't seem to reach the query options in Apollo Link middleware.

is there a way to see which options where given to a query?

**Comment by kamilkisiela** [comment]
@gviligvili If you're using `apollo-angular-link-http`, then [check out this](https://github.com/apollographql/apollo-angular/tree/master/packages/apollo-angular-link-http#options).

**Comment by gviligvili** [comment]
Yeah, but the thing is I don't want to add things to each polling request this head manually.
I can't relay that everyone in our section at work would attach the header to a poll request.

the thing I want to do is :  
In apollo link middleware  , check if the operation as a "pollInteval" property, if so, attach an header.
but I can't reach pollInterval, because QueryOptions isn't attached to operation as far as I know.

**Comment by kamilkisiela** [comment]
It's by design and it's related to ApolloLink, not Angular Apollo
