### ISSUE TITLE
middleware migration issue

### ISSUE THREAD

**Issue by hschaeidt** [apollographql/apollo-angular#478]
I've got a small issue during the apollo-client migration from 1.x to 2.x in the middleware part. I am currently using a middleware that injects the authorization header for the graphql backend. in 1.x it was easy to setup a async storage during the middleware setup, due to the manual call of the callack function `next`.

The 1.x code in question resides here: https://github.com/hschaeidt/hitori/blob/8838060dc97beb59477ea704ddfc79eb274b8d20/src/providers/apollo/apollo.ts

Is there any advise/good practice of how to achieve a similar setup by upgrading to the 2.x version?

My current thought was: https://github.com/hschaeidt/hitori/blob/633282e770e4e601d7daa811986b07d8736f31d9/src/app/apollo.config.ts

However the promise resolves after the client has been set up and the authorization header will not be set.

Looking forward a small hint :)

**Comment by kamilkisiela** [comment]
You can put that promise inside `setContext` function. `apollo-link-context` supports asynchronous functions which solves your issue :)

**Comment by kamilkisiela** [comment]
You could also create your own link. I think I might write something about creating a custom link so people will get to understand that.

**Comment by hschaeidt** [comment]
Thanks for pointing that out. The documentation of `apollo-link-context` shows exactly what I need. Do you mean by custom link, what is described as 'Stateful Link' in the [docs](https://www.apollographql.com/docs/link/stateful.html)?

In fact this might be a good solution for this use-case. Or a Stateless link with [caching](https://www.apollographql.com/docs/link/links/context.html#caching-async).
