### ISSUE TITLE
IE11 Error: "Network error: Object doesn't support this action"

### ISSUE THREAD

**Issue by chenkie** [apollographql/apollo-angular#481]
I'm having trouble with IE11 and can't seem to find other reports of the same error message being encountered before.

I'm using the Angular CLI and when loading in IE11 I get the following:

<img width="505" alt="screen shot 2018-02-09 at 2 59 03 pm" src="https://user-images.githubusercontent.com/1847678/36047349-d71e7d64-0da9-11e8-95b7-bbaec1412e47.png">

* Angular CLI v1.6.0
* Angular v5.1.0
* Apollo Angular v1.0.1
* Apollo Client v2.0.3

I've added just about every polyfill I can think of and nothing seems to be doing the trick. Any tips would be greatly appreciated!

**Comment by kamilkisiela** [comment]
Could you create a reproduction? This way I could tell more.

**Comment by chenkie** [comment]
Shoot, I meant to update and close this. The issue was caused by another library (ironically, one that I'm the author of) and reliance on the browser's URL interface. Polyfilling that did the trick.

Thanks!
