### ISSUE TITLE
Batched Queries & Mutations

### ISSUE THREAD

**Issue by jafaircl** [apollographql/apollo-angular#487]
How can we batch queries/mutations? The only issue I could find was for a 1.x version and the docs point to a page that doesn't exist: https://github.com/apollographql/apollo-angular/blob/99e73a5054bfcb81cc4d2c56648b956ec3e2d681/docs/link/links/batch-http.html

When I try to use BatchHttpLink from 'apollo-link-batch-http' it throws the following error:

Argument of type '{ link: BatchHttpLink; cache: InMemoryCache; queryDeduplication: boolean; defaultOptions: { watch...' is not assignable to parameter of type 'ApolloClientOptions<NormalizedCacheObject>'.
  Types of property 'link' are incompatible.
    Type 'BatchHttpLink' is not assignable to type 'ApolloLink'.
      Types of property 'split' are incompatible.
        Type '(test: (op: Operation) => boolean, left: ApolloLink | RequestHandler, right?: ApolloLink | Reques...' is not assignable to type '(test: (op: Operation) => boolean, left: ApolloLink | RequestHandler, right?: ApolloLink | Reques...'. Two different types with this name exist, but they are unrelated.
           Types of parameters 'left' and 'left' are incompatible.
            Type 'ApolloLink | RequestHandler' is not assignable to type 'ApolloLink | RequestHandler'. Two different types with this name exist, but they are unrelated.
              Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.
                Type 'ApolloLink' is not assignable to type 'RequestHandler'.
                  Type 'ApolloLink' provides no match for the signature '(operation: Operation, forward?: NextLink): Observable<any>'.

Is there a way to do this currently or is it on the roadmap? Thanks.

Edit: Added the right error message.

**Comment by kamilkisiela** [comment]
It's not possible right not but I started to work on it.

**Comment by Charius** [comment]
It'l be great to have this feature available

**Comment by kamilkisiela** [comment]
You can now use #495

`apollo-angular-link-http-batch`
