### ISSUE TITLE
Unsubscribing to an ObservableQuery containing ShareReplay doesn't teardown

### ISSUE THREAD

**Issue by intellix** [apollographql/apollo-angular#494]
So I've been debugging some issues caused by WebSocket subscriptions not being stopped. 

Entering/Leaving a page causes them to pile up and I've found that the issue is caused by a `shareReplay(1)` preventing the ObservableQuery from calling it's unsubscribe function. On top of that, I've found that you need to manually clean up subscribeToMore if you don't subscribe to valueChanges.

Consider this component:
```ts
@Component(...)
export class GameComponent implements OnDestroy {

  private subscriptions = new Subscription();
  private queryRef = this.apollo.watchQuery({ query });

  games$ = this.queryRef.valueChanges.pipe(
    shareReplay(1),
    finalize(() => console.log('finalize')),
  );

  constructor(private apollo: Apollo) {
    this.subscriptions.add(this.games$.subscribe(console.log));
    this.queryRef.subscribeToMore({ document, updateQuery: prev => prev });
  }

  ngOnDestroy() {
    this.subscriptions.unsubscribe();
  }
}
```

1) enter the page, it'll fetch data, subscribeToMore on the websocket
2) leave the page, the subscription is unsubscribed from, finalize() is called but the websocket never sends stop

Replace the `shareReplay(1)` with `share()` and it'll correctly send STOP to the websocket but then this has other implications like fetching from cache being instant causing late subscribers to now miss the emit.

Also, I guess another thing I found is that if you never subscribe to valueChanges but subscribeToMore and leave the page, it'll throw an Error later in console:
![screenshot 2018-03-03 11 26 54](https://user-images.githubusercontent.com/1162531/36934290-4f42c2d4-1ee7-11e8-97d4-e391d96e86ca.png)

Could be related to #469 

**Temporary workaround**: enforce an unsubscription from the subscribeToMore within ngOnDestroy:
```ts
this.subscriptions.add(
  this.gamesQueryRef.subscribeToMore({ document, updateQuery: prev => prev }),
);
```

**Comment by kamilkisiela** [comment]
@intellix hi, is it still a thing or bug/expected behaviour of shareReplay operator?

**Comment by intellix** [comment]
Latest configurable with shareReplay from rxjs solves this I guess
