### ISSUE TITLE
Feature: Apollo Link Persisted Queries

### ISSUE THREAD

**Issue by intellix** [apollographql/apollo-angular#496]
Having just implemented Apollo Engine, the automatic persisted queries sounded pretty cool.
Tried to implement the standard one: https://github.com/apollographql/apollo-link-persisted-queries but had a few issues with the types. After hacking away all the types with <any> I found that nothing really happened on the client and am guessing something custom needs implementing for it to work with HttpClient.

Tried this, which adds the persistedQuery extension but when it's not found, it doesn't send a request to add it:
```
const http = concat(createPersistedQueryLink() as any, httpLink.create({
  uri,
  method: 'POST',
  withCredentials: true,
  includeQuery: false,
  includeExtensions: true,
}));
```

#### Happy Path

1) Client sends query signature with no query field
2) Server looks up query based on hash, if found, it resolves the data
3) Client receives data and completes request
4) Missing hash path

#### Client sends query signature with no query field

1) Server looks up query based on hash, none is found
2) Server responds with NotFound error response
3) Client sends both hash and query string to Server
4) Server fulfills response and saves query string + hash for future lookup
5) Client receives data and completes request

**Comment by kamilkisiela** [comment]
@intellix I think this issue is now resolved with https://github.com/apollographql/apollo-angular/tree/master/packages/apollo-angular-link-persisted

**Comment by intellix** [comment]
Was just checking the latest version and seems this comment is still relevant: https://github.com/apollographql/apollo-angular/pull/509#issuecomment-377699656

The server returns that the `PersistedQueryNotFound` but never makes the second call to add it

**Comment by kamilkisiela** [comment]
I created a reproduction here
https://github.com/kamilkisiela/apollo-angular-persisted-queries-demo

Seems like it works

**Comment by intellix** [comment]
Thanks for your demo, just tested it and it looks to all be working perfectly. I'll look deeper into why mine doesn't work and guessing it's something else in my setup :)
