### ISSUE TITLE
toPromise() on watchQuery.valueChanges doesn't resolve (or how to await a watchQuery)

### ISSUE THREAD

**Issue by simonhaenisch** [apollographql/apollo-angular#498]
I've been trying to await a `watchQuery` and had some issues because of lack of documentation...

I realized that because watchQuery is kind of like a stream of observables I need to grab the first observable with `valueChanges.first()` to make `.toPromise()` resolve:

```ts
(async (query) => {

  const res = await this.apollo
    .watchQuery<{ foo: FooType }>({  query })
    .valueChanges
    .first()
    .toPromise();

  const foo = res.data.foo;

})(query);
```

Without adding `.first()` the code still runs but the promise never resolves. I was expecting it to automatically resolve with the first response. Could you remove `.toPromise()` from `watchQuery<T>().valueChanges` to make this more obvious? Or even better, make the promise resolve with the first response 🤓 

Maybe it would also be helpful for others to document this in the ["What is QueryRef"](https://www.apollographql.com/docs/angular/basics/queries.html#queryref) section of the docs?

**Comment by kamilkisiela** [comment]
if you want to fetch data once just use `apollo.query`, watch query is to get notified about new changes so it should be a stream.

**Comment by simonhaenisch** [comment]
ok. from the docs it just seems that `watchQuery` is to be preferred over `query` in general, as it's used in most examples. if the backend doesn't support sending updated data through the same query, should i bother using watchQuery at all (except for refetch maybe)?

**Comment by kamilkisiela** [comment]
It's not like it's preferred. Both are for two different use cases. Your backend has nothing to do with that. Imagine a situation when you have a list of tasks and you add new one. If you use watchQuery then when mutation happens you can add that task to cache, Apollo will update your query and you will see a new task on the list, in your UI. If it would be `query()` your UI wouldn't be updated since it fetches data once and close the observable.

**Comment by simonhaenisch** [comment]
ah ok, thanks for the clarification. wasn't aware that watchQuery would observe local cache changes (:
