### ISSUE TITLE
Support `addTypename: false` as configuration option in apollo-angular as per apollo-client

### ISSUE THREAD

**Issue by lukeify** [apollographql/apollo-angular#499]
Having browsed `apollo-angular` looking for an option to disable `__typename` properties on returned queries, such as the [`addTypename: false` configuration option in `apollo-client`](https://github.com/apollographql/apollo-client/issues/1913#issuecomment-336376513), it appears this has not been implemented here, consider adding it; thanks!

**Comment by kamilkisiela** [comment]
Apollo Angular accepts the same options as apollo-client. It's just the option you mentioned, is no longer a part of apollo-client since versions l 2.0.
