### ISSUE TITLE
Subscription updates does not work

### ISSUE THREAD

**Issue by cyberbeast** [apollographql/apollo-angular#501]
I have a method called fetchComments() in my angular service which sets a variable for my "fetchComments" query to retrieve data. I am also trying to immediately subscribe to the changes on this using the "subscribeToMore" method on the QueryRef object. However, while I am able to retrieve the comments correctly (".valueChanges" works), the subscription's updateQuery does not trigger at all after a new comment is posted. Am I doing something wrong?

```
fetchComments(): Observable<any> {
    this.allCommentsQuery.setVariables({
      id: this.currentParent
    });

    this.allCommentsQuery.subscribeToMore({
      document: NEW_COMMENT_ADDED_SUBSCRIPTION,
      variables: {
        parentId: this.currentParent
      },
      updateQuery: (prev, { subscriptionData }) => {
        if (!subscriptionData.data) {
          return prev;
        }

        const newComment = subscriptionData.data.newCommentCreated;
        console.log('NEW COMMENT', newComment);
        this.store.dispatch(new fromStore.AppendNewComment(newComment));
      }
    });

    return this.allCommentsQuery.valueChanges.pipe(
      catchError((error: any) => Observable.throw(error.json()))
    );
  }
```

What would be the best approach to setting up subscriptions dynamically based on changes to a variable?

**Comment by intellix** [comment]
Weird, never tried dispatching actions from a subscription. Shouldn't you just be returning the new result there inside updateQuery? Also, guessing you console logged inside there. Does it run at all?

**Comment by cyberbeast** [comment]
Hey @intellix ,

This is the same issue we talked about on gitter. It was my fault. 
For others facing a similar issue, use the "Network" tab on the developer console to check for graphql request errors. For me, I was subscribing to an incorrectly named subscription type (typo).
