### ISSUE TITLE
fetchPolicy: 'network-only' being ignored

### ISSUE THREAD

**Issue by ahyos** [apollographql/apollo-angular#503]
I'm trying to use watchQuery with 'netwok-only' fetchPolicy and pollInterval, as a result the following output  
``` shell
Error: Queries that specify the cache-first and cache-only fetchPolicies cannot also be polling queries.
```
``` javascript
let options:any = {
            query: gql `...`,
            fetchPolicy: 'network-only',
        };
        this.feedRef = this.apollo.watchQuery(options);
        console.log('queryRef: ',  this.feedRef)
```
![image](https://user-images.githubusercontent.com/16686506/37559150-48fbbfda-2a21-11e8-9368-ef88afb3d31d.png)

I have even put this mode in the default settings, 
``` javascript
this.apollo.create({
      link: middleware ? errorLink.concat(middleware) : errorLink.concat(this.link),
      cache: this.cache,
      ssrMode: true,
      defaultOptions: {
        watchQuery: {
          fetchPolicy: 'network-only'
        }
      }
    });
```

in the package.json ...
``` json
"apollo-angular": "1.0.1",
    "apollo-angular-link-http": "1.0.2-beta.0",
    "apollo-cache-inmemory": "1.1.11",
    "apollo-cache-persist": "0.1.1",
    "apollo-client": "2.2.7",
    "apollo-client-rxjs": "^0.6.0-rc.2",
    "apollo-link": "1.2.1",
    "apollo-link-context": "1.0.7",
    "apollo-link-error": "1.0.7",
    "apollo-link-http": "1.5.3",
    "graphql": "0.13.2",
    "graphql-tag": "2.8.0",
```
Anyone knows what I'm missing up?
Thanks

**Comment by kamilkisiela** [comment]
Do you use SSR mode?

**Comment by ahyos** [comment]
@kamilkisiela yes, and it works fine (Universal behaviour I mean).

 I've just test this without ssr flag and 'network-only' mode and it works!, somehow this SSR flag is breaking this fetchPolicy

so if I put again the SSR flag to true, the bug previously reported happens

**Comment by maapteh** [comment]
Seems to be related to https://github.com/apollographql/apollo-client/blob/337314111bc75e17834d0dfb6af461b921276dd2/packages/apollo-client/src/ApolloClient.ts#L209-L211

**Comment by kamilkisiela** [comment]
Since it's related to ApolloClient I would recommend to open an issue there

**Comment by michaelbromley** [comment]
Try using setting the `ssrForceFetchDelay` option to a non-zero value, say `500`. This should undo the forced "cache-only" policy as per this code: https://github.com/apollographql/apollo-client/blob/337314111bc75e17834d0dfb6af461b921276dd2/packages/apollo-client/src/ApolloClient.ts#L127-L132 

```ts
    if (ssrForceFetchDelay) {
      setTimeout(
        () => (this.disableNetworkFetches = false),
        ssrForceFetchDelay,
      );
    }
```

**Comment by neistow** [comment]
For me, the fix was conditionally setting `ssrMode` when creating `apolloOptions`.

```ts
const PLATFORM_SSR = new InjectionToken<boolean>(
  'Indicates if app is rendering in ssr mode',
  {
    factory: () => isPlatformServer(inject(PLATFORM_ID)),
  }
);

function apolloOptionsFactory(): ApolloClientOptions<any> {
  // ....

  const isSsr = inject(PLATFORM_SSR);

  return {
    link: httpLink.create({ uri }),
    cache,
    ssrMode: isSsr,
    devtools: {
      enabled: true,
    },
    defaultOptions: {
      watchQuery: {
        fetchPolicy: 'cache-and-network',
      },
      query: {
        fetchPolicy: 'no-cache',
      },
    },
  };
}
```
