### ISSUE TITLE
apollo-link-error onError implementation does not match with documentation / correct typings

### ISSUE THREAD

**Issue by kroeder** [apollographql/apollo-angular#504]
Hi,

I tried to use the apollo client afterware for statusCode checks.
In the documentation (https://www.apollographql.com/docs/angular/basics/network-layer.html#linkAfterware) there's a snippet where `onError` (from apollo-link-error) contains statusCode but in my case `networkError: Error` is returning a lib.es6 Error interface

```
interface Error {
    name: string;
    message: string;
    stack?: string;
}
```

I guess there is a apollo-client interface named `Error` as well?

**Comment by maapteh** [comment]
Its in an open ticket at https://github.com/apollographql/apollo-link/issues/300

**Comment by kamilkisiela** [comment]
Closing this in favor of apollographql/apollo-link#300
