### ISSUE TITLE
apollo-angular-link-http: Need "credentials" option to use the "include" option for CORS

### ISSUE THREAD

**Issue by Dunos** [apollographql/apollo-angular#505]
When using the **apollo-angular-link-http** package to create a link against a URI with multiple CORS values, it does not allow the option "credentials" to bypass that error. The _createHttpLink_ method from **apollo-link-http** package has that parameter (and works fine).

`
    const linkOptions = {
      credentials: 'include',
      uri: 'http://uri.com'
    };
`
`const httpLink = this.httpLink.create(linkOptions); // does not work`
`const httpLink = createHttpLink(linkOptions); // works`

The error looks like this:
`The 'Access-Control-Allow-Origin' header contains multiple values 'https://domain.com,http://dev.domain.com:4200', but only one is allowed`

**Comment by kamilkisiela** [comment]
@Dunos `apollo-angular-link-http` uses `HttpClient` from `@angular/common/http`, but `apollo-link-http` uses `fetch` API. It means that the first one has different options than the second one, including `credentials`. In `HttpClient` there is the same option called `withCredentials` so you can use this one.

`const linkOptions = { withCredentials: true, ... }`

**Comment by Dunos** [comment]
@kamilkisiela I tried that (forgot to mention) instead credentials include, but it does not work (same error) :/

**Comment by intellix** [comment]
I'm using this and it works:
```
const http = httpLink.create({
  uri: environment.uri,
  method: 'POST',
  withCredentials: true,
});
```

**Comment by kamilkisiela** [comment]
@Dunos Could you create a reproduction?

**Comment by Dunos** [comment]
Can't share the endpoints of our backend right now. The error happens when the "Access-Control-Allow-Origin" has multiple values.

For now I'm going to keep using **createHttpLink** from _apollo-link-http_ instead because I'm also using the "fetch" link option.
