### ISSUE TITLE
should I use angular http client interceptor or apollo link to add the authorization header?

### ISSUE THREAD

**Issue by goldenbearkin** [apollographql/apollo-angular#538]
As Apollo angular can use HttpClientModule under the hood, can I use http client interceptor to implement all the token issues (e.g. refresh token, authorization header)?

**Comment by kamilkisiela** [comment]
I depends. With ApolloLink it will use that header only on requests to the graphql endpoint but HttpInterceptor will attach it to all requests if won't catch the one you need. There is no one _good practice_, it depends what you want to achieve.
