### ISSUE TITLE
Angular and RxJS v6 compatibility

### ISSUE THREAD

**Issue by bmayen** [apollographql/apollo-angular#546]
Attempting to migrate a project to Angular v6.0.0-rc.2 with RxJS v6.0.0-rc.0 and rxjs-compat installed. Getting the following error on build:
`ERROR in ./node_modules/apollo-angular/utils.js Module not found: Error: Can't resolve 'rxjs/operator/observeOn'`

**Comment by kamilkisiela** [comment]
I'm going to migrate everything to RxJS and Angular 6 soon.

**Comment by kamilkisiela** [comment]
I'm going to do this after Wednesday but if someone wants to pick it up than it's fine :)

**Comment by plantsmiles** [comment]
Woot! Can't wait!!!

**Comment by kamilkisiela** [comment]
Work in progress #580

**Comment by kamilkisiela** [comment]
Right now you all can use it by adding `rxjs-compat` package

**Comment by kamilkisiela** [comment]
An update https://github.com/apollographql/apollo-angular/pull/580#issuecomment-387744110

**Comment by kamilkisiela** [comment]
You can now `yarn add apollo-angular@next`, later today I'll release a stable version.
