### ISSUE TITLE
do not kill watchQuery on errors

### ISSUE THREAD

**Issue by raysuelzer** [apollographql/apollo-angular#547]
I have run into an issue where a watchQuery will die if there is a network error.  I've tried a number of solutions, but I haven't found one that works. The goal is to be able to at least be able to `catchError` so that when a new value becomes available for the query, that it will update the UI. 

example would be something like this. Where I will soemtimes have an error on the query, but the cache may be updated for the query, and the watchQuery will be able to get the value.  Traditional methods of using a `switchMap, catchError` do not work in this case because the valueChanges observable is destroyed as soon as there is an error.

How does one handle this scenario? It's not practical to have watch queries just die due to a 500 error. 

```
        const assessmentLevelRef = this.apollo.watchQuery<GQL.IQuery>({
            query: getPersonAssessInfo,
            variables: {
                personId: this.person.id,
                campaignId: this.campaignId
            },
            fetchPolicy: 'cache-first',
            errorPolicy: 'ignore'
        });

        const asssessmentLevel = assessmentLevelRef.valueChanges
            .pipe(                 
                map((res: any) => {
                    if (res && res.data && res.data.getPerson) {
                        return res.data.getPerson.currentAssessmentLevel;
                    }
                    return null;
                })
            );      
```

**Comment by raysuelzer** [comment]
This was an issue on my end, sorry. The ignore error policy works fine.

**Comment by WilsonLau0755** [comment]
> This was an issue on my end, sorry. The ignore error policy works fine.

Hello, I have the same problem like what you had. while i using errorpolicy: 'all', the middleware error handler works, and there is something error log in console by system. however, it return nothing to my code while i want to taking some actions with my UI. 

Could you teach me how you solved this problem？Thanks!
