### ISSUE TITLE
Pass null as a variable

### ISSUE THREAD

**Issue by Mhs-220** [apollographql/apollo-angular#572]
hey there!
I want to pass null as some mutation field, is there any way to do this?
example query:
```GraphQL
mutation($id: ID!, $test: String!, $test2: String!){
    updateSomeThing(id: $id ,test: $test, test2: $test2){
        result
    }
}
```
variables:
```TypeScript
variables: {
    id: "Udfbs5efDSF==",
    test: "",
    test2: "Test"
}
```

I wanna pass null instead of empty string in test variable( "" ), is there any way to do this?

**Comment by kaisoz** [comment]
draft-them-all balenaci

**Comment by kaisoz** [comment]
draft-them-all balenaci

**Comment by kaisoz** [comment]
draft-them-all balenaci

**Comment by kaisoz** [comment]
draft-them-all balenaci

**Comment by lakshyak789** [comment]
> When your argument is mandatory on the GraphQL API (String!) You can not pass a null to it.
> Maybe by changing the GraphQL API to take a String and not a String!

thanks man

**Comment by Zony-Zhao** [comment]
I didn't think so. @OwlLaboratory . I want to make sure the field has a value. But this can be null. 
For example, I have a **Task** which has a field _handler_. Handler must be provided, but it can be null, which means this task is in a future task without  assigning to anyone.  
Having this key with a null value is totally different from absence of this field. Which may lead the DB write to a different result. A key with null value will overwrite the value in db to null.
