### ISSUE TITLE
Property 'request' in type 'HttpLinkHandler' is not assignable to the same property in base type 'ApolloLink'

### ISSUE THREAD

**Issue by chrishandorf** [apollographql/apollo-angular#579]
Haven't been able to build for a little while due to the below.  It seems similar to: https://github.com/apollographql/apollo-link/issues/599

v1.0.2 apollo-angular-link-http/HttpLink.d.ts has this:
export declare class HttpLinkHandler extends ApolloLink {
    ...
    **request(op: Operation): LinkObservable<ExecutionResult> | null;**
}

v1.2.2 apollo-link/src/link.ts has this:
export class ApolloLink {
  ...
  **public request(
    operation: Operation,
    forward?: NextLink,
  ): Observable<FetchResult> | null {
    throw new Error('request is not implemented');
  }**
}

ERROR in node_modules/apollo-angular-link-http/HttpLink.d.ts(10,5): error TS2416: Property 'request' in type 'HttpLinkHandler' is not assignable to the same property in base type 'ApolloLink'.
  Type '(op: Operation) => Observable<ExecutionResult>' is not assignable to type '(operation: Operation, forward?: NextLink) => Observable<FetchResult<Record<string, any>, Record<...'.
    Type 'Observable<ExecutionResult>' is not assignable to type 'Observable<FetchResult<Record<string, any>, Record<string, any>>>'.
      Type 'ExecutionResult' is not assignable to type 'FetchResult<Record<string, any>, Record<string, any>>'.
        Type 'ExecutionResult' is not assignable to type 'ExecutionResult'. Two different types with this name exist, but they are unrelated.
          Types of property 'errors' are incompatible.
            Type 'ReadonlyArray<GraphQLError>' is not assignable to type 'GraphQLError[]'.
              Property 'push' is missing in type 'ReadonlyArray<GraphQLError>'.

**Comment by kamilkisiela** [comment]
I think releasing 7f58eff will fix that, will try to do that today

**Comment by chrishandorf** [comment]
Working again - thanks
