### ISSUE TITLE
apollo-angular-link-http-common peer dependency missing

### ISSUE THREAD

**Issue by nodehack** [apollographql/apollo-angular#588]
```
npm ERR! peer dep missing: graphql@^0.11.3 || ^0.12.3, required by apollo-angular-link-http-common@1.0.0
```

Looks like the package.json for apollo-angular-link-http-common was updated but never pushed a new version to npm so common still thinks its missing graphql dependency if you're using 0.13.x.

**Steps to Reproduce:**
Follow npm install instructions from main apollo-angular README.
`npm install apollo-angular apollo-angular-link-http apollo-link apollo-client apollo-cache-inmemory graphql-tag graphql --save`

You'll get `npm WARN apollo-angular-link-http-common@1.0.0 requires a peer of graphql@^0.11.3 || ^0.12.3 but none is installed. You must install peer dependencies yourself.`

run `npm list`

You'll get `npm ERR! peer dep missing: graphql@^0.11.3 || ^0.12.3, required by apollo-angular-link-http-common@1.0.0`

**Comment by kamilkisiela** [comment]
This has been fixed in a recent RC

https://github.com/apollographql/apollo-angular/pull/580#issuecomment-387744110

**Comment by kamilkisiela** [comment]
You can now `yarn add apollo-angular-link-http@next`, later today I'll release a stable version.
