### ISSUE TITLE
FetchResult type use unsoundness

### ISSUE THREAD

**Issue by infogulch** [apollographql/apollo-angular#589]
In [apollo-angular/src/Apollo.ts](https://github.com/apollographql/apollo-angular/blob/master/packages/apollo-angular/src/Apollo.ts#L37) `Apollo.mutate<T>` uses `FetchResult<T>` just like `query<T>` uses `ApolloQueryResult<T>`. But the meaning of T is completely different between the two target types (FetchResult & ApolloQueryResult) leading to unsound usage.

ApolloQueryResult is defined in [apollo-client/src/core/types.ts](https://github.com/apollographql/apollo-client/blob/9ebbb61fb1061f56edf0bedb965c9954f75afead/packages/apollo-client/src/core/types.ts#L16) as:
``` typescript
export declare type ApolloQueryResult<T> = {
    data: T;
    // snip
};
```

Note that the first type parameter declares the type of the `data` property.

FetchResult is defined in [apollo-link/src/types.ts](https://github.com/apollographql/apollo-link/blob/623b04cd145b68e2d455f3db6e971dac8bc7d738/packages/apollo-link/src/types.ts#L23) as:
``` typescript
export type FetchResult<
  C = Record<string, any>,
  E = Record<string, any>
> = ExecutionResult & {
  extensions?: E;
  context?: C;
};
```

Note that the first type parameter C is used to declare the type of `context`, and the type of ExecutionResult's `data` property is left undeclared. Comparing to ApolloQueryResult, one would expect the first type parameter to declare the type of the data property.

I see one bug and one API issue here:

1. apollo-angular is using `FetchResult<C,E>` wrong which subverts the type system.
2. apollo-link declares `FetchResult` without a T parameter to set the type of the data property. It should be declared `FetchResult<T,C,E>` with `data?: T;` in the body. (I will be filing an issue on apollo-link as well.)
3. (edit:) apollo-client [appears](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L216) to use the FetchResult wrongly as well. It's not easy to tell for sure because the expected type information disappears eventually so I'm not 100% sure what's intended, but going by context and usage it really looks like FetchResult isn't defined correctly.

**Comment by kamilkisiela** [comment]
I'll close this one in favour of the one in Apollo Link repo.
