### ISSUE TITLE
Angular 6 is out :)

### ISSUE THREAD

**Issue by jycouet** [apollographql/apollo-angular#600]
Hello,

I'm trying to update my application to Angular6, but I have an issue.
Here is what I get when I do a `ng update @angular/core`

`Package "apollo-angular" has an incompatible peer dependency to "rxjs" (requires "^5.0.1", would install "6.1.0").`

Could you have a look?
Let me know if you need help :)

**Comment by plinionaves** [comment]
Hello @jycouet,

I also have a project with apollo-angular, I just instaled this package in your local project:

`npm i -S rxjs-compat`

Then do this:

`npm i -g rxjs-tslint
rxjs-5-to-6-migrate -p src/tsconfig.app.json`

And works fine!

This is necessary until the apollo-angular update your code to work with rxjs@6.

Hugs!

**Comment by jycouet** [comment]
WoW, that works soooooooooooooooooo well :)
Thanks 🍾 🤙

**Comment by jycouet** [comment]
Actually, it's going forward and my build is running :)
But I have errors in the browser console:
```
ERROR TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeTo (subscribeTo.js:41)
    at from (from.js:17)
    at new QueryRef (QueryRef.js:6)
    at Apollo.push../node_modules/apollo-angular/Apollo.js.ApolloBase.watchQuery
```

Do you have another magic trick? 
Thx for your help

**Comment by picosam** [comment]
@plinionaves keep the free hugs goin' man!

**Comment by intellix** [comment]
Another issue: 
```
Package "apollo-angular-link-http-batch" has an incompatible peer dependency to "@angular/core" (requires "^4.3.0 || ^5.0.0-rc.0",would install "6.0.0")
```

**Comment by wenerme** [comment]
@jycouet Have you work this out ? Upgrade today, meet the same problem

**Comment by plinionaves** [comment]
Hello @jycouet, sorry for the delay...

I'm not sure, but this looks like some code error, you have many watchQueries? I recommend check his, mainly in use of Observable operators.

Tip: can try to search use of "catch" in your code, if you have something like this:

`myObservable
   .catch(...`

Change to this:

`myObservable
   .pipe(
       catchError(err => /* do something */)
    )`

Do the test.

Hug!

**Comment by frederik** [comment]
@jycouet this seems to be related to #545 (which also references #580). The workaround that is mentionend there, did fix the invalid object error.

**Comment by wenerme** [comment]
when will #580 get released ?

**Comment by frederik** [comment]
The [milestone](https://github.com/apollographql/apollo-angular/milestone/11) states May 12th, though there is still quite a lot open - @kamilkisiela can probably tell best.

**Comment by wenerme** [comment]
😢 we have to disable all apollo apis to let project running, so sad.

**Comment by jycouet** [comment]
#545 worked well for me 👍 
Tmp fix is nice, waiting for @kamilkisiela ;)

**Comment by kamilkisiela** [comment]
An update https://github.com/apollographql/apollo-angular/pull/580#issuecomment-387744110

**Comment by bardiel** [comment]
Thank you so much for keeping us posted @kamilkisiela !

**Comment by kamilkisiela** [comment]
You can now `yarn add apollo-angular@next`, later today I'll release a stable version.
