### ISSUE TITLE
[BUG] FetchMore() trigger QueryRef value changes before it's over

### ISSUE THREAD

**Issue by OwlLaboratory** [apollographql/apollo-angular#648]
Hi everyone !

Since a few weeks I try to implement a very simple workflow with the fetchMore() function.

I retrieve information from a campaign object: id, name, start_time, end_time.
When the user clicks a button, new data for the campaign is retrieved via fetchMore().

Whenever I click on the button, the observable valueChanges of the queryRef detects a new value even before fetchMore () has finished its work.
So I never have my object updated in valueChanges.

![apollo_issue](https://user-images.githubusercontent.com/28731923/40969368-fcae2fd4-68b7-11e8-97c8-f3f52f7ea237.png)

Here is a stackblitz that reproduces the problem: 
The logic is in **report.service.ts** & **app.component.ts**
You can see debug information in the console
https://stackblitz.com/github/OwlLaboratory/apollo_angular_issue

I would be infinitely grateful to the person who can explain to me where the problem comes from or if it is a bug?

Good day everyone and thanks in advance (sorry for my poor english)

**Comment by kamilkisiela** [comment]
It's related to `apollo-client`, not `apollo-angular` itself. Please open an issue [here](https://github.com/apollographql/apollo-client).

Here's how I know it's on `apollo-client`'s side
https://stackblitz.com/edit/github-a6bkz5?embed=1&file=src/app/report.service.ts

**Comment by OwlLaboratory** [comment]
Thank you for your quick answer ! :)
