### ISSUE TITLE
Error GraphQL subscriptions

### ISSUE THREAD

**Issue by javadababadoo** [apollographql/apollo-angular#668]
**Intended outcome:**

The GraphQL subscriptions work correctly.

**Actual outcome:**

I'm getting an error when I try to create a GraphQL subscription on Angular with the latest versions.

`
ERROR TypeError: Object(...) is not a function
at ApolloBase.subscribe (webpack-internal:///./node_modules/apollo-angular/Apollo.js:54)
`

**How to reproduce the issue:**

I updated all dependencies to latest and have the following code:

```
const deviceLocationEvent = gql`
    subscription{
        deviceLocationEvent{
            id
            hostname
            groupName
        }
    }
`;

apollo.subscribe({
        query: deviceLocationEvent
}).subscribe(resp => {
   console.log('Subscription ', resp);
});

```
When I try to subscribe to a GraphQL subscription, I'm getting the error previously mentioned.

The error is also happening with the watchQuery method, here a code example where I was able to represent the same error with watchQuery.  I don´t know why but when the code is executed on Stackblitz the error is different:

[https://stackblitz.com/github/javadababadoo/DemoGraphQLTest](url)

 [https://github.com/javadababadoo/DemoGraphQLTest](url)

using:

    "apollo-angular": "1.1.1",
    "apollo-angular-link-http": "1.1.0",
    "apollo-cache-inmemory": "1.2.4",
    "apollo-client": "2.3.4",
    "apollo-link-context": "1.0.8",
    "apollo-link-http": "1.5.4",
    "apollo-link-ws": "1.0.8"

**Comment by kamilkisiela** [comment]
I guess it's related to #651, I'll check it after this weekend.
