### ISSUE TITLE
Type Error: Wrong generic types QueryRef (Apollo Client)

### ISSUE THREAD

**Issue by julietacampos** [apollographql/apollo-angular#669]
Hello! We're adding Apollo to two projects that use Angular 6 created with the latest Angular CLI. We got the setup done like in the documentation but when we run the project we get these errors:

```
node_modules/apollo-angular/QueryRef.d.ts(14,33): error TS2314: Generic type 'FetchMoreQueryOptions<TVariables, K>' requires 2 type argument(s).
node_modules/apollo-angular/QueryRef.d.ts(16,60): error TS2314: Generic type 'UpdateQueryOptions<TVariables>' requires 1 type argument(s).
``` 

And when we go to compile, the build fails completely. Is there anything we can do here to fix it?

**Comment by bmayen** [comment]
`skipLibCheck: true` in your tsconfig will get around this in the meantime

**Comment by kamilkisiela** [comment]
This issue came up in latest `apollo-client`, they changed interfaces a bit...

**Comment by kamilkisiela** [comment]
A little summary because I guess it will make a lot of noise in near future.

**Comment by cbyte** [comment]
Neither one of that upgrades works for us, because we are using Ionic, which depends on RxJs 5.

**Comment by kamilkisiela** [comment]
@cbyte ApolloClient introduced that issue so there's nothing I can do about it.

You can still use `apollo-client` v2.3.2 or less with `apollo-angular` v1.0.1 or less and it should work. It's also possible to use latest apollo-client with `apollo-angular` <= 1.0.1, but you have to set `skipLibCheck: true` in tsconfig's compilerOptions.

**Comment by kwoxford** [comment]
You can use Rxjs 6 with Ionic by adding rxjs-compat and doing a bit of tidying
