### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by danilohgds** [apollographql/apollo-angular#705]
Hello fellow developers.
I ran into some issues while developing my Apollo-Client classes with Angular 5. At the moment I have the apollo-angular at 1.0.0, and I cannot figure out what to do to replace APOLLO_OPTIONS import.

```typescript

export const APOLLO_OPTIONS = new InjectionToken<ApolloClientOptions<any>>(
  '[apollo-angular] options',
);

export function createApollo(httpLink: HttpLink) {
  return {
    link: httpLink.create({uri: 'http://localhost:8080/svc/graphql'}),
    cache: new InMemoryCache(),
  };
}

@NgModule({
    declarations: [
        AppComponent,
        SideMenuComponent,
        DashComponent,
        MainComponent,
        DialogWelcomeComponent,
        ModalRouteComponent
    ],
    imports: [
        BrowserModule,
        BrowserAnimationsModule,
        RouterModule.forRoot(appRoutes),
        StoreModule.forRoot(reducers, { metaReducers }),
        StoreRouterConnectingModule.forRoot({
            stateKey: 'router'
        }),
        EffectsModule.forRoot([]),
        ApolloModule,
        HttpLinkModule,
        HttpClientModule,
        !environment.production
        ? StoreDevtoolsModule.instrument({ maxAge: 50 })
        : [],
        HttpClientModule, ApolloModule, HttpLinkModule
    ],
    providers: [
        {
          provide: APOLLO_OPTIONS,
          useFactory: createApollo,
          deps: [HttpLink],
        },
        { provide: RouterStateSerializer, useClass: CustomSerializer }
      ],
    bootstrap: [AppComponent],
    entryComponents: [
        DialogWelcomeComponent
    ]
})


export class AppModule {
    constructor(
    apollo: Apollo,
    httpLink: HttpLink
  ) { }
}

```
While doing the above, I keep getting the  
ERROR Error: Client has not been defined yet
    at ApolloBase.checkInstance (Apollo.js:68)
    at ApolloBase.beforeEach (Apollo.js:64)
    at Apollo.get [as client] (Apollo.js:57)

This worked with 1.1.1 but I'm on Angular5 with RXJS 5, therefore going to RXJS6 might not be an option atm.

Can anyone help me figure out how to properly setup my client with DI? I have done quite a bit of researching online and there aren't many resources on the angular implementations of Apollo at all.
/label Help Wanted

**Comment by kamilkisiela** [comment]
`APOLLO_OPTIONS` won't work because you create it on your own and not the version of `apollo-angular`.

If you have a version that doesn't export `APOLLO_OPTIONS` then the only thing you can do is to use `Apollo.create`. I noticed that you want to create Apollo on Dependency Injection level so you can try [`APP_INITIALIZER`](https://angular.io/api/core/APP_INITIALIZER).

```ts
// inside of NgModule
{ provide: APP_INITIALIZER, useFactory: createApollo, deps: [Apollo, HttpLink], multi: true }

// somewhere
export function createApollo(apollo, Apollo, httpLink: HttpLink) {
  apollo.create({
    link: httpLink.create({uri: 'http://localhost:8080/svc/graphql'}),
    cache: new InMemoryCache(),
  });
}
```
