### ISSUE TITLE
Apollo Mutation Returns Error Code 400 on POST and error 204 on the OPTIONS

### ISSUE THREAD

**Issue by riginoommen** [apollographql/apollo-angular#717]
While passing data from client to server i getting this error code

<img width="1680" alt="screen shot 2018-07-19 at 9 35 43 pm" src="https://user-images.githubusercontent.com/3840244/42999043-f0c7031c-8c39-11e8-9653-2f6242578059.png">
<img width="1346" alt="screen shot 2018-07-19 at 9 35 59 pm" src="https://user-images.githubusercontent.com/3840244/42999045-f0fec00e-8c39-11e8-9ec7-455cd13b2d7e.png">
<img width="1676" alt="screen shot 2018-07-19 at 9 35 21 pm" src="https://user-images.githubusercontent.com/3840244/42999046-f1317f12-8c39-11e8-91eb-8ae4636995a8.png">

**Comment by kamilkisiela** [comment]
I don't think is somehow related to the client. The error is thrown by a server. Try to check the terminal with GraphQL Server process going on.

I'm closing right now but let me know if I was wrong so I'll reopen it and help you :)

**Comment by riginoommen** [comment]
This is my terminal log

    "OPTIONS /graphql 204 0 - 0.256 ms - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
    "POST /graphql 400 1917 - 2.977 ms https://localhost:4200/modules/create Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

**Comment by kamilkisiela** [comment]
@riginoommen Okay but it doesn't say anything, the only thing it says is:
- Server responded with 204 for OPTIONS operation
- Server responded with 400 for POST operation

That's it.

**Comment by riginoommen** [comment]
@kamilkisiela Yes you are correct when i do the same from graphiql i getting same error
<img width="1087" alt="screen shot 2018-07-30 at 3 16 09 pm" src="https://user-images.githubusercontent.com/3840244/43390383-b3fc7ad2-940b-11e8-9e59-dbe8ffda2d15.png">

**Comment by kamilkisiela** [comment]
Please read the error messages. They say you have missing arguments, the query itself is wrong.

It has nothing to do with `apollo-angular` or `apollo-client`, that's why I closed the issue.
