### ISSUE TITLE
SwitchMap no longer cancels ajax requests for queries

### ISSUE THREAD

**Issue by crissi** [apollographql/apollo-angular#721]
Newest version of Apollo no longer cancel ajax requests when using switchMap.

I use apollo.query, did not test watchQuery.

 Works fine when using the Angular HttpClient.

```
    this.searchField = new FormControl();
    this.searchField.valueChanges.pipe(
      switchMap(term => this.search(term)),
    ).subscribe(res => {
      this.results = res;
    });
```

```
  search(term: string): Observable<any> {
    const casesQuery: DocumentNode = gql`
        query cases($searchQuery: String) {
            someQuery(
                search: {query: $searchQuery},
            ) {
                items {
                    id
                }
            }
        }
    `;

    return this.apollo.query({
      query: casesQuery,
      variables: {
        searchQuery: term
      },
    });
  }

```

**Comment by AmitXShukla** [comment]
Using Angular 6.1.0, I am not able to cancel any subscription in-spite of using async or unsubscribe();
this.data = this._apollo.watchQuery({query: getJobCode_Q}).valueChanges;
<ul *ngFor="let entry of data | async | select: 'getJobCode_Q'">
CODE: {{entry.CODE}}
</ul>
Re-browsing to this component or calling getData() doesn't re-fetch any data from GraphQL server.
Only way to re-fetch/get new data is to reload entire Angular App.

**Comment by kamilkisiela** [comment]
@crissi In apollo-angular `.query()` wraps a Promise with Observable, I don't know if it cancels a promise, need to check it. Maybe you can create a test for it? I can help you!

@AmitXShukla I added tests and https://github.com/apollographql/apollo-angular/pull/733/files#diff-be568156b5ced52591b3b4f42328bcd8 seems to work fine.

**Comment by kamilkisiela** [comment]
@crissi `.query()` doesn't cancel the request because `unsubscribe()` can't cancel a Promise since it's not cancellable, only with `AbortController` which ApolloClient doesn't support. I think you should open an issue in ApolloClient.
