### ISSUE TITLE
Support to upload file.

### ISSUE THREAD

**Issue by ysantalla** [apollographql/apollo-angular#737]
Why do not you support the upload of files in the official library?

apollo-upload-angular-link-http

**Comment by kamilkisiela** [comment]
There's no official library because me and my team mates don't upload files through GraphQL so I never really started looking into it.

Feel free to create one that is based on `HttpClient`, for now you can use https://github.com/jaydenseric/apollo-upload-client

**Comment by ysantalla** [comment]
Thanks for your explanation, some example of the upload files in angular?
