### ISSUE TITLE
How to mock ApolloLink for unit testing?

### ISSUE THREAD

**Issue by ayyazzafar** [apollographql/apollo-angular#761]
I am writing unit tests for an application. 
I am facing difficulty to mock ApolloLink. I am not sure how to mock it.
This is how I am using it in my component:

`new ApolloLink(((operation, forward) => {....`

I can mock services easily if these are coming from constructor but it does not seems to be possible by manually instantiating classes like above.

Thanks in Advance!

**Comment by kamilkisiela** [comment]
@ayyazzafar I usually try to have each link under InjectionToken, [here's an example on StackBlitz](https://stackblitz.com/edit/apollo-angular-links-as-tokens?file=app%2Fapollo%2Flog-link.ts)
