### ISSUE TITLE
Feature proposal: `ng add apollo-angular`

### ISSUE THREAD

**Issue by sis0k0** [apollographql/apollo-angular#762]
Angular CLI 6.0 introduced a new command - `ng add`. It allows plugin authors to add an installation script to their npm packages. That script will be executed whenever someone installs the plugin with `ng add my-plugin`.
The script should be implemented as a [schematic](https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2) in order to be executed by the Angular CLI.

## ng add apollo-angular
The initial setup of `apollo-angular` can be automated by enabling `ng add`. It should do the following:
1. Installs the `apollo-angular` plugin.
That happens automatically because the Angular CLI will execute `npm install apollo-angular`, whenever someone executes `ng add apollo-angular`.

2. Installs the other dependencies and add them to the project's package.json.(`apollo-angular-link-http apollo-link apollo-client apollo-cache-inmemory graphql-tag graphql`).

3. Adds an NgModule with an initial setup to the project.
```
// graphql.module.ts
import { NgModule } from '@angular/core';

import { ApolloModule, APOLLO_OPTIONS } from 'apollo-angular';
import { HttpLinkModule, HttpLink } from 'apollo-angular-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';

const uri = ''; // <-- add the URL of the GraphQL server here
export function createApollo(httpLink: HttpLink) {
  return {
    link: httpLink.create({ uri }),
    cache: new InMemoryCache(),
  };
}

@NgModule({
  exports: [
    ApolloModule,
    HttpLinkModule
  ],
  providers: [
    {
      provide: APOLLO_OPTIONS,
      useFactory: createApollo,
      deps: [HttpLink],
    },
  ],
})
export class GraphQLModule { }
```

4. Imports the `GraphQLModule` and `HttpClientModule` to the root NgModule.
```
// app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';

import { AppComponent } from './app.component';
import { GraphQLModule } from './graphql.module';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    HttpClientModule,
    GraphQLModule,
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

With these changes done automatically, the project should be ready to use the `apollo-angular` plugin.
Please share any comments or suggestions :)

**Comment by kamilkisiela** [comment]
#779

**Comment by naveenrawat51** [comment]
"lib": [
      "es6",
      "dom", 
      "esnext"
    ],
fixed my issue. Thank you guys
