### ISSUE TITLE
ERROR in node_modules/apollo-angular/types.d.ts(9,58): error TS2304: Cannot find name 'Exclude'.

### ISSUE THREAD

**Issue by ysantalla** [apollographql/apollo-angular#773]
import { NgModule, SkipSelf, Optional } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClientModule, HttpHeaders } from '@angular/common/http';

import { ApolloModule, Apollo } from 'apollo-angular';
import { HttpLinkModule } from 'apollo-upload-angular-link-http';
import { split, from, ApolloLink } from 'apollo-link';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { WebSocketLink } from 'apollo-link-ws';
import { getMainDefinition } from 'apollo-utilities';

import { createUploadLink } from 'apollo-upload-client';
import { onError } from 'apollo-link-error';

import { environment as env } from '@env/environment';
import { AuthService } from '@app/core/services/auth.service';
import { AuthGuard } from '@app/core/guard/auth.guard';
import { RoleGuard } from '@app/core/guard/role.guard';

@NgModule({
  imports: [
    CommonModule,
    HttpClientModule, // provides HttpClient for HttpLink
    ApolloModule,
    HttpLinkModule
  ],
  exports: [ApolloModule, HttpLinkModule],
  providers: [AuthGuard, RoleGuard, AuthService],
  declarations: []
})
export class CoreModule {

  constructor(
    @Optional()
    @SkipSelf()
    parentModule: CoreModule,
    public apollo: Apollo,
    private authService: AuthService
  ) {
    if (parentModule) {
      throw new Error('CoreModule is already loaded. Import only in AppModule');
    }

    const authLink = new ApolloLink((operation, forward) => {
      operation.setContext({
        headers: new HttpHeaders().set(
          'Authorization',
          `Bearer ${this.authService.getToken()}` || null
        )
      });
      return forward(operation);
    });

    const errorLink = onError(({ graphQLErrors, networkError, forward, response, operation }) => {
      if (graphQLErrors) {
        console.log(`GraphQL error ${graphQLErrors}`);
      }
      if (networkError) {
        console.log(`[Network error]: ${networkError}`);
       }
    });

    const uploadLink = createUploadLink({ uri: env.httpLinkServer });

    // Create a WebSocket link:
    const subscriptionLink = new WebSocketLink({
      uri: env.wsLinkServer,
      options: {
        reconnect: true,
        timeout: 20000,
        connectionParams: {
          authToken: this.authService.getToken() || null
        }
      }
    });

    const networkLink = split(
      ({ query }) => {
        const definition = getMainDefinition(query);
        return (
          definition.kind === 'OperationDefinition' &&
          definition.operation === 'subscription'
        );
      },
      subscriptionLink,
      uploadLink
    );

    this.apollo.create({
      link: from([authLink, errorLink, networkLink]),
      cache: new InMemoryCache(),
      defaultOptions: {
        watchQuery: {
          fetchPolicy: 'cache-and-network',
          errorPolicy: 'none',
        },
        query: {
          fetchPolicy: 'cache-and-network',
          errorPolicy: 'none',
        },
        mutate: {
          errorPolicy: 'none',
        },
      }
    });

  }
}

**Comment by ysantalla** [comment]
this is a compilation error, it appeared when adding apollo-upload-client

**Comment by kamilkisiela** [comment]
#770
