### ISSUE TITLE
The pipe 'select' could not be found in Angular 6.1.4

### ISSUE THREAD

**Issue by emolr** [apollographql/apollo-angular#805]
Hi, I have followed the guide from Apollo-angular using the `apollo-angular-boost`module. 

Somehow I can't use the select pipe, and if I try to set it as a declaration myself in any module, it complains about being present in two modules. 

Is this a bug, or something I am missing?

All the best

**Comment by emolr** [comment]
Thank you @kamilkisiela for returning to me, sorry I didn't get to answer quickly. I'm going to close the issue. Thanks!

**Comment by dauledk** [comment]
@kamilkisiela why is the SelectPipe going to be deprecated?
