### ISSUE TITLE
How do I make variable type known to Query ?

### ISSUE THREAD

**Issue by catull** [apollographql/apollo-angular#817]
Got this query, which works nicely in `GraphQL Playground`:

```typescript
import { Injectable } from '@angular/core';
import { Apollo, Query } from 'apollo-angular';
import gql from 'graphql-tag';

import { PublicationsPagePublication, SortInput } from './api';

interface IVariables {
  pageNumber: number;
  pageSize: number;
  sort: SortInput;
}

@Injectable({
  providedIn: 'root',
})
export class PublicationSearchGQL extends Query<PublicationsPagePublication, IVariables> {
  document = gql`
query publicationPage(
  $pageSize: Int
  $pageNumber: Int
  $sort: SortInput
) {
  publicationsPage(
    pageSize: $pageSize
    pageNumber: $pageNumber
    sort: $sort
  ) {
    publications {
      id
    }
  }
}
  `;

  constructor(apollo: Apollo) {
    super(apollo);
  }
}
```
When an instance of `PublicationSearchGQL` is used as

```typescript
    this.publicationSearchQuery
      .fetch({
        pageSize: 15,
        pageNumber: this.paginationConfig.pageIndex,
        filters,
      })
      .subscribe(result => {
           // nice things are done here
      });
```
at runtime, there are validation errors for 'SortInput`:

```json
{
  "errors": [
    {
      "message": "Validation error of type UnknownType: Unknown type SortInput",
      "locations": [{ "line": 1, "column": 64 }]
    },
    {
      "message": "Validation error of type UnknownArgument: Unknown field argument sort @ 'publicationsPage'",
      "locations": [{ "line": 2, "column": 66 }]
    }
  ]
}
```
What am I missing ?

**Comment by kamilkisiela** [comment]
It's missing on the server, your GraphQL Schema doesn't include `input SortInput { }`

**Comment by catull** [comment]
I am afraid I don't follow this argumentation.

Why then does `GraphQL Playground` succeed ?
I get field completion etc in `GraphQL Playground`.

I generated the `./api.ts` through gql-gen from the same graphlql server.

See this screen shots
![image](https://user-images.githubusercontent.com/150055/45554625-2b104a00-b837-11e8-9746-d83bb5fc8fa3.png)
and
![image](https://user-images.githubusercontent.com/150055/45554730-57c46180-b837-11e8-8d31-589722fd3ad0.png)

**Comment by catull** [comment]
Everything worked when there were only 2 variables: `pageSize` and `pageNumber`.
That is not a suprise, both of them are of type `Int` - scalar types.
`SortInput` is composed of two scalar types:
 * `sortDirection` is an enum
* `sortColumn` is another enum

`sortDirection` is of type
```graphql
enum Direction {
  ASC
  DESC
}
```
and `sortColumn` of type
```graphql
enum SortColumn {
  CHNumber
  Canton
  CompanyName
  Location
  PublicationDate
  PublicationLanguage
  PublicationType
}
```

**Comment by catull** [comment]
Oh, I see now.

https://graphql.org/graphql-js/mutations-and-input-types/ mentions this

> To make your schema simpler, you can use “input types” for this, by using the input keyword instead of the type keyword.

**Comment by kamilkisiela** [comment]
`SortInput` is a `type` and should be `input`.

```graphql
input Sortnput { }
```
