### ISSUE TITLE
has no exported member 'Subscription'

### ISSUE THREAD

**Issue by viandanteoscuro** [apollographql/apollo-angular#818]
Hi to all, 

I follow the documentation for creating a Subscription, but when i do "ng serve", i have the following error:

ERROR in src/app/apollo-subscriptions/get-storages.subscrption.ts(1,10): error TS2305: Module '"S:/src/products/CubeNG/csharp/cubewebclient/ClientApp/node_modules/apollo-angular/index"' has no exported member 'Subscription'.

Con i fix this?

The code is copy&paste from the site https://www.apollographql.com/docs/angular/basics/services.html#Subscription

Thanks

**Comment by kamilkisiela** [comment]
It's exported,
https://github.com/apollographql/apollo-angular/blob/master/packages/apollo-angular/src/index.ts#L5

Could you try out the latest version? v1.3.0

**Comment by viandanteoscuro** [comment]
Oh yes, thanks and sorry!

But once subscribed, how i grab the new notified data? As usual on angular standard subscription?
thanks

**Comment by kamilkisiela** [comment]
@viandanteoscuro Just like here https://www.apollographql.com/docs/angular/features/subscriptions.html, except instead of subscribeToMore you have `subscribe` method that returns an Observable

And to receive new data you once again, subscribe to that Observable.
