### ISSUE TITLE
Create GraphQL client with authentication header before intializing Angular app

### ISSUE THREAD

**Issue by okkevdeijk** [apollographql/apollo-angular#825]
Hi there,

I am now encountering the following issue which is also related to my [server side rendering](https://github.com/apollographql/apollo-angular/issues/765) issue. 

I was struggling with the "Apollo client is not defined" error and followed[ this solution](https://stackoverflow.com/questions/49257668/angular-apollo-client-has-not-been-defined-yet) on StackOverflow. Then I ran into issues with undefined token, because Apollo is already there if there's not token availble. I implemented an [HTTP interceptor](https://github.com/apollographql/apollo-angular/issues/628), according to [this example](https://stackblitz.com/edit/simple-apollo-angular-example-headers), to tackle this. However, I'm still having troubles, because the GraphQL client is not defined BEFORE the app loads and thus not showing any results, however the token is now there.

So can someone please help and suggest how to implement the following scenario:
- User gets a link
- The token is not there yet (in localstorage)
- The angular app needs to ask for a token BEFORE...
- ... the GraphQL client gets intialized

Would be awesome if this is a solution which does help to work server side rendering in Angular as well.

My code: 
```ts
export function provideApollo(httpLink: HttpLink, userService: UserService, httpClient: HttpClient) {
    const anonymousToken = userService.getAnonymousToken();
    const authenticatedToken = userService.getAuthenticatedToken();

    if (!authenticatedToken && !anonymousToken) {
        getToken(httpClient, userService).then(() => {
            const basic = setContext((op, ctx) => ({
                headers: new HttpHeaders()
            }));

            const link = ApolloLink.from([basic, httpLink.create({ uri })]);
            console.log('return link');
             <!-- This loggin shows here but the GraphQL client doesn't do any call in my service, I think 
               becuase the return is after the time the token is there-->

            return {
                link,
                cache: new InMemoryCache()
            };
        });
    } else {
        const basic = setContext((op, ctx) => ({
            headers: new HttpHeaders()
        }));

        const link = ApolloLink.from([basic, httpLink.create({ uri })]);

        return {
            link,
            cache: new InMemoryCache()
        };
    }
}
```

```ts
export function getToken(httpClient: HttpClient, userService: UserService): Promise<any> {
    return new Promise((resolve, reject) => {
        const authUri = environment

        const token = httpClient.post(authUri, {}, httpOptions);

        token.subscribe(async response => {
            const anonymousToken = 'Bearer ' + response['access_token'];
            await userService.setAnonymousToken(anonymousToken);
            resolve();
        });
    });
}
```

```ts
@NgModule({
    exports: [
        HttpClientModule,
        ApolloModule,
        HttpLinkModule
    ],

    providers: [
        HttpClient,
        {
            provide: APOLLO_OPTIONS,
            useFactory: provideApollo,
            deps: [HttpLink, UserService, HttpClient],
        }
    ],
})
export class GraphQLModule { }
```

**Comment by kamilkisiela** [comment]
@okkevdeijk Hi

First of all, when you provide anything to Dependency Injection, it has to be sync, not async as you did in `provideApollo` function.

What you want is to get the token `inside` of `setContext`.

**Comment by kamilkisiela** [comment]
Also, you don't have to anything before app is initialized. Angular Universal waits for the app to be stable and then it renders the page. What makes the app unstable? Pending macro tasks in Zone.js.

**Comment by okkevdeijk** [comment]
Hi @kamilkisiela 
Thank you so much! This was indeed exactly what I needed:
https://www.apollographql.com/docs/link/links/context.html
