### ISSUE TITLE
Idea: watchMutate

### ISSUE THREAD

**Issue by intellix** [apollographql/apollo-angular#842]
I've got a stream of multiplayer games which you can join. Underneath is a list of the players with their tickets. The player joins with an `amount` and then the server emits when something changes (emitted via GQL Subscription):

**join-game-form.component.ts:**
```ts
const variables = { ...this.form.value };
const mutation = gql`
  mutation JoinGame($gameId: ID!, $amount: Int!) {
    join(gameId: $gameId, amount: $amount) {
      ticket {
        id
        gameId
        amount
        finishedAt
      }
    }
  }
`;

this.apollo.mutate({ mutation, variables }).subscribe(({ data }) => this.ticket = data.join.ticket);
```

The mutation responds with the new ticket for the player and the UI updates showing that they're in the game and now I need to know when the server updates the ticket.

In another component I'm listing all tickets for all players:

**list-players.component.ts:**
```gql
subscription TicketUpdate($gameId: ID!) {
  onTicketUpdate(gameId: $gameId) {
    id
    finishedAt
  }
}
```

The only way for `join-game-form.component.ts` to know the `finishedAt` value changed is if I make another `watchQuery` after the mutation (round trip to server to refetch) so I receive the updates that the Store already knows about like so:

```ts
this.apollo.mutate({ mutation, variables })
  .pipe(
    switchMap(({ data }) => {
      const ticketId = data.join.ticket.id;
      return this.apollo.watchQuery({
        variables: { ticketId },
        query: gql`
          query GetTicket($ticketId: ID!) {
            ticket(id: $ticketId) {
              id
              gameId
              amount
              finishedAt
            }
          }
        `
      }).valueChanges
    }),
    takeUntil(this.newGame$),
  )
  .subscribe(({ data }) => this.ticket = data.ticket);
```

This could be simplified and would save a server call by being able to watch the store after a mutate:
```ts
const queryRef = this.apollo.watchMutate({ mutation, variables });
queryRef.pipe(takeUntil(this.newGame$)).subscribe(({ data }) => this.ticket = data.join.ticket);
```

**Comment by kamilkisiela** [comment]
Does `Apollo.subscribe()` solve your issue?

**Comment by intellix** [comment]
works :) doing this:

```ts
return this.apollo
  .subscribe({
    query: updateSubscription,
    variables: { id: this.ticket.id },
  })
  .pipe(take(1))
  .subscribe(({ data }) => this.ticket = { ...this.ticket, ...data.onTicketUpdate });
```

**Comment by kamilkisiela** [comment]
@intellix can I close this one?
