### ISSUE TITLE
Is useGETForHashedQueries available?

### ISSUE THREAD

**Issue by pablocarreraest** [apollographql/apollo-angular#852]
Hi guys,

just want to know if useGETForHashedQueries: true to use for APQ to use GET method instead of POST.. 👨‍💻

I try to discover in this repo but I don't find any thing. 🧐

If not is posible to use "apollo-link-persisted-queries" in angular module?
Because a fail on that.

Hope you can help me.🙄

**Comment by kamilkisiela** [comment]
@pablocarreraest 
`yarn add apollo-link-persisted-queries@latest` v1.1.0

Here's an example of Automatic Persisted Queries, you can check the `useGETForHashedQueries` option there:
https://stackblitz.com/edit/apollo-angular-persisted-queries?file=app%2Fgraphql.module.ts
