### ISSUE TITLE
Client schema sample code for graphql-code-generator

### ISSUE THREAD

**Issue by vespertilian** [apollographql/apollo-angular#870]
@kamilkisiela 

I was linked to a pull request you had when asking about the @client directive on the graphql-code-generator project. 

Question issue
https://github.com/dotansimha/graphql-code-generator/issues/659#issuecomment-426608958
Your pull request
https://github.com/dotansimha/graphql-code-generator/pull/561

Logging an issue here as it fairly specific to Apollo-Angular

Do you have sample code for how you create the schema you can read into graphql-code-generator when using `apollo-state-link` and the @client directive.

To import into Apollo I would do something like this:

clientside-schema.ts
```ts
import gql from 'graphql-tag';
export const clientSideSchema = gql`
  type CurrentTheme {
    theme: String!
  }

  type Mutation {
    updateCurrentTheme(theme: String!): CurrentTheme
  }

  type Query {
    currentTheme: CurrentTheme
  }
`;
```

GraphQL config for client state
```ts
...
  const localState = withClientState({
    defaults: {
      ...themeDefault
    },
    resolvers: {
      Mutation: {
        ...themeResolverMutation
      }
    },
    typeDefs: clientSideSchema
  });
...
```

package.json
```json
    "generate-schema-frontend-client-schema": "rm -rf ./typings && gql-gen --schema http://localhost:4000/graphql --clientSchema ./src/app/clientside-schema.graphqls --template graphql-codegen-typescript-template --out ./typings/ \"./src/**/*.ts\""```

This is all in a sample repo under the Apollo branch here: 

https://github.com/vespertilian/wallaby-angular-node-yarn-workspaces/tree/apollo

Any help appreciated. 
Thanks

**Comment by kamilkisiela** [comment]
```typescript
import gql from 'graphql-tag';

// you can export it as schema variable
export const schema = gql`...`;

// or use export default
export default gql`...`
```

**Comment by vespertilian** [comment]
@kamilkisiela 

Thanks for the quick reply. 

I had tried that originally, I think, full example here: 
https://github.com/vespertilian/wallaby-angular-node-yarn-workspaces/tree/apollo

I keep getting an error:

```console
rm -rf ./typings && gql-gen --schema http://localhost:4000/graphql --clientSchema ./src/app/clientside-schema.ts --template graphql-codegen-typescript-template --out ./typings/ "./src/**/*.graphql.ts"
18:22:18.815 - info: Loading GraphQL Introspection from remote: http://localhost:4000/graphql... 
18:22:18.821 - info: Loading GraphQL schema object, text, ast, or introspection json from JavaScript ES6 export: ./src/app/clientside-schema.ts... 
18:22:18.823 - error: Unexpected token import 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Where it does not seem to like the import of GraphQL tag from in the TS file. 

So I am still a bit stuck. Which is why I was hoping you had a sample, maybe it's an issue with one of my dependencies. 

Thanks.

**Comment by kamilkisiela** [comment]
That's because you have to transpile ts files.

Try to add `--require ts-node/register/transpileOnly`

```
gql-gen --require ts-node/register/transpileOnly --schema http://localhost:4000/graphql --clientSchema ./src/app/clientside-schema.ts --template graphql-codegen-typescript-template --out ./typings/ "./src/**/*.graphql.ts"
```

Why transpileOnly? It will skip type checking so should be faster.

**Comment by DonaldWebb** [comment]
@kamilkisiela using ts-node@7.0.1  require should be
--require ts-node/register/transpile-only
