### ISSUE TITLE
ERROR in node_modules/apollo-angular/types.d.ts(10,58): error TS2304: Cannot find name 'Exclude'.

### ISSUE THREAD

**Issue by MennaRamadan** [apollographql/apollo-angular#873]
Hi all,
 I am new in jss sitecore, I run cmd command: **jss create myapp-demo angular**  to create jss app with angular template. jss app created successfully.
but while run the following command: **jss start**  the following compilation error thrown 
**ERROR in node_modules/apollo-angular/types.d.ts(10,58): error TS2304: Cannot find name 'Exclude'.**

my pacakge.json file conatins:
"dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/platform-server": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "apollo-angular": "^1.1.1",
    "apollo-angular-link-http-batch": "^1.1.1",
    "apollo-angular-link-persisted": "^1.0.0-beta.2",
    "apollo-cache-inmemory": "^1.2.5",
    "apollo-client": "^2.3.5",
    "apollo-link": "^1.2.2",
    "@ngx-meta/core": "^6.0.0-rc.1",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "@sitecore-jss/sitecore-jss": "^9.0.5",
    "@sitecore-jss/sitecore-jss-angular": "^9.0.5",
    "bootstrap": "^4.1.1",
    "core-js": "^2.4.1",
    "graphql": "0.13.0",
    "graphql-tag": "^2.9.2",
    "lodash": "^4.17.10",
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.0.0-rc.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.6",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.4",
    "@angular/language-service": "^6.0.4",
    "@sitecore-jss/sitecore-jss-angular-schematics": "^9.0.5",
    "@sitecore-jss/sitecore-jss-cli": "^9.0.6",
    "@sitecore-jss/sitecore-jss-dev-tools": "^9.0.6",
    "@sitecore-jss/sitecore-jss-manifest": "^9.0.5",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^8.10.17",
    "body-parser": "^1.18.2",
    "chalk": "^2.1.0",
    "codelyzer": "^4.0.2",
    "cookie-parser": "^1.4.3",
    "cross-env": "^5.0.5",
    "enhanced-resolve": "3.3.0",
    "express": "^4.16.2",
    "fs-extra": "^5.0.0",
    "isomorphic-fetch": "^2.2.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "npm-run-all": "^4.1.3",
    "protractor": "~5.1.2",
    "ts-loader": "^4.3.1",
    "ts-node": "^6.1.0",
    "tslint": "^5.7.0",
    "typescript": "2.7.2",
    "webpack-cli": "^3.0.2"
  }

can anyone help me?

**Comment by MennaRamadan** [comment]
> Hi all,
> I am new in jss sitecore, I run cmd command: **jss create myapp-demo angular** to create jss app with angular template. jss app created successfully.
> but while run the following command: **jss start** the following compilation error thrown
> **ERROR in node_modules/apollo-angular/types.d.ts(10,58): error TS2304: Cannot find name 'Exclude'.**
> 
> my pacakge.json file conatins:
> "dependencies": {
> "@angular/animations": "^6.0.3",
> "@angular/common": "^6.0.3",
> "@angular/compiler": "^6.0.3",
> "@angular/core": "^6.0.3",
> "@angular/forms": "^6.0.3",
> "@angular/http": "^6.0.3",
> "@angular/platform-browser": "^6.0.3",
> "@angular/platform-browser-dynamic": "^6.0.3",
> "@angular/platform-server": "^6.0.3",
> "@angular/router": "^6.0.3",
> "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
> "apollo-angular": "^1.1.1",
> "apollo-angular-link-http-batch": "^1.1.1",
> "apollo-angular-link-persisted": "^1.0.0-beta.2",
> "apollo-cache-inmemory": "^1.2.5",
> "apollo-client": "^2.3.5",
> "apollo-link": "^1.2.2",
> "@ngx-meta/core": "^6.0.0-rc.1",
> "@ngx-translate/core": "^10.0.2",
> "@ngx-translate/http-loader": "^3.0.1",
> "@sitecore-jss/sitecore-jss": "^9.0.5",
> "@sitecore-jss/sitecore-jss-angular": "^9.0.5",
> "bootstrap": "^4.1.1",
> "core-js": "^2.4.1",
> "graphql": "0.13.0",
> "graphql-tag": "^2.9.2",
> "lodash": "^4.17.10",
> "rxjs": "^6.2.1",
> "rxjs-compat": "^6.0.0-rc.0",
> "zone.js": "^0.8.14"
> },
> "devDependencies": {
> "@angular-devkit/build-angular": "~0.6.6",
> "@angular/cli": "^6.0.8",
> "@angular/compiler-cli": "^6.0.4",
> "@angular/language-service": "^6.0.4",
> "@sitecore-jss/sitecore-jss-angular-schematics": "^9.0.5",
> "@sitecore-jss/sitecore-jss-cli": "^9.0.6",
> "@sitecore-jss/sitecore-jss-dev-tools": "^9.0.6",
> "@sitecore-jss/sitecore-jss-manifest": "^9.0.5",
> "@types/jasmine": "~2.5.53",
> "@types/jasminewd2": "~2.0.2",
> "@types/node": "^8.10.17",
> "body-parser": "^1.18.2",
> "chalk": "^2.1.0",
> "codelyzer": "^4.0.2",
> "cookie-parser": "^1.4.3",
> "cross-env": "^5.0.5",
> "enhanced-resolve": "3.3.0",
> "express": "^4.16.2",
> "fs-extra": "^5.0.0",
> "isomorphic-fetch": "^2.2.1",
> "jasmine-core": "~2.6.2",
> "jasmine-spec-reporter": "~4.1.0",
> "karma": "~1.7.0",
> "karma-chrome-launcher": "~2.1.1",
> "karma-cli": "~1.0.1",
> "karma-coverage-istanbul-reporter": "^1.2.1",
> "karma-jasmine": "~1.1.0",
> "karma-jasmine-html-reporter": "^0.2.2",
> "npm-run-all": "^4.1.3",
> "protractor": "~5.1.2",
> "ts-loader": "^4.3.1",
> "ts-node": "^6.1.0",
> "tslint": "^5.7.0",
> "typescript": "2.7.2",
> "webpack-cli": "^3.0.2"
> }
> 
> can anyone help me?

issue solved by running the following command: **npm install typescript@2.9.2 --save-exact**

**Comment by Inpassor** [comment]
In my opinion, this is a very silly decision to lower the version of typescript.
Adding "@types/graphql" in the dev dependencies solves the issue.
