### ISSUE TITLE
Query.watch doesn't allow generic type like watchQuery

### ISSUE THREAD

**Issue by mattiLeBlanc** [apollographql/apollo-angular#877]
Versions:
 "apollo-angular": "^1.4.1",
"@angular/core": "^6.1.9",

I was going through the tutorials and ran into Query Watch.
However, when mapping the response to my Observable of users$ I got typing errors on on the `data` object.
```
this.data$ = this.allUsersGQL.watch()
      .valueChanges
      .pipe(
        map( result => result.data.allUsers )  // <-- `allUsers` not known
      )
```
When I use `watchQuery` I can pass in the generic type of the response:

```
interface User {
  firstName: string;
  lastName: string;
  id: string;

}

interface Response {
  allUsers: User[];
}


this.data$ = this.apollo
    .watchQuery<Response>({
      query: AllUsers,
    })
    .valueChanges
    .pipe(
      tap( result => this.loading = result.loading ),
      map( (result ) => result.data.allUsers )
    ),
    catchError( err => this.error = err ) ;
```

I this an omission in the code base of Apollo-Angular?  I would like to pass `<Response>` as a generic return type for `watch` as I do for `watchQuery`.

**Comment by kamilkisiela** [comment]
How your AllUsersGQL looks like? Did you created it by yourself? If so, then you should provide a generic type in it.

```typescript
import { Query } from 'apollo-angular';

export class AllUsersGQL extends Query<Response, Variables> {
  document = gql`...`
}
```

**Comment by mattiLeBlanc** [comment]
```
export class AllUsersGQL extends Query {
  document = gql`
    query {
      allUsers {
        firstName,
        lastName,
        id
      }
    }
  `;
}
```

I see you put the typing when you extend the query. Excellent!
