### ISSUE TITLE
How to do file upload mutation?

### ISSUE THREAD

**Issue by oexza** [apollographql/apollo-angular#89]
How does one include a file upload in a mutation?

Awesome project btw.

**Comment by kamilkisiela** [comment]
Related apollostack/apollo-client#586

**Comment by oexza** [comment]
thanks @kamilkisiela  i looked into that but i have a hard time transferring the idea in the referenced tutorial to angular 2. especially this bunch of code:

`            for(let { node, path } of new RecursiveIterator(request.variables)) {
                 if (node instanceof File) {
                    const id = Math.random().toString(36);
                    formData.append(id, node);
                    objectPath.set(request.variables, path.join('.'), id);
                }
}
`
i'd appreciate an example using angular2apollo. Thanks

Peace

**Comment by manuelfink** [comment]
Thinking in scalable architecture designs I prefer to directly upload to s3 or a comparable cloud asset service. Some services even provide resizing etc. Thus my way to go is to make a request to graphql returning a s3 signed hash token which can be used for a direct upload to s3. Sample see [froala editor s3 upload](https://www.froala.com/wysiwyg-editor/docs/sdks/nodejs/image-s3-upload). Gonna implement something similar in the next days.

**Comment by Eraldo** [comment]
@manuelfink Can you please share your solution?
If you are using a newer version/method I would prefer that one. ;)

**Comment by kamilkisiela** [comment]
It's more related to `apollo-client` and graphql server implementation than to `apollo-angular`
