### ISSUE TITLE
Using multiple client with Query

### ISSUE THREAD

**Issue by remicastaing** [apollographql/apollo-angular#903]
**Intended outcome**
I should be able to create a Query class using a named client by overwriting the client parameter:
```
@Injectable()
export class PokemonsGQL extends Query<PokemonsQuery, {}> {
  public client = 'client2';
  document = gql`
         query Pokemons  {pokemons(first: 10) { 
            id
            name
          }}
      `;
}
```

**Actual outcome**
The outcome of ```console.log(this.pokemonsQuery.client);```is ```client2```. And yet, apollo is querying the default client.

**How to reproduce the issue**
[Stackblitz example](https://stackblitz.com/edit/simple-apollo-angular-query-example)

**Comment by kamilkisiela** [comment]
Two things. First, update `apollo-angular`, second: `link: httpLink.create({ uri2 })` should be `link: httpLink.create({ uri: uri2 })`

**Comment by kamilkisiela** [comment]
@mention me if it's still an issue

**Comment by remicastaing** [comment]
Thanks @kamilkisiela. It works.
