### ISSUE TITLE
Debugging in NativeScript with Angular App

### ISSUE THREAD

**Issue by alonstar** [apollographql/apollo-angular#953]
Hi,
apollo-angular can work with nativescript-angular, but it doesn't show nothing in chrome-devtools Network panel when debugging.

How do I let it come out?

Thank you.

**Comment by kamilkisiela** [comment]
@alonstar do you use `apollo-angular-link-http`? If so then it uses the Angular's HttpClient that is overwritten by NativeScript, so it should be okay.

**Comment by alonstar** [comment]
@kamilkisiela 
Yes, I did.

```
import { NgModule } from '@angular/core';
import { ApolloModule, APOLLO_OPTIONS } from 'apollo-angular';
import { HttpLinkModule, HttpLink } from 'apollo-angular-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { environment } from '../environments/environment';
import { onError } from 'apollo-link-error';

const uri = environment.myCoreInfoApiUrl;

export function createApollo(httpLink: HttpLink) {
  const errorLink = onError(({ graphQLErrors, networkError }) => {
    if (graphQLErrors) {
      console.error('[GraphQL error]:', graphQLErrors);
    }
    if (networkError) {
      console.error('[Network error]:', networkError);
    }
  });

  return {
    link: errorLink.concat(httpLink.create({ uri })),
    cache: new InMemoryCache()
  };
}

@NgModule({
  exports: [ApolloModule, HttpLinkModule],
  providers: [
    {
      provide: APOLLO_OPTIONS,
      useFactory: createApollo,
      deps: [HttpLink]
    }
  ]
})
export class GraphQLModule {}

```

**Comment by alonstar** [comment]
Does apollo-angular-link-http implement the global.__inspector ?

From [NativeScript Note](https://docs.nativescript.org/tooling/debugging/chrome-devtools#network):
> For third-party modules that do network requests, additional code must be implemented to populate the Network Tab. See [Plugin author's guide](https://docs.nativescript.org/tooling/debugging/chrome-devtools#plugin-authors-guide ) for details on how to do it for your plugin.

**Comment by kamilkisiela** [comment]
> ***This is currently available for the built-in http module.** For third-party modules that do network requests, additional code must be implemented to populate the Network Tab. See Plugin author's guide for details on how to do it for your plugin.

So I guess it should work. Could you create a small working project that I can check and debug?

**Comment by alonstar** [comment]
hi ~
I found it works on windows, but I don't understand why I can't get network on MAC with iphone emulator. 
But I guess it shouldn't not be apollo-angular's issue. 

Thank you.
